### PR TITLE
Linux 4.12 compat: fix super_setup_bdi_name() call

### LINKED ISSUE #6147: Can mount only one filesystem at a time on kernel 4.12.0-rc1
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 
Linux Kernel                 | 4.12.0-rc1
Architecture                 | amd64
ZFS Version                  | 0.7.0-rc4_20_gf871ab6e
SPL Version                  | 0.7.0-rc4_1_g8f87971

### Describe the problem you're observing
Only one zfs filesystem can be mounted at the same time, even with multiple pools.

### Describe how to reproduce the problem
Build a 4.12.0-rc1 kernel and try to mount more than one filesystem.
```
monolith ~ # zpool list
NAME       SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
testpool   992M   152K   992M         -     0%     0%  1.00x  ONLINE  -
monolith ~ # zpool status
  pool: testpool
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	testpool    ONLINE       0     0     0
	  loop0     ONLINE       0     0     0

errors: No known data errors
monolith ~ # zfs list
NAME         USED  AVAIL  REFER  MOUNTPOINT
testpool     129K   864M    23K  /testpool
testpool/a    23K   864M    23K  /testpool/a
testpool/b    23K   864M    23K  /testpool/b
monolith ~ # zfs mount testpool/a
monolith ~ # zfs mount testpool/b
filesystem 'testpool/b' can not be mounted due to error 17
cannot mount 'testpool/b': Invalid argument
```

### Include any warning/errors/backtraces from the system logs
```
[ 1069.907662] sysfs: cannot create duplicate filename '/devices/virtual/bdi/zfs'
[ 1069.907666] ------------[ cut here ]------------
[ 1069.907670] WARNING: CPU: 1 PID: 3334 at fs/sysfs/dir.c:31 sysfs_warn_dup+0x56/0x70
[ 1069.907670] Modules linked in: loop rfcomm bnep zfs(PO) zunicode(PO) zavl(PO) icp(PO) amdkfd amd_iommu_v2 snd_hda_codec_realtek snd_hda_codec_generic amdgpu snd_hda_codec_hdmi snd_hda_intel zcommon(PO) btusb mfd_core btrtl snd_hda_codec ttm znvpair(PO) btbcm btintel fuse snd_hwdep spl(O) edac_mce_amd drm_kms_helper bluetooth snd_hda_core syscopyarea kvm_amd sysfillrect snd_pcm sysimgblt mxm_wmi ecdh_generic fb_sys_fops igb kvm drm snd_timer ptp snd joydev irqbypass pps_core mousedev evdev soundcore alx i2c_algo_bit input_leds dca i2c_piix4 mdio acpi_cpufreq tpm_infineon i2c_designware_platform 8250_dw wmi tpm_tis i2c_designware_core tpm_tis_core button tpm sch_fq_codel it87(O) hwmon_vid ext4 crc16 jbd2 fscrypto mbcache sd_mod hid_lenovo led_class hid_generic usbhid hid crct10dif_pclmul crc32_pclmul
[ 1069.907694]  crc32c_intel ghash_clmulni_intel pcbc aesni_intel aes_x86_64 crypto_simd glue_helper cryptd xhci_pci ahci xhci_hcd libahci libata ccp usbcore rng_core scsi_mod usb_common serio dm_mirror dm_region_hash dm_log dm_mod dax
[ 1069.907702] CPU: 1 PID: 3334 Comm: mount.zfs Tainted: P        W  O    4.12.0-rc1 #2
[ 1069.907702] Hardware name: Gigabyte Technology Co., Ltd. AX370-Gaming K7/AX370-Gaming K7, BIOS F4a 05/08/2017
[ 1069.907703] task: ffff88040b6a9b80 task.stack: ffffc9000ddbc000
[ 1069.907704] RIP: 0010:sysfs_warn_dup+0x56/0x70
[ 1069.907705] RSP: 0018:ffffc9000ddbfab0 EFLAGS: 00010282
[ 1069.907706] RAX: 0000000000000042 RBX: ffff8804081a7000 RCX: 0000000000000000
[ 1069.907706] RDX: 0000000000000000 RSI: ffff88041ec4db88 RDI: ffff88041ec4db88
[ 1069.907706] RBP: ffffc9000ddbfac8 R08: 0000000000000773 R09: 0000000000000004
[ 1069.907707] R10: 0000000000000000 R11: 0000000000000001 R12: ffff88040c5b06a0
[ 1069.907707] R13: ffff88040c0b1e10 R14: ffff8803f9d65000 R15: 0000000000000000
[ 1069.907708] FS:  00007fb35166a780(0000) GS:ffff88041ec40000(0000) knlGS:0000000000000000
[ 1069.907708] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1069.907709] CR2: 00007fb34fc2bb6e CR3: 0000000387778000 CR4: 00000000003406e0
[ 1069.907709] Call Trace:
[ 1069.907712]  sysfs_create_dir_ns+0x77/0x90
[ 1069.907714]  kobject_add_internal+0xaa/0x2b0
[ 1069.907715]  kobject_add+0x71/0xd0
[ 1069.907716]  ? refcount_inc+0x9/0x30
[ 1069.907718]  device_add+0x107/0x620
[ 1069.907719]  device_create_groups_vargs+0xe4/0xf0
[ 1069.907720]  device_create_vargs+0x16/0x20
[ 1069.907722]  bdi_register_va.part.1+0x28/0x180
[ 1069.907723]  bdi_register_va+0x1b/0x20
[ 1069.907724]  super_setup_bdi_name+0x87/0xe0
[ 1069.907736]  ? dmu_objset_rele+0x42/0x60 [zfs]
[ 1069.907748]  ? dsl_prop_get+0x7b/0xb0 [zfs]
[ 1069.907750]  ? spl_kmem_free+0x2a/0x40 [spl]
[ 1069.907760]  zfs_domount+0x110/0x370 [zfs]
[ 1069.907769]  ? zpl_mount+0x50/0x50 [zfs]
[ 1069.907779]  ? zpl_mount+0x50/0x50 [zfs]
[ 1069.907788]  zpl_fill_super+0x2c/0x40 [zfs]
[ 1069.907789]  mount_nodev+0x4d/0xa0
[ 1069.907798]  zpl_mount+0x34/0x50 [zfs]
[ 1069.907799]  mount_fs+0x32/0x150
[ 1069.907801]  vfs_kern_mount.part.7+0x5d/0x110
[ 1069.907802]  do_mount+0x528/0xc50
[ 1069.907803]  ? __check_object_size+0x12c/0x1a2
[ 1069.907804]  SyS_mount+0x5a/0xe0
[ 1069.907806]  entry_SYSCALL_64_fastpath+0x1a/0xa5
[ 1069.907807] RIP: 0033:0x7fb35094e4ca
[ 1069.907807] RSP: 002b:00007fff25cbe1d8 EFLAGS: 00000206 ORIG_RAX: 00000000000000a5
[ 1069.907808] RAX: ffffffffffffffda RBX: 00000000017d0060 RCX: 00007fb35094e4ca
[ 1069.907808] RDX: 00000000004023e6 RSI: 00007fff25cc22f0 RDI: 00007fff25cc444c
[ 1069.907809] RBP: 00000000017d1180 R08: 00007fff25cbf2f0 R09: 00007fb3509913a0
[ 1069.907809] R10: 0000000001000000 R11: 0000000000000206 R12: 00007fff25cbf2f0
[ 1069.907809] R13: 0000000000000005 R14: 0000000000000000 R15: 0000000000000000
[ 1069.907810] Code: 85 c0 48 89 c3 74 12 b9 00 10 00 00 48 89 c2 31 f6 4c 89 ef e8 9c c9 ff ff 4c 89 e2 48 89 de 48 c7 c7 80 14 94 81 e8 d9 67 ef ff <0f> ff 48 89 df e8 40 c2 f5 ff 5b 41 5c 41 5d 5d c3 66 0f 1f 84 
[ 1069.907823] ---[ end trace 58c8ea15857b8a77 ]---
[ 1069.907824] kobject_add_internal failed for zfs with -EEXIST, don't try to register things with the same name in the same directory.
[ 1069.907826] ------------[ cut here ]------------
[ 1069.907827] WARNING: CPU: 1 PID: 3334 at lib/kobject.c:240 kobject_add_internal+0x269/0x2b0
[ 1069.907828] Modules linked in: loop rfcomm bnep zfs(PO) zunicode(PO) zavl(PO) icp(PO) amdkfd amd_iommu_v2 snd_hda_codec_realtek snd_hda_codec_generic amdgpu snd_hda_codec_hdmi snd_hda_intel zcommon(PO) btusb mfd_core btrtl snd_hda_codec ttm znvpair(PO) btbcm btintel fuse snd_hwdep spl(O) edac_mce_amd drm_kms_helper bluetooth snd_hda_core syscopyarea kvm_amd sysfillrect snd_pcm sysimgblt mxm_wmi ecdh_generic fb_sys_fops igb kvm drm snd_timer ptp snd joydev irqbypass pps_core mousedev evdev soundcore alx i2c_algo_bit input_leds dca i2c_piix4 mdio acpi_cpufreq tpm_infineon i2c_designware_platform 8250_dw wmi tpm_tis i2c_designware_core tpm_tis_core button tpm sch_fq_codel it87(O) hwmon_vid ext4 crc16 jbd2 fscrypto mbcache sd_mod hid_lenovo led_class hid_generic usbhid hid crct10dif_pclmul crc32_pclmul
[ 1069.907841]  crc32c_intel ghash_clmulni_intel pcbc aesni_intel aes_x86_64 crypto_simd glue_helper cryptd xhci_pci ahci xhci_hcd libahci libata ccp usbcore rng_core scsi_mod usb_common serio dm_mirror dm_region_hash dm_log dm_mod dax
[ 1069.907846] CPU: 1 PID: 3334 Comm: mount.zfs Tainted: P        W  O    4.12.0-rc1 #2
[ 1069.907846] Hardware name: Gigabyte Technology Co., Ltd. AX370-Gaming K7/AX370-Gaming K7, BIOS F4a 05/08/2017
[ 1069.907847] task: ffff88040b6a9b80 task.stack: ffffc9000ddbc000
[ 1069.907847] RIP: 0010:kobject_add_internal+0x269/0x2b0
[ 1069.907848] RSP: 0018:ffffc9000ddbfb00 EFLAGS: 00010286
[ 1069.907848] RAX: 0000000000000078 RBX: ffff8803f9d65010 RCX: 0000000000000006
[ 1069.907849] RDX: 0000000000000000 RSI: 0000000000000086 RDI: ffff88041ec4db80
[ 1069.907849] RBP: ffffc9000ddbfb30 R08: 00000000000007a8 R09: 0000000000000004
[ 1069.907849] R10: ffffea0010206800 R11: 0000000000000001 R12: ffff88041e905960
[ 1069.907850] R13: 00000000ffffffef R14: ffff8803f9d65000 R15: 0000000000000000
[ 1069.907850] FS:  00007fb35166a780(0000) GS:ffff88041ec40000(0000) knlGS:0000000000000000
[ 1069.907851] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1069.907851] CR2: 00007fb34fc2bb6e CR3: 0000000387778000 CR4: 00000000003406e0
[ 1069.907851] Call Trace:
[ 1069.907852]  kobject_add+0x71/0xd0
[ 1069.907853]  ? refcount_inc+0x9/0x30
[ 1069.907854]  device_add+0x107/0x620
[ 1069.907855]  device_create_groups_vargs+0xe4/0xf0
[ 1069.907856]  device_create_vargs+0x16/0x20
[ 1069.907857]  bdi_register_va.part.1+0x28/0x180
[ 1069.907858]  bdi_register_va+0x1b/0x20
[ 1069.907858]  super_setup_bdi_name+0x87/0xe0
[ 1069.907868]  ? dmu_objset_rele+0x42/0x60 [zfs]
[ 1069.907880]  ? dsl_prop_get+0x7b/0xb0 [zfs]
[ 1069.907882]  ? spl_kmem_free+0x2a/0x40 [spl]
[ 1069.907892]  zfs_domount+0x110/0x370 [zfs]
[ 1069.907901]  ? zpl_mount+0x50/0x50 [zfs]
[ 1069.907910]  ? zpl_mount+0x50/0x50 [zfs]
[ 1069.907920]  zpl_fill_super+0x2c/0x40 [zfs]
[ 1069.907920]  mount_nodev+0x4d/0xa0
[ 1069.907930]  zpl_mount+0x34/0x50 [zfs]
[ 1069.907931]  mount_fs+0x32/0x150
[ 1069.907932]  vfs_kern_mount.part.7+0x5d/0x110
[ 1069.907933]  do_mount+0x528/0xc50
[ 1069.907933]  ? __check_object_size+0x12c/0x1a2
[ 1069.907935]  SyS_mount+0x5a/0xe0
[ 1069.907936]  entry_SYSCALL_64_fastpath+0x1a/0xa5
[ 1069.907936] RIP: 0033:0x7fb35094e4ca
[ 1069.907937] RSP: 002b:00007fff25cbe1d8 EFLAGS: 00000206 ORIG_RAX: 00000000000000a5
[ 1069.907937] RAX: ffffffffffffffda RBX: 00000000017d0060 RCX: 00007fb35094e4ca
[ 1069.907937] RDX: 00000000004023e6 RSI: 00007fff25cc22f0 RDI: 00007fff25cc444c
[ 1069.907938] RBP: 00000000017d1180 R08: 00007fff25cbf2f0 R09: 00007fb3509913a0
[ 1069.907938] R10: 0000000001000000 R11: 0000000000000206 R12: 00007fff25cbf2f0
[ 1069.907938] R13: 0000000000000005 R14: 0000000000000000 R15: 0000000000000000
[ 1069.907939] Code: 49 89 c4 48 85 ff 0f 84 44 fe ff ff 48 83 c7 18 e9 01 fe ff ff 48 8b 13 48 c7 c6 70 7c 84 81 48 c7 c7 f8 81 94 81 e8 86 45 e7 ff <0f> ff e9 92 fe ff ff 0f ff eb a5 0f ff eb 98 41 bd fe ff ff ff 
[ 1069.907952] ---[ end trace 58c8ea15857b8a78 ]---

```

### PR DESCRIPTION
**Pull request by loli10K**
### Description

Add a format parameter to `super_setup_bdi_name()` so we don't create duplicate names in /sys/devices/virtual/bdi which prevents more than one ZFS filesystem from being mounted at a time:

```
root@debian-8-zfs:~# uname -a
Linux debian-8-zfs 4.12.0-rc1 #1 SMP Sat May 20 12:52:46 CEST 2017 x86_64 GNU/Linux
root@debian-8-zfs:~# ls -l /sys/devices/virtual/bdi/ | grep zfs
drwxr-xr-x 3 root root 0 May 20 13:57 zfs
root@debian-8-zfs:~# zfs create $POOLNAME/fs
filesystem 'testpool/fs' can not be mounted due to error 17
cannot mount 'testpool/fs': Invalid argument
filesystem successfully created, but not mounted
root@debian-8-zfs:~# ls -l /sys/devices/virtual/bdi/ | grep zfs
drwxr-xr-x 3 root root 0 May 20 13:57 zfs
root@debian-8-zfs:~# 
root@debian-8-zfs:~# dmesg
[  150.155657] sysfs: cannot create duplicate filename '/devices/virtual/bdi/zfs'
[  150.155669] ------------[ cut here ]------------
[  150.155673] WARNING: CPU: 1 PID: 2927 at fs/sysfs/dir.c:31 sysfs_warn_dup+0x58/0x70
[  150.155674] Modules linked in: zfs(POE) joydev(E) acpi_cpufreq(E) sg(E) evdev(E) pvpanic(E) tpm_tis(E) virtio_balloon(E) virtio_console(E) serio_raw(E) i2c_piix4(E) tpm_tis_core(E) tpm(E) pcspkr(E) button(E) zunicode(POE) zavl(POE) icp(POE) zcommon(POE) znvpair(POE) spl(OE) usbhid(E) sd_mod(E) sr_mod(E) ata_generic(E) virtio_blk(E) 8139too(E) psmouse(E) ahci(E) libahci(E) ehci_pci(E) uhci_hcd(E) ehci_hcd(E) 8139cp(E) virtio_pci(E) mii(E) virtio_ring(E) usbcore(E) ata_piix(E) virtio(E)
[  150.155692] CPU: 1 PID: 2927 Comm: mount.zfs Tainted: P        W  OE   4.12.0-rc1 #1
[  150.155693] Hardware name: Bochs Bochs, BIOS Bochs 01/01/2011
[  150.155694] task: ffff915c839da080 task.stack: ffffba2c43cb8000
[  150.155695] RIP: 0010:sysfs_warn_dup+0x58/0x70
[  150.155696] RSP: 0018:ffffba2c43cbba98 EFLAGS: 00010282
[  150.155697] RAX: 0000000000000042 RBX: ffff915c8f83a000 RCX: 0000000000000000
[  150.155698] RDX: 0000000000000000 RSI: ffff915c9fc4e048 RDI: ffff915c9fc4e048
[  150.155699] RBP: ffffba2c43cbbab0 R08: 0000000000000001 R09: 0000000000000381
[  150.155699] R10: ffff915c9a64a700 R11: 0000000000000381 R12: ffff915c926c6f20
[  150.155700] R13: ffff915bb03161e0 R14: ffff915c8e684c18 R15: ffff915c8d097018
[  150.155701] FS:  00007ff575485780(0000) GS:ffff915c9fc40000(0000) knlGS:0000000000000000
[  150.155702] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  150.155703] CR2: 00007ff5749cfe7f CR3: 000000010d560000 CR4: 00000000000006e0
[  150.155706] Call Trace:
[  150.155708]  sysfs_create_dir_ns+0x77/0x90
[  150.155711]  kobject_add_internal+0xc0/0x2d0
[  150.155712]  kobject_add+0x71/0xd0
[  150.155715]  ? refcount_inc+0x9/0x30
[  150.155717]  device_add+0x117/0x670
[  150.155718]  device_create_groups_vargs+0xe0/0xf0
[  150.155720]  device_create_vargs+0x16/0x20
[  150.155722]  bdi_register_va.part.11+0x2e/0x1b0
[  150.155723]  bdi_register_va+0x1b/0x20
[  150.155725]  super_setup_bdi_name+0x87/0xf0
[  150.155765]  ? dsl_prop_get+0x7a/0xa0 [zfs]
[  150.155795]  zfs_domount+0x121/0x440 [zfs]
[  150.155825]  zpl_fill_super+0x40/0x110 [zfs]
[  150.155853]  ? zpl_statfs+0x110/0x110 [zfs]
[  150.155855]  mount_nodev+0x4e/0xa0
[  150.155882]  zpl_mount+0x34/0x50 [zfs]
[  150.155884]  mount_fs+0x38/0x150
[  150.155886]  vfs_kern_mount+0x64/0x130
[  150.155887]  do_mount+0x1e5/0xcd0
[  150.155889]  ? _copy_from_user+0x33/0x70
[  150.155890]  SyS_mount+0x94/0xd0
[  150.155892]  entry_SYSCALL_64_fastpath+0x1e/0xa9
[  150.155893] RIP: 0033:0x7ff573aa9fda
[  150.155894] RSP: 002b:00007ffec9519fa8 EFLAGS: 00000202 ORIG_RAX: 00000000000000a5
[  150.155895] RAX: ffffffffffffffda RBX: 000000000153c060 RCX: 00007ff573aa9fda
[  150.155896] RDX: 00000000004022e6 RSI: 00007ffec951e080 RDI: 00007ffec951fee0
[  150.155896] RBP: 00007ffec9519f90 R08: 00007ffec951b080 R09: 0000000001543650
[  150.155897] R10: 0000000001000000 R11: 0000000000000202 R12: 00007ffec951b080
[  150.155898] R13: 0000000000000005 R14: 0000000000000000 R15: 0000000000000001
[  150.155898] Code: 48 89 c3 74 12 b9 00 10 00 00 48 89 c2 31 f6 4c 89 ef e8 5c c8 ff ff 4c 89 e2 48 89 de 48 c7 c7 68 29 ab 88 31 c0 e8 7f 2c ee ff <0f> ff 48 89 df e8 9e 1a f5 ff 5b 41 5c 41 5d 5d c3 0f 1f 80 00 
[  150.155916] ---[ end trace a2337445839d0b0e ]---
[  150.155918] kobject_add_internal failed for zfs with -EEXIST, don't try to register things with the same name in the same directory.
[  150.155925] ------------[ cut here ]------------
[  150.155928] WARNING: CPU: 1 PID: 2927 at lib/kobject.c:240 kobject_add_internal+0x284/0x2d0
[  150.155928] Modules linked in: zfs(POE) joydev(E) acpi_cpufreq(E) sg(E) evdev(E) pvpanic(E) tpm_tis(E) virtio_balloon(E) virtio_console(E) serio_raw(E) i2c_piix4(E) tpm_tis_core(E) tpm(E) pcspkr(E) button(E) zunicode(POE) zavl(POE) icp(POE) zcommon(POE) znvpair(POE) spl(OE) usbhid(E) sd_mod(E) sr_mod(E) ata_generic(E) virtio_blk(E) 8139too(E) psmouse(E) ahci(E) libahci(E) ehci_pci(E) uhci_hcd(E) ehci_hcd(E) 8139cp(E) virtio_pci(E) mii(E) virtio_ring(E) usbcore(E) ata_piix(E) virtio(E)
[  150.155942] CPU: 1 PID: 2927 Comm: mount.zfs Tainted: P        W  OE   4.12.0-rc1 #1
[  150.155942] Hardware name: Bochs Bochs, BIOS Bochs 01/01/2011
[  150.155943] task: ffff915c839da080 task.stack: ffffba2c43cb8000
[  150.155944] RIP: 0010:kobject_add_internal+0x284/0x2d0
[  150.155945] RSP: 0018:ffffba2c43cbbae8 EFLAGS: 00010282
[  150.155946] RAX: 0000000000000078 RBX: ffff915c8d097010 RCX: 0000000000000006
[  150.155946] RDX: 0000000000000000 RSI: 0000000000000082 RDI: ffff915c9fc4e040
[  150.155947] RBP: ffffba2c43cbbb18 R08: 0000000000000001 R09: 00000000000003b2
[  150.155948] R10: ffff915c9a64a700 R11: 00000000000003b2 R12: 00000000ffffffef
[  150.155948] R13: ffff915bb02f0a80 R14: ffff915c8e684c18 R15: ffff915c8d097018
[  150.155949] FS:  00007ff575485780(0000) GS:ffff915c9fc40000(0000) knlGS:0000000000000000
[  150.155950] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  150.155951] CR2: 00007ff5749cfe7f CR3: 000000010d560000 CR4: 00000000000006e0
[  150.155953] Call Trace:
[  150.155954]  kobject_add+0x71/0xd0
[  150.155956]  ? refcount_inc+0x9/0x30
[  150.155957]  device_add+0x117/0x670
[  150.155959]  device_create_groups_vargs+0xe0/0xf0
[  150.155960]  device_create_vargs+0x16/0x20
[  150.155961]  bdi_register_va.part.11+0x2e/0x1b0
[  150.155962]  bdi_register_va+0x1b/0x20
[  150.155964]  super_setup_bdi_name+0x87/0xf0
[  150.155989]  ? dsl_prop_get+0x7a/0xa0 [zfs]
[  150.156018]  zfs_domount+0x121/0x440 [zfs]
[  150.156046]  zpl_fill_super+0x40/0x110 [zfs]
[  150.156073]  ? zpl_statfs+0x110/0x110 [zfs]
[  150.156075]  mount_nodev+0x4e/0xa0
[  150.156102]  zpl_mount+0x34/0x50 [zfs]
[  150.156104]  mount_fs+0x38/0x150
[  150.156105]  vfs_kern_mount+0x64/0x130
[  150.156106]  do_mount+0x1e5/0xcd0
[  150.156108]  ? _copy_from_user+0x33/0x70
[  150.156109]  SyS_mount+0x94/0xd0
[  150.156111]  entry_SYSCALL_64_fastpath+0x1e/0xa9
[  150.156111] RIP: 0033:0x7ff573aa9fda
[  150.156112] RSP: 002b:00007ffec9519fa8 EFLAGS: 00000202 ORIG_RAX: 00000000000000a5
[  150.156113] RAX: ffffffffffffffda RBX: 000000000153c060 RCX: 00007ff573aa9fda
[  150.156114] RDX: 00000000004022e6 RSI: 00007ffec951e080 RDI: 00007ffec951fee0
[  150.156114] RBP: 00007ffec9519f90 R08: 00007ffec951b080 R09: 0000000001543650
[  150.156115] R10: 0000000001000000 R11: 0000000000000202 R12: 00007ffec951b080
[  150.156116] R13: 0000000000000005 R14: 0000000000000000 R15: 0000000000000001
[  150.156116] Code: 7b 20 49 89 c5 48 85 ff 0f 84 3d fe ff ff e9 e4 fd ff ff 48 8b 13 48 c7 c6 00 bd 89 88 48 c7 c7 08 97 af 88 31 c0 e8 03 66 cc ff <0f> ff e9 8f fe ff ff 0f 0b 0f 0b 0f 0b 0f ff eb 9a 0f ff eb 8d 
[  150.156134] ---[ end trace a2337445839d0b0f ]---
```

### Motivation and Context

Fix #6147

### How Has This Been Tested?

Manually tested on linux-4.12-rc1

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

File: include/linux/vfs_compat.h [hunk 1]
```diff
@@ -74,10 +74,16 @@ truncate_setsize(struct inode *ip, loff_t new)
...
+
 static inline int
 zpl_bdi_setup(struct super_block *sb, char *name)
 {
-	return (super_setup_bdi_name(sb, name));
+	char tmp[32];
+
+	sprintf(tmp, "%.28s%s", name, "-%d");
+	return super_setup_bdi_name(sb, tmp,
+	    atomic_long_inc_return(&zfs_bdi_seq));
```
Comment (tuxoko) [inline include/linux/vfs_compat.h]: There's no reason to use two format functions, fold sprintf into `super_setup_bdi_name`

Comment (loli10K) [inline include/linux/vfs_compat.h]: @tuxoko did you mean something like the following?

```c
super_setup_bdi_name(sb, "%.28s-%ld", name, atomic_long_inc_return(&zfs_bdi_seq));
```

I basically just copy/pasted the code from https://github.com/zfsonlinux/zfs/blob/5547c2f1bf49802835fd6c52f15115ba344a2a8b/include/linux/vfs_compat.h#L85, should we update that too?

Comment (tuxoko) [inline include/linux/vfs_compat.h]: Yeah, we should do that. This code is ugly and kinda dangerous, in that if the name is user supplied, then you're using a user supplied format string.
