### PR TITLE
bpobj_iterate overflows the stack

### LINKED ISSUE #7674: nested bpobj causes stack overflow on pool import
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	| 14
Linux Kernel	| 4.4.0-111-generic #134~14.04.1-Ubuntu SMP Mon Jan 15 15:39:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Architecture	| 
ZFS Version	| 0.6.5.9
SPL Version	| 0.6.5.9

### Describe the problem you're observing
Pool import fails due to dereference of wrong pointers because of stack overflow.

### Describe how to reproduce the problem
Datto has a certain pool that reproduces the problem.

### LINKED ISSUE #7908: nested bpobj causes leak of subobj
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| illumos
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	| 

### Describe the problem you're observing

After a `zfs destroy`, an object of type `bpobj subobj` remains allocated but not referenced.  This is reported by yet-to-be-upstreamed enhancements to zdb.

### Describe how to reproduce the problem

(updated 10/2/2018)
```
#!/bin/bash

zfs create -o compress=zle -o redundant_metadata=most -o recordsize=512 test/fs

# note, each 16K snapshots results in one layer of recursive bpobj subobj's
n=17000

echo creating file
dd if=/dev/urandom of=/test/fs/file conv=notrunc bs=$((512*100)) count=$((n/100))
zfs snapshot test/fs@first


for (( i=0; i<n; i=i+1 )); do
        echo $i
        dd if=/dev/zero of=/test/fs/file conv=notrunc bs=512 seek=$i count=1 >&/dev/null
        zfs snapshot test/fs@$i
        zfs destroy test/fs@$((i-1))
done

set -x

zdb -ddd test | grep subobj
zfs destroy test/fs@first
zdb -ddd test | grep subobj
```

output:
```
    $ zdb -ddd test | grep subobj
            83    1   128K   128K      0   128K    0.00  bpobj subobj
         26162    1   128K   128K   196K   256K  100.00  bpobj subobj
         30460    1   128K   128K     9K   128K  100.00  bpobj subobj
        Pool snapshot frees: object 11, 0 local blkptrs, 0 subobjs in object 83, 0 (0/0 comp)

    $ zfs destroy test/fs@first

    $ zdb -ddd test | grep subobj
            83    1   128K   128K      0   128K    0.00  bpobj subobj
         26162    1   128K   128K      0   128K    0.00  bpobj subobj
        Pool snapshot frees: object 11, 0 local blkptrs, 0 subobjs in object 83, 0 (0/0 comp)
    MOS object 26162 (bpobj subobj) leaked
```

Proposed fix (updated 9/17/2018):
```
diff --git a/usr/src/uts/common/fs/zfs/bpobj.c b/usr/src/uts/common/fs/zfs/bpobj.c
index a47bcd37dfe..fcb2989846d 100644
--- a/usr/src/uts/common/fs/zfs/bpobj.c
+++ b/usr/src/uts/common/fs/zfs/bpobj.c
@@ -352,6 +352,16 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, int64_t start,
                        bpo->bpo_phys->bpo_comp -= comp_before - comp_after;
                        bpo->bpo_phys->bpo_uncomp -=
                            uncomp_before - uncomp_after;
+
+                       if (err == 0 && sublist.bpo_havesubobj &&
+                           sublist.bpo_phys->bpo_subobjs != 0) {
+                               err = dmu_object_free(bpo->bpo_os,
+                                   sublist.bpo_phys->bpo_subobjs, tx);
+                               if (err != 0)
+                                       break;
+                               dmu_buf_will_dirty(sublist.bpo_dbuf, tx);
+                               sublist.bpo_phys->bpo_subobjs = 0;
+                       }
                }

                bpobj_close(&sublist);
```

See also https://github.com/zfsonlinux/zfs/pull/7675 and https://github.com/zfsonlinux/zfs/issues/7674

### PR DESCRIPTION
**Pull request by PaulZ-98**
The function bpobj_iterate overflows the stack when bpobjs
are deeply nested.  Rewrite the function to eliminate the recursion.

Signed-off-by: Paul Zuchowski <pzuchowski@datto.com>
Fixes #7674
Fixes #7908

Eliminate recursion from bpobj_iterate_impl.

### Description

Place items onto a list (stack) and pop them off the stack to work on them.

### Motivation and Context

A Datto server could not import the pool because the function bpobj_iterate overflowed the stack.

https://github.com/zfsonlinux/zfs/issues/7674
https://github.com/zfsonlinux/zfs/issues/7908

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
If possible can you include a backtrace of the offending stack from `/sys/kernel/debug/tracing/stack_trace`.  This will include the actual stack frame sizes.  It may be possible to resolve this issue instead by slimming down the worst offenders.  For example, it looks like moving the `dmu_object_info_t doi` and `bpobj_t sublist` to the heap would be a substantial savings.

**Comment by PaulZ-98** [comment]
I don't have the /sys/kernel/debug/tracing/stack_trace but this was captured:
```
server1890 login: [67823.699272] Kernel panic - not syncing: corrupted stack end detected inside scheduler
[67823.699272]
[67823.708618] CPU: 9 PID: 31471 Comm: txg_sync Tainted: P           OE   4.4.0-111-generic #134~14.04.1-Ubuntu
[67823.718455] Hardware name: Supermicro X9DRD-7LN4F(-JBOD)/X9DRD-EF/X9DRD-7LN4F, BIOS 3.0a 12/05/2013
[67823.727510]  0000000000000000 ffff8800357cc7f8 ffffffff813e07ac ffffffff81cbd850
[67823.735036]  0000000000017300 ffff8800357cc870 ffffffff81184aec ffff881f00000008
[67823.742551]  ffff8800357cc880 ffff8800357cc820 ffff880000000001 0000000000000202
[67823.750054] Call Trace:
[67823.752533]  [<ffffffff813e07ac>] dump_stack+0x63/0x87
[67823.757710]  [<ffffffff81184aec>] panic+0xc8/0x20f
[67823.762520]  [<ffffffff8180ca73>] __schedule+0x743/0x7e0
[67823.767854]  [<ffffffff8180cb45>] schedule+0x35/0x80
[67823.772850]  [<ffffffff8180f507>] schedule_timeout+0x237/0x2d0
[67823.778814]  [<ffffffffc02bdc6b>] ? vdev_mirror_io_start+0xab/0x180 [zfs]
[67823.785686]  [<ffffffffc02bd3e0>] ? vdev_config_sync+0x140/0x140 [zfs]
[67823.792233]  [<ffffffff810f11fb>] ? ktime_get+0x3b/0xb0
[67823.797499]  [<ffffffff8180c2c6>] io_schedule_timeout+0xa6/0x110
[67823.803562]  [<ffffffffc019f754>] cv_wait_common+0xa4/0x110 [spl]
[67823.809689]  [<ffffffff810c05e0>] ? prepare_to_wait_event+0xf0/0xf0
[67823.815993]  [<ffffffffc019f818>] __cv_wait_io+0x18/0x20 [spl]
[67823.821945]  [<ffffffffc02f9373>] zio_wait+0xb3/0x140 [zfs]
[67823.827589]  [<ffffffffc025d020>] dbuf_read+0x2e0/0x870 [zfs]
[67823.833413]  [<ffffffffc025db41>] __dbuf_hold_impl+0x451/0x4e0 [zfs]
[67823.839861]  [<ffffffffc025d872>] __dbuf_hold_impl+0x182/0x4e0 [zfs]
[67823.846282]  [<ffffffffc025dc43>] dbuf_hold_impl+0x73/0xa0 [zfs]
[67823.852352]  [<ffffffffc025df20>] dbuf_hold+0x20/0x30 [zfs]
[67823.858016]  [<ffffffffc0275f61>] dnode_hold_impl+0x91/0x500 [zfs]
[67823.864228]  [<ffffffff8180e6d2>] ? mutex_lock+0x12/0x2f
[67823.869603]  [<ffffffffc02765f3>] ? dnode_setdirty+0x93/0x170 [zfs]
[67823.875938]  [<ffffffffc02763e9>] dnode_hold+0x19/0x20 [zfs]
[67823.881657]  [<ffffffffc0266e01>] dmu_object_info+0x21/0x50 [zfs]
[67823.887816]  [<ffffffffc02764f8>] ? dnode_rele_and_unlock+0x48/0x80 [zfs]
[67823.894662]  [<ffffffffc0259089>] bpobj_open+0x39/0x170 [zfs]
[67823.900465]  [<ffffffffc0276559>] ? dnode_rele+0x29/0x30 [zfs]
[67823.906354]  [<ffffffffc025a01e>] bpobj_iterate_impl+0x51e/0x7b0 [zfs]
[67823.912950]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67823.920045]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67823.926623]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67823.932770]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67823.939866]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67823.946443]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67823.952589]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67823.959685]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67823.966260]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67823.972399]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67823.979493]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67823.986070]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67823.992205]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67823.999297]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.005872]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.012009]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.019106]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.025684]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.031828]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.038926]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.045501]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.051638]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.058735]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.065312]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.071459]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.078554]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.085122]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.091260]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.098357]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.104933]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.111071]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.118167]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.124774]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.130954]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.138068]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.144668]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.150841]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.157984]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.164591]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.170755]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.177894]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.184499]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.190670]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.197795]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.204396]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.210560]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.217683]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.224275]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.230449]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.237562]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.244156]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.250335]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.257460]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.264070]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.270232]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.277367]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.283958]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.290121]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.297256]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.303846]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.310026]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.317161]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.323761]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.329924]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.337057]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.343658]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.349820]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.356936]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.363537]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.369711]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.376833]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.383446]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.389615]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.396757]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.403350]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.409538]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.416671]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.423289]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.429460]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.436579]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.443184]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.449351]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.456468]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.463095]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.469290]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.476416]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.483027]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.489210]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.496330]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.502921]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.509102]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.516218]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.522821]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.529016]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.536142]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.542733]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.548906]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.556056]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.562657]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.568827]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.575964]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.582563]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.588742]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.595867]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.602462]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.608648]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.615774]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.622375]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67824.628545]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.635704]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67824.642307]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67824.649432]  [<ffffffffc025a2c4>] bpobj_iterate+0x14/0x20 [zfs]
[67824.655447]  [<ffffffffc02908b4>] dsl_scan_sync+0x584/0xbf0 [zfs]
[67824.661603]  [<ffffffffc019a0c6>] ? spl_kmem_cache_free+0x166/0x1c0 [spl]
[67824.668497]  [<ffffffffc02f5d91>] ? zio_destroy+0xc1/0xd0 [zfs]
[67824.674501]  [<ffffffffc02a10d5>] spa_sync+0x3b5/0xad0 [zfs]
[67824.680200]  [<ffffffff810c05f2>] ? autoremove_wake_function+0x12/0x40
[67824.686837]  [<ffffffffc02b3a81>] txg_sync_thread+0x3b1/0x600 [zfs]
[67824.693198]  [<ffffffffc02b36d0>] ? txg_quiesce_thread+0x380/0x380 [zfs]
[67824.699942]  [<ffffffffc019ac60>] ? __thread_exit+0x20/0x20 [spl]
[67824.706092]  [<ffffffffc019acd1>] thread_generic_wrapper+0x71/0x80 [spl]
[67824.712843]  [<ffffffff8109de86>] kthread+0xd6/0xf0
[67824.717749]  [<ffffffff8109ddb0>] ? kthread_park+0x60/0x60
[67824.723293]  [<ffffffff8181091f>] ret_from_fork+0x3f/0x70
[67824.728721]  [<ffffffff8109ddb0>] ? kthread_park+0x60/0x60
[67824.734358] Kernel Offset: disabled
[67825.600245] ---[ end Kernel panic - not syncing: corrupted stack end detected inside scheduler
[67825.600245]
[67825.610479] ------------[ cut here ]------------
[67825.615179] WARNING: CPU: 9 PID: 31471 at /build/linux-lts-xenial-HGqnV_/linux-lts-xenial-4.4.0/arch/x86/kernel/smp.c:125 native_smp_send_reschedule+0x5d/0x60()
[67825.629631] Modules linked in: drbg ansi_cprng xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_nat_ipv4 nf_nat bridge ip6table_filter ip6_tables xt_multiport xt_set ip_set_hash_ip ip_set nfnetlink ipmi_devintf 8021q garp mrp stp llc ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi xt_comment ipt_REJECT nf_reject_ipv4 xt_tcpudp nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack bonding iptable_filter ip_tables ebtable_filter ebtables x_tables dm_crypt intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd ipmi_ssif sb_edac edac_core input_leds joydev lpc_ich mei_me mei ioatdma shpchp ipmi_si 8250_fintek ipmi_msghandler nfsd mac_hid auth_rpcgss nfs_acl binfmt_misc nfs lockd grace sunrpc fscache zfs(POE) zunicode(POE) zcommon(POE) znvpair(POE) spl(OE) zavl(POE) raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear ses enclosure hid_generic igb dca mpt3sas ahci ptp usbhid raid_class pps_core libahci hid scsi_transport_sas i2c_algo_bit wmi fjes
[67825.750015] CPU: 9 PID: 31471 Comm: txg_sync Tainted: P           OE   4.4.0-111-generic #134~14.04.1-Ubuntu
[67825.759939] Hardware name: Supermicro X9DRD-7LN4F(-JBOD)/X9DRD-EF/X9DRD-7LN4F, BIOS 3.0a 12/05/2013
[67825.769081]  0000000000000000 ffff88203f2c3c68 ffffffff813e07ac 0000000000000000
[67825.776798]  ffffffff81cae878 ffff88203f2c3ca0 ffffffff8107f606 0000000000000003
[67825.784529]  ffff88103fad7300 0000000000000009 0000000000000009 00000000000103a8
[67825.792258] Call Trace:
[67825.797860]  <IRQ>  [<ffffffff813e07ac>] dump_stack+0x63/0x87
[67825.803754]  [<ffffffff8107f606>] warn_slowpath_common+0x86/0xc0
[67825.809832]  [<ffffffff8107f6fa>] warn_slowpath_null+0x1a/0x20
[67825.815732]  [<ffffffff8104eded>] native_smp_send_reschedule+0x5d/0x60
[67825.822346]  [<ffffffff810bb473>] trigger_load_balance+0x143/0x1f0
[67825.828611]  [<ffffffff810ab0e6>] scheduler_tick+0xa6/0xd0
[67825.834191]  [<ffffffff810fa260>] ? tick_sched_do_timer+0x30/0x30
[67825.840376]  [<ffffffff810eac11>] update_process_times+0x51/0x60
[67825.846454]  [<ffffffff810f9c65>] tick_sched_handle.isra.15+0x25/0x60
[67825.852973]  [<ffffffff810fa29d>] tick_sched_timer+0x3d/0x70
[67825.858723]  [<ffffffff810eb753>] __hrtimer_run_queues+0xf3/0x260
[67825.864888]  [<ffffffff810ebbf8>] hrtimer_interrupt+0xa8/0x1a0
[67825.870812]  [<ffffffff810517c5>] local_apic_timer_interrupt+0x35/0x60
[67825.877426]  [<ffffffff8181591d>] smp_apic_timer_interrupt+0x3d/0x50
[67825.883849]  [<ffffffff81811816>] apic_timer_interrupt+0x1a6/0x1b0
[67825.890126]  [<ffffffff81083d1e>] ? __do_softirq+0x7e/0x290
[67825.895789]  [<ffffffff8116a92c>] ? irq_work_run+0x2c/0x40
[67825.901351]  [<ffffffff81084155>] irq_exit+0x95/0xa0
[67825.906392]  [<ffffffff8104f2a5>] smp_call_function_single_interrupt+0x35/0x40
[67825.913696]  [<ffffffff81812c56>] call_function_single_interrupt+0x1a6/0x1b0
[67825.920810]  <EOI>  [<ffffffff81184bef>] ? panic+0x1cb/0x20f
[67825.926609]  [<ffffffff81184beb>] ? panic+0x1c7/0x20f
[67825.931737]  [<ffffffff8180ca73>] __schedule+0x743/0x7e0
[67825.937117]  [<ffffffff8180cb45>] schedule+0x35/0x80
[67825.942158]  [<ffffffff8180f507>] schedule_timeout+0x237/0x2d0
[67825.948130]  [<ffffffffc02bdc6b>] ? vdev_mirror_io_start+0xab/0x180 [zfs]
[67825.955042]  [<ffffffffc02bd3e0>] ? vdev_config_sync+0x140/0x140 [zfs]
[67825.961643]  [<ffffffff810f11fb>] ? ktime_get+0x3b/0xb0
[67825.966938]  [<ffffffff8180c2c6>] io_schedule_timeout+0xa6/0x110
[67825.973037]  [<ffffffffc019f754>] cv_wait_common+0xa4/0x110 [spl]
[67825.979202]  [<ffffffff810c05e0>] ? prepare_to_wait_event+0xf0/0xf0
[67825.985541]  [<ffffffffc019f818>] __cv_wait_io+0x18/0x20 [spl]
[67825.991507]  [<ffffffffc02f9373>] zio_wait+0xb3/0x140 [zfs]
[67825.997181]  [<ffffffffc025d020>] dbuf_read+0x2e0/0x870 [zfs]
[67826.003031]  [<ffffffffc025db41>] __dbuf_hold_impl+0x451/0x4e0 [zfs]
[67826.009486]  [<ffffffffc025d872>] __dbuf_hold_impl+0x182/0x4e0 [zfs]
[67826.015941]  [<ffffffffc025dc43>] dbuf_hold_impl+0x73/0xa0 [zfs]
[67826.022051]  [<ffffffffc025df20>] dbuf_hold+0x20/0x30 [zfs]
[67826.027736]  [<ffffffffc0275f61>] dnode_hold_impl+0x91/0x500 [zfs]
[67826.033993]  [<ffffffff8180e6d2>] ? mutex_lock+0x12/0x2f
[67826.039412]  [<ffffffffc02765f3>] ? dnode_setdirty+0x93/0x170 [zfs]
[67826.045782]  [<ffffffffc02763e9>] dnode_hold+0x19/0x20 [zfs]
[67826.051545]  [<ffffffffc0266e01>] dmu_object_info+0x21/0x50 [zfs]
[67826.057742]  [<ffffffffc02764f8>] ? dnode_rele_and_unlock+0x48/0x80 [zfs]
[67826.064629]  [<ffffffffc0259089>] bpobj_open+0x39/0x170 [zfs]
[67826.070477]  [<ffffffffc0276559>] ? dnode_rele+0x29/0x30 [zfs]
[67826.076412]  [<ffffffffc025a01e>] bpobj_iterate_impl+0x51e/0x7b0 [zfs]
[67826.083054]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.090210]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.096841]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.103052]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.110205]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.116834]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.123032]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.130186]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.136818]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.143016]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.150163]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.156791]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.162991]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.170138]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.176766]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.182965]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.190115]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.196740]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.202940]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.210090]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.216715]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.222913]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.230063]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.236691]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.242891]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.250040]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.256666]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.262865]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.270015]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.276640]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.282839]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.289987]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.296618]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.302814]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.309963]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.316591]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.322789]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.329939]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.336566]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.342765]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.349914]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.356542]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.362740]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.369889]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.376517]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.382715]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.389864]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.396491]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.402689]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.409838]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.416465]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.422664]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.429816]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.436442]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.442641]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.449789]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.456416]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.462624]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.469773]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.476401]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.482599]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.489749]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.496376]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.502574]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.509723]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.516351]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.522549]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.529698]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.536326]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.542524]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.549675]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.556303]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.562498]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.569650]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.576278]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.582473]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.589624]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.596252]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.602450]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.609598]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.616225]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.622423]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.629575]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.636203]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.642398]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.649551]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.656178]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.662374]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.669526]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.676151]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.682349]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.689500]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.696128]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.702324]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.709474]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.716101]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.722299]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.729451]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.736078]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.742274]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.749425]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.756053]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.762250]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.769402]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.776026]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.782224]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.789375]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.796003]  [<ffffffffc025cc8f>] ? dbuf_create+0x3af/0x430 [zfs]
[67826.802201]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.809349]  [<ffffffffc0259edb>] bpobj_iterate_impl+0x3db/0x7b0 [zfs]
[67826.815979]  [<ffffffffc028de40>] ? dsl_scan_prefetch.isra.5+0xb0/0xb0 [zfs]
[67826.823138]  [<ffffffffc025a2c4>] bpobj_iterate+0x14/0x20 [zfs]
[67826.829160]  [<ffffffffc02908b4>] dsl_scan_sync+0x584/0xbf0 [zfs]
[67826.835327]  [<ffffffffc019a0c6>] ? spl_kmem_cache_free+0x166/0x1c0 [spl]
[67826.842243]  [<ffffffffc02f5d91>] ? zio_destroy+0xc1/0xd0 [zfs]
[67826.848284]  [<ffffffffc02a10d5>] spa_sync+0x3b5/0xad0 [zfs]
[67826.854015]  [<ffffffff810c05f2>] ? autoremove_wake_function+0x12/0x40
[67826.860663]  [<ffffffffc02b3a81>] txg_sync_thread+0x3b1/0x600 [zfs]
[67826.867044]  [<ffffffffc02b36d0>] ? txg_quiesce_thread+0x380/0x380 [zfs]
[67826.873822]  [<ffffffffc019ac60>] ? __thread_exit+0x20/0x20 [spl]
[67826.879990]  [<ffffffffc019acd1>] thread_generic_wrapper+0x71/0x80 [spl]
[67826.886756]  [<ffffffff8109de86>] kthread+0xd6/0xf0
[67826.891700]  [<ffffffff8109ddb0>] ? kthread_park+0x60/0x60
[67826.897258]  [<ffffffff8181091f>] ret_from_fork+0x3f/0x70
[67826.902725]  [<ffffffff8109ddb0>] ? kthread_park+0x60/0x60
[67826.908287] ---[ end trace b7c25d164ec03795 ]---

**Comment by behlendorf** [comment]
Can you try dynamically allocating the `dmu_object_info_t` and `bpobj` instead.  It looks like that will save 160 bytes per frame, and your stack was 38 levels deep for a whopping total savings of 6080 bytes.

```
$ pahole -C bpobj module/zfs/zfs.o
die__process_function: tag not supported (INVALID)!
struct bpobj {
	kmutex_t                   bpo_lock;             /*     0    48 */
	objset_t *                 bpo_os;               /*    48     8 */
	uint64_t                   bpo_object;           /*    56     8 */
	/* --- cacheline 1 boundary (64 bytes) --- */
	int                        bpo_epb;              /*    64     4 */
	uint8_t                    bpo_havecomp;         /*    68     1 */
	uint8_t                    bpo_havesubobj;       /*    69     1 */

	/* XXX 2 bytes hole, try to pack */

	bpobj_phys_t *             bpo_phys;             /*    72     8 */
	dmu_buf_t *                bpo_dbuf;             /*    80     8 */
	dmu_buf_t *                bpo_cached_dbuf;      /*    88     8 */

	/* size: 96, cachelines: 2, members: 9 */
	/* sum members: 94, holes: 1, sum holes: 2 */
	/* last cacheline: 32 bytes */
};

$ pahole -C dmu_object_info module/zfs/zfs.o
die__process_function: tag not supported (INVALID)!
struct dmu_object_info {
	uint32_t                   doi_data_block_size;  /*     0     4 */
	uint32_t                   doi_metadata_block_size; /*     4     4 */
	dmu_object_type_t          doi_type;             /*     8     4 */
	dmu_object_type_t          doi_bonus_type;       /*    12     4 */
	uint64_t                   doi_bonus_size;       /*    16     8 */
	uint8_t                    doi_indirection;      /*    24     1 */
	uint8_t                    doi_checksum;         /*    25     1 */
	uint8_t                    doi_compress;         /*    26     1 */
	uint8_t                    doi_nblkptr;          /*    27     1 */
	uint8_t                    doi_pad[4];           /*    28     4 */
	uint64_t                   doi_dnodesize;        /*    32     8 */
	uint64_t                   doi_physical_blocks_512; /*    40     8 */
	uint64_t                   doi_max_offset;       /*    48     8 */
	uint64_t                   doi_fill_count;       /*    56     8 */
	/* --- cacheline 1 boundary (64 bytes) --- */

	/* size: 64, cachelines: 1, members: 14 */
};
```

**Comment by ahrens** [comment]
@behlendorf The amount of recursion here is theoretically unbounded, so I think the solution needs to be removing the recursion, rather than reducing the stack used per recursive call.

**Comment by PaulZ-98** [comment]
Thanks @ahrens  - Ok so I can create a situation with nested bpobjs.
```
dd if=/dev/urandom of=/tank/fs3/foo1 bs=1k count=4096
zfs snapshot tank/fs3@snap2
dd if=/dev/urandom of=/tank/fs3/foo1 bs=1k count=4096
zfs snapshot tank/fs3@snap2a
dd / snap2b ..
dd / snap2i
dd
snap3
dd
snap4
dd
snap5
zfs destroy tank/fs3@snap4 &
zfs destroy tank/fs3@snap3 &
zfs destroy tank/fs3@snap2i &
zfs destroy tank/fs3@snap2h &
zfs destroy tank/fs3@snap2g &
zfs destroy tank/fs3@snap2f &
zfs destroy tank/fs3@snap2e &
zfs destroy tank/fs3@snap2d &
zfs destroy tank/fs3@snap2c &
zfs destroy tank/fs3@snap2b &
zfs destroy tank/fs3@snap2a &
zfs destroy tank/fs3@snap2 &
zdb tank
less /proc/spl/kstat/zfs/dbgmsg


1531330703   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 1 num_blkptrs 0 num_subobjs 11
1531330703   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 2 num_blkptrs 4108 num_subobjs 0
1531330703   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 3 num_blkptrs 4108 num_subobjs 0
1531330703   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 4 num_blkptrs 4108 num_subobjs 0
1531330703   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 5 num_blkptrs 4108 num_subobjs 0
1531330703   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 6 num_blkptrs 4108 num_subobjs 0
1531330704   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 7 num_blkptrs 4108 num_subobjs 0
1531330704   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 8 num_blkptrs 4108 num_subobjs 0
1531330704   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 9 num_blkptrs 4111 num_subobjs 0
1531330704   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 10 num_blkptrs 4108 num_subobjs 0
1531330704   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 11 num_blkptrs 4108 num_subobjs 0
1531330704   bpobj.c:225:bpobj_iterate_impl(): bpobj levels of recursion 12 num_blkptrs 4108 num_subobjs 0

In this case only one of the snaps has num_subobjs > 0.  My question now is can I get it so one of the "nested" bpobj to have subobjs off of it (num_subobjs > 0)?  Or is that not possible?  It might simplify the code if that's a "can't happen".

**Comment by ahrens** [comment]
So you did some things to move one bpobj into another (B -> A).  Now you need to do the same thing to move the bpobj (with subobj) into another bpobj, then you will have C -> B -> A.

**Comment by PaulZ-98** [comment]
Just pushed first try at a non-recursive version of bpobj_iterate_impl.  Feedback is welcome.

**Comment by ahrens** [comment]
Nice.  Were you able to reproduce the issue as well?  I'm on vacation until the 27th, I'll take a look then.

File: module/zfs/bpobj.c [hunk 1]
```diff
@@ -206,155 +206,216 @@ bpobj_is_empty(bpobj_t *bpo)
...
+				ASSERT0(bpo->bpo_phys->bpo_bytes);
+				ASSERT0(bpo->bpo_phys->bpo_comp);
+				ASSERT0(bpo->bpo_phys->bpo_uncomp);
+			}
+			mutex_exit(&bpo->bpo_lock);
+			if (bpi->bpi_parent != NULL) {
+				bpobj_close(bpo);
+				kmem_free(bpi->bpi_bpo, sizeof (bpobj_t));
+			}
+			continue;
```
[the remark this answers is not in the document]
Comment (behlendorf) [reply module/zfs/bpobj.c]: The kernel's leak checker agrees.

http://build.zfsonlinux.org/builders/Ubuntu%2017.04%20x86_64%20Coverage%20%28TEST%29/builds/3231/steps/shell_9/logs/kmemleak

[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Thanks @sdimitro and @behlendorf I'll correct that.

File: module/zfs/bpobj.c [hunk 2]
```diff
@@ -206,155 +206,216 @@ bpobj_is_empty(bpobj_t *bpo)
...
+
 static int
-bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
-    boolean_t free)
+bpobj_iterate_impl(bpobj_t *initial_bpo, bpobj_itor_t func, void *arg,
+    dmu_tx_t *tx, boolean_t free)
 {
 	dmu_object_info_t doi;
-	int epb;
+	list_t stack;
```
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: I'll take a look at this scoping.  Is declaring inside the for loops a problem or does the compiler optimize stack usage in that case?

[the remark this answers is not in the document]
Comment (sdimitro) [reply module/zfs/bpobj.c]: As of C99 you are allowed to declare variables in the middle of blocks, or inside initialization statements of for loops to reduce their scope.

From what I remember, reducing the scope of variables in general in terms of optimizations would help with things like register allocation for the compiler. That said, I doubt this is a thing anymore.

IMHO the advantage is readability. For example, some of the variables that you declare on the top of the function like `i`, and `bpi_cleanup` seemed to be used only for their respective loops. Their declarations could be moved into the initialization statement of their for loops
(kinda like you did with `for (bpobj_info_t *bpi = ...`).

`bpi_add` is used in a single place later for a specific case inside a for loop. You could inline it right there, or even completely get rid of it.
E.g. `list_insert_head(&stack, bpi_alloc(sublist, bpo, objarray[blkoff], i));`

`epb` and `doi` are used a lot later in the function and only if we have subobjects. Why not move their declarations later where they are actually used?
...etc.

I'm fine with the code as it is by the way, and many of these things can be subjective. But if we have the luxury to get rid of extra lines that perform no action nor have any meaning until used, I don't see why not going for it.

**Comment by PaulZ-98** [comment]
Hi @ahrens I used this script to test the changes.  All the subobjs were nested under dp_free_bpobj.  I never figured out how to get one of those subobjs to have its own subobjs.

```
#!/bin/bash
set -x
make -j10 && make install
zpool destroy -f tank
modprobe -r zfs
modprobe zfs
echo 1 > /sys/module/zfs/parameters/zfs_dbgmsg_enable
#echo 4294967262 > /sys/module/zfs/parameters/zfs_flags
echo 0 > /proc/spl/kstat/zfs/dbgmsg
zpool create -f tank /root/file1
zfs create tank/clones
zfs set recordsize=1k tank/clones
for i in {1..4}
do
    zfs create tank/fs$i
    zfs set recordsize=1k tank/fs$i
    for j in {1..12}
    do
	dd if=/dev/urandom of=/tank/fs$i/foo1 bs=1k count=4096
	zfs snapshot tank/fs$i@snap$j
    done
done
#
for i in {1..4}
do
    for j in {2..10}
    do
	zfs destroy tank/fs$i@snap$j &
    done
done
zdb tank
#less /proc/spl/kstat/zfs/dbgmsg
dmesg

**Comment by PaulZ-98** [comment]
Hi @sdimitro I pushed a version that improves the variable declarations.

File: module/zfs/bpobj.c [hunk 3]
```diff
@@ -206,155 +206,213 @@ bpobj_is_empty(bpobj_t *bpo)
...
+				err = dmu_object_free(p->bpo_os,
+				    bpi->bpi_object, tx);
+				if (err)
+					break;
+				p->bpo_phys->bpo_num_subobjs--;
+				ASSERT3S(p->bpo_phys->bpo_num_subobjs, >=, 0);
+				VERIFY3U(0, ==, dmu_free_range(p->bpo_os,
+				    p->bpo_phys->bpo_subobjs,
+				    bpi->bpi_index * sizeof (uint64_t),
+				    DMU_OBJECT_END, tx));
```
Comment (ahrens) [inline module/zfs/bpobj.c]: Are we sure that, given the order we are processing these in, that this is only chopping off a single entry?  Could we somehow verify that?  e.g. by checking that `bpi_index == bpo_num_subobjs-1`

File: module/zfs/bpobj.c [hunk 4]
```diff
@@ -206,155 +206,213 @@ bpobj_is_empty(bpobj_t *bpo)
...
-	}
-	if (dbuf) {
-		dmu_buf_rele(dbuf, FTAG);
-		dbuf = NULL;
-	}
-	if (free) {
-		VERIFY3U(0, ==, dmu_free_range(bpo->bpo_os,
-		    bpo->bpo_phys->bpo_subobjs,
-		    (i + 1) * sizeof (uint64_t), DMU_OBJECT_END, tx));
+		mutex_exit(&bpo->bpo_lock);
```
Comment (ahrens) [inline module/zfs/bpobj.c]: in this case, when do we call `bpobj_close(bpo)`?  It looks like we're leaving it open, and it's pointed to by the childrens' `bpi_parent`, but I don't see where we close it.

File: module/zfs/bpobj.c [hunk 5]
```diff
@@ -206,155 +206,213 @@ bpobj_is_empty(bpobj_t *bpo)
...
+	bpi->bpi_object = obj;
+	bpi->bpi_index = index;
+	return (bpi);
+}
+
 static int
-bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
-    boolean_t free)
+bpobj_iterate_impl(bpobj_t *initial_bpo, bpobj_itor_t func, void *arg,
+    dmu_tx_t *tx, boolean_t free)
```
Comment (ahrens) [inline module/zfs/bpobj.c]: This function was a bit long to begin with and now it's become pretty unwieldy.  Let's break it up into two or more functions.  Perhaps a sub-function can deal with the actual freeing of bp's (around lines 252-300).

File: module/zfs/bpobj.c [hunk 6]
```diff
@@ -206,155 +206,213 @@ bpobj_is_empty(bpobj_t *bpo)
...
 
-	for (i = bpo->bpo_phys->bpo_num_subobjs - 1; i >= 0; i--) {
-		uint64_t *objarray;
-		uint64_t offset, blkoff;
-		bpobj_t sublist;
-		uint64_t used_before, comp_before, uncomp_before;
-		uint64_t used_after, comp_after, uncomp_after;
+		if (!bpo->bpo_havesubobj || bpo->bpo_phys->bpo_subobjs == 0) {
+			/* propogate reduction in space used and clean up */
+			if (free && (bpi->bpi_parent != NULL)) {
```
Comment (ahrens) [inline module/zfs/bpobj.c]: Do we need to propagate this to our older ancestors (grand-parent, great-grand-parent, etc)?

**Comment by PaulZ-98** [comment]
Thank you for the comments.  I'm just back from vacation and will be working on this later in the week.

File: module/zfs/bpobj.c (hunk 3 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: I have added an ASSERT for this.
```
                if (!bpo->bpo_havesubobj || bpo->bpo_phys->bpo_subobjs == 0) {
                        /* propogate reduction in space used and clean up */
                        if (free && (bpi->bpi_parent != NULL)) {
                                bpobj_t *p = bpi->bpi_parent;
                                err = dmu_object_free(p->bpo_os,
                                    bpi->bpi_object, tx);
                                if (err)
                                        break;
                                ASSERT3S(bpi->bpi_index, ==, p->bpo_phys->bpo_num_subobjs - 1);
                                cmn_err(CE_NOTE, "clearing range at bpi_index %llu num_subojbs %llu",
                                    (u_longlong_t)bpi->bpi_index, (u_longlong_t)p->bpo_phys->bpo_num_subobjs);
                                p->bpo_phys->bpo_num_subobjs--;
                                ASSERT3S(p->bpo_phys->bpo_num_subobjs, >=, 0);
                                VERIFY3U(0, ==, dmu_free_range(p->bpo_os,
                                    p->bpo_phys->bpo_subobjs,
                                    bpi->bpi_index * sizeof (uint64_t),
                                    DMU_OBJECT_END, tx));
                                p->bpo_phys->bpo_bytes -= freed;
                                ASSERT3S(p->bpo_phys->bpo_bytes, >=, 0);
                                p->bpo_phys->bpo_comp -= comp_freed;
                                p->bpo_phys->bpo_uncomp -= uncomp_freed;
                        }
```
And here is the debug output:
```
[ 1713.047827] NOTICE: clearing range at bpi_index 0 num_subojbs 1
[ 1713.210079] NOTICE: clearing range at bpi_index 34 num_subojbs 35
[ 1713.248953] NOTICE: clearing range at bpi_index 33 num_subojbs 34
[ 1713.282443] NOTICE: clearing range at bpi_index 32 num_subojbs 33
[ 1713.315946] NOTICE: clearing range at bpi_index 31 num_subojbs 32
[ 1713.349813] NOTICE: clearing range at bpi_index 30 num_subojbs 31
[ 1713.383331] NOTICE: clearing range at bpi_index 29 num_subojbs 30
[ 1713.418360] NOTICE: clearing range at bpi_index 28 num_subojbs 29
[ 1713.442221] NOTICE: clearing range at bpi_index 27 num_subojbs 28
[ 1713.479142] NOTICE: clearing range at bpi_index 26 num_subojbs 27
[ 1713.511587] NOTICE: clearing range at bpi_index 25 num_subojbs 26
[ 1713.543077] NOTICE: clearing range at bpi_index 24 num_subojbs 25
[ 1713.614529] NOTICE: clearing range at bpi_index 23 num_subojbs 24
[ 1713.685240] NOTICE: clearing range at bpi_index 22 num_subojbs 23
[ 1713.743492] NOTICE: clearing range at bpi_index 21 num_subojbs 22
[ 1713.802604] NOTICE: clearing range at bpi_index 20 num_subojbs 21
[ 1713.869107] NOTICE: clearing range at bpi_index 19 num_subojbs 20
[ 1713.918777] NOTICE: clearing range at bpi_index 18 num_subojbs 19
[ 1713.973525] NOTICE: clearing range at bpi_index 17 num_subojbs 18
[ 1714.038343] NOTICE: clearing range at bpi_index 16 num_subojbs 17
[ 1714.155260] NOTICE: clearing range at bpi_index 15 num_subojbs 16
[ 1714.591379] NOTICE: clearing range at bpi_index 14 num_subojbs 15
[ 1714.622209] NOTICE: clearing range at bpi_index 13 num_subojbs 14
[ 1714.655231] NOTICE: clearing range at bpi_index 12 num_subojbs 13
[ 1714.688806] NOTICE: clearing range at bpi_index 11 num_subojbs 12
[ 1714.716590] NOTICE: clearing range at bpi_index 10 num_subojbs 11
[ 1714.752010] NOTICE: clearing range at bpi_index 9 num_subojbs 10
[ 1714.790763] NOTICE: clearing range at bpi_index 8 num_subojbs 9
[ 1714.826907] NOTICE: clearing range at bpi_index 7 num_subojbs 8
[ 1714.863624] NOTICE: clearing range at bpi_index 6 num_subojbs 7
[ 1714.903465] NOTICE: clearing range at bpi_index 5 num_subojbs 6
[ 1714.937283] NOTICE: clearing range at bpi_index 4 num_subojbs 5
[ 1714.969658] NOTICE: clearing range at bpi_index 3 num_subojbs 4
[ 1715.004930] NOTICE: clearing range at bpi_index 2 num_subojbs 3
[ 1715.035054] NOTICE: clearing range at bpi_index 1 num_subojbs 2
[ 1715.069743] NOTICE: clearing range at bpi_index 0 num_subojbs 1
```

File: module/zfs/bpobj.c (hunk 4 above)
Comment (ahrens) [reply module/zfs/bpobj.c]: Right, but what about the intermediate bpobj's?  I.e. dp_free_bpobj points to a bpobj which points to a bpobj which points to this one.

File: module/zfs/bpobj.c (hunk 6 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Here's some debug output.  bpobj ffff8ef8f98170d0 is the parent of all 34 subobjs.  I'd like to prove that the flattened list would always propagate the accounting even if the test generated multiple levels.  Experimented with clones but that didn't help, all subobjs were still children of dp_free_bpobj.
```
[  425.942985] NOTICE: bpi bpo ffff8ef8f98170d0 parent           (null) index 0 bytes 158490624 (before)
[  425.943103] NOTICE: bpi bpo ffff8ef8fa18d420 parent ffff8ef8f98170d0 index 34 bytes 4528128 (before)
[  425.977424] NOTICE: bpi bpo ffff8ef8fa18d420 parent ffff8ef8f98170d0 index 34 bytes 0 parent bytes 153962496 (after)
[  425.977428] NOTICE: bpi bpo ffff8ef8fa18d840 parent ffff8ef8f98170d0 index 33 bytes 4528128 (before)
[  426.010388] NOTICE: bpi bpo ffff8ef8fa18d840 parent ffff8ef8f98170d0 index 33 bytes 0 parent bytes 149434368 (after)
[  426.010391] NOTICE: bpi bpo ffff8ef8fa18dba0 parent ffff8ef8f98170d0 index 32 bytes 4528128 (before)
[  426.042430] NOTICE: bpi bpo ffff8ef8fa18dba0 parent ffff8ef8f98170d0 index 32 bytes 0 parent bytes 144906240 (after)
[  426.042434] NOTICE: bpi bpo ffff8ef8d2c04ba0 parent ffff8ef8f98170d0 index 31 bytes 4528128 (before)
[  426.076430] NOTICE: bpi bpo ffff8ef8d2c04ba0 parent ffff8ef8f98170d0 index 31 bytes 0 parent bytes 140378112 (after)
[  426.076433] NOTICE: bpi bpo ffff8ef8d2c04e40 parent ffff8ef8f98170d0 index 30 bytes 4528128 (before)
[  426.110688] NOTICE: bpi bpo ffff8ef8d2c04e40 parent ffff8ef8f98170d0 index 30 bytes 0 parent bytes 135849984 (after)
[  426.110690] NOTICE: bpi bpo ffff8ef8d2c04660 parent ffff8ef8f98170d0 index 29 bytes 4528128 (before)
[  426.139851] NOTICE: bpi bpo ffff8ef8d2c04660 parent ffff8ef8f98170d0 index 29 bytes 0 parent bytes 131321856 (after)
[  426.139855] NOTICE: bpi bpo ffff8ef8d2c041e0 parent ffff8ef8f98170d0 index 28 bytes 4528128 (before)
[  426.181628] NOTICE: bpi bpo ffff8ef8d2c041e0 parent ffff8ef8f98170d0 index 28 bytes 0 parent bytes 126793728 (after)
[  426.181631] NOTICE: bpi bpo ffff8ef8d2c04000 parent ffff8ef8f98170d0 index 27 bytes 4528128 (before)
[  426.214137] NOTICE: bpi bpo ffff8ef8d2c04000 parent ffff8ef8f98170d0 index 27 bytes 0 parent bytes 122265600 (after)
[  426.214140] NOTICE: bpi bpo ffff8ef8d2c04780 parent ffff8ef8f98170d0 index 26 bytes 4528128 (before)
[  426.247009] NOTICE: bpi bpo ffff8ef8d2c04780 parent ffff8ef8f98170d0 index 26 bytes 0 parent bytes 117737472 (after)
[  426.247012] NOTICE: bpi bpo ffff8ef8d2c04900 parent ffff8ef8f98170d0 index 25 bytes 4528128 (before)
[  426.293723] NOTICE: bpi bpo ffff8ef8d2c04900 parent ffff8ef8f98170d0 index 25 bytes 0 parent bytes 113209344 (after)
[  426.293726] NOTICE: bpi bpo ffff8ef8d2c04a80 parent ffff8ef8f98170d0 index 24 bytes 4528128 (before)
[  426.361108] NOTICE: bpi bpo ffff8ef8d2c04a80 parent ffff8ef8f98170d0 index 24 bytes 0 parent bytes 108681216 (after)
[  426.361111] NOTICE: bpi bpo ffff8ef8d2c04ea0 parent ffff8ef8f98170d0 index 23 bytes 4528128 (before)
[  426.426093] NOTICE: bpi bpo ffff8ef8d2c04ea0 parent ffff8ef8f98170d0 index 23 bytes 0 parent bytes 104153088 (after)
[  426.426096] NOTICE: bpi bpo ffff8ef8d2c04d20 parent ffff8ef8f98170d0 index 22 bytes 4528128 (before)
[  426.495193] NOTICE: bpi bpo ffff8ef8d2c04d20 parent ffff8ef8f98170d0 index 22 bytes 0 parent bytes 99624960 (after)
[  426.495196] NOTICE: bpi bpo ffff8ef8d2c04a20 parent ffff8ef8f98170d0 index 21 bytes 4528128 (before)
[  426.530717] NOTICE: bpi bpo ffff8ef8d2c04a20 parent ffff8ef8f98170d0 index 21 bytes 0 parent bytes 95096832 (after)
[  426.530720] NOTICE: bpi bpo ffff8ef8d2c04540 parent ffff8ef8f98170d0 index 20 bytes 4528128 (before)
[  426.593854] NOTICE: bpi bpo ffff8ef8d2c04540 parent ffff8ef8f98170d0 index 20 bytes 0 parent bytes 90568704 (after)
[  426.593857] NOTICE: bpi bpo ffff8ef8d2c04420 parent ffff8ef8f98170d0 index 19 bytes 4530176 (before)
[  426.648729] NOTICE: bpi bpo ffff8ef8d2c04420 parent ffff8ef8f98170d0 index 19 bytes 0 parent bytes 86038528 (after)
[  426.648732] NOTICE: bpi bpo ffff8ef8d2c04240 parent ffff8ef8f98170d0 index 18 bytes 4528128 (before)
[  426.691102] NOTICE: bpi bpo ffff8ef8d2c04240 parent ffff8ef8f98170d0 index 18 bytes 0 parent bytes 81510400 (after)
[  426.691105] NOTICE: bpi bpo ffff8ef8d2c04b40 parent ffff8ef8f98170d0 index 17 bytes 4528128 (before)
[  426.749585] NOTICE: bpi bpo ffff8ef8d2c04b40 parent ffff8ef8f98170d0 index 17 bytes 0 parent bytes 76982272 (after)
[  426.749589] NOTICE: bpi bpo ffff8ef8d2c04c60 parent ffff8ef8f98170d0 index 16 bytes 4528128 (before)
[  426.791471] NOTICE: bpi bpo ffff8ef8d2c04c60 parent ffff8ef8f98170d0 index 16 bytes 0 parent bytes 72454144 (after)
[  426.791474] NOTICE: bpi bpo ffff8ef8d2c040c0 parent ffff8ef8f98170d0 index 15 bytes 4528128 (before)
[  426.851609] NOTICE: bpi bpo ffff8ef8d2c040c0 parent ffff8ef8f98170d0 index 15 bytes 0 parent bytes 67926016 (after)
[  426.851613] NOTICE: bpi bpo ffff8ef8d2c04120 parent ffff8ef8f98170d0 index 14 bytes 4528128 (before)
[  426.901299] NOTICE: bpi bpo ffff8ef8d2c04120 parent ffff8ef8f98170d0 index 14 bytes 0 parent bytes 63397888 (after)
[  426.901304] NOTICE: bpi bpo ffff8ef8d2c04480 parent ffff8ef8f98170d0 index 13 bytes 4528128 (before)
[  426.934305] NOTICE: bpi bpo ffff8ef8d2c04480 parent ffff8ef8f98170d0 index 13 bytes 0 parent bytes 58869760 (after)
[  426.934308] NOTICE: bpi bpo ffff8ef8d2c044e0 parent ffff8ef8f98170d0 index 12 bytes 4528128 (before)
[  426.948021] NOTICE: error: 85
[  426.948032] NOTICE: returning with err 85 initial bpo bytes 56972288
[  426.948233] NOTICE: bpi bpo ffff8ef959c8e588 parent           (null) index 0 bytes 178176 (before)
[  426.948360] NOTICE: bpi bpo ffff8ef959c8e588 parent           (null) index 0 bytes 0 parent bytes 0 (after)
[  426.948361] NOTICE: returning with err 0 initial bpo bytes 0
[  427.514926] NOTICE: bpi bpo ffff8ef8f98170d0 parent           (null) index 0 bytes 56972288 (before)
[  427.514970] NOTICE: bpi bpo ffff8ef8e469ed80 parent ffff8ef8f98170d0 index 12 bytes 2630656 (before)
[  427.534730] NOTICE: bpi bpo ffff8ef8e469ed80 parent ffff8ef8f98170d0 index 12 bytes 0 parent bytes 54341632 (after)
[  427.534736] NOTICE: bpi bpo ffff8ef8e469e5a0 parent ffff8ef8f98170d0 index 11 bytes 4528128 (before)
[  427.577647] NOTICE: bpi bpo ffff8ef8e469e5a0 parent ffff8ef8f98170d0 index 11 bytes 0 parent bytes 49813504 (after)
[  427.577651] NOTICE: bpi bpo ffff8ef8e469e3c0 parent ffff8ef8f98170d0 index 10 bytes 4528128 (before)
[  427.613637] NOTICE: bpi bpo ffff8ef8e469e3c0 parent ffff8ef8f98170d0 index 10 bytes 0 parent bytes 45285376 (after)
[  427.613640] NOTICE: bpi bpo ffff8ef8e469eb40 parent ffff8ef8f98170d0 index 9 bytes 4530176 (before)
[  427.657938] NOTICE: bpi bpo ffff8ef8e469eb40 parent ffff8ef8f98170d0 index 9 bytes 0 parent bytes 40755200 (after)
[  427.657942] NOTICE: bpi bpo ffff8ef8e469e480 parent ffff8ef8f98170d0 index 8 bytes 4528128 (before)
[  427.700679] NOTICE: bpi bpo ffff8ef8e469e480 parent ffff8ef8f98170d0 index 8 bytes 0 parent bytes 36227072 (after)
[  427.700682] NOTICE: bpi bpo ffff8ef8e469e060 parent ffff8ef8f98170d0 index 7 bytes 4528128 (before)
[  427.738197] NOTICE: bpi bpo ffff8ef8e469e060 parent ffff8ef8f98170d0 index 7 bytes 0 parent bytes 31698944 (after)
[  427.738201] NOTICE: bpi bpo ffff8ef8e469e600 parent ffff8ef8f98170d0 index 6 bytes 4528128 (before)
[  427.779463] NOTICE: bpi bpo ffff8ef8e469e600 parent ffff8ef8f98170d0 index 6 bytes 0 parent bytes 27170816 (after)
[  427.779466] NOTICE: bpi bpo ffff8ef8e469e240 parent ffff8ef8f98170d0 index 5 bytes 4528128 (before)
[  427.821228] NOTICE: bpi bpo ffff8ef8e469e240 parent ffff8ef8f98170d0 index 5 bytes 0 parent bytes 22642688 (after)
[  427.821232] NOTICE: bpi bpo ffff8ef8e469e4e0 parent ffff8ef8f98170d0 index 4 bytes 4528128 (before)
[  427.858871] NOTICE: bpi bpo ffff8ef8e469e4e0 parent ffff8ef8f98170d0 index 4 bytes 0 parent bytes 18114560 (after)
[  427.858876] NOTICE: bpi bpo ffff8ef8e469e360 parent ffff8ef8f98170d0 index 3 bytes 4529152 (before)
[  427.897173] NOTICE: bpi bpo ffff8ef8e469e360 parent ffff8ef8f98170d0 index 3 bytes 0 parent bytes 13585408 (after)
[  427.897176] NOTICE: bpi bpo ffff8ef8e469e000 parent ffff8ef8f98170d0 index 2 bytes 4528128 (before)
[  427.943388] NOTICE: bpi bpo ffff8ef8e469e000 parent ffff8ef8f98170d0 index 2 bytes 0 parent bytes 9057280 (after)
[  427.943426] NOTICE: bpi bpo ffff8ef8e469ecc0 parent ffff8ef8f98170d0 index 1 bytes 4529152 (before)
[  427.981859] NOTICE: bpi bpo ffff8ef8e469ecc0 parent ffff8ef8f98170d0 index 1 bytes 0 parent bytes 4528128 (after)
[  427.981862] NOTICE: bpi bpo ffff8ef8e469eba0 parent ffff8ef8f98170d0 index 0 bytes 4528128 (before)
[  428.017620] NOTICE: bpi bpo ffff8ef8e469eba0 parent ffff8ef8f98170d0 index 0 bytes 0 parent bytes 0 (after)
[  428.017623] NOTICE: returning with err 0 initial bpo bytes 0
```

File: module/zfs/bpobj.c (hunk 4 above)
Comment (ahrens) [reply module/zfs/bpobj.c]: I think you're referring to the code that's now on line 373.  So bpi_parent always refers to the bpi_bpo of another bpi?  I wonder if that would be more clear if bpi_parent was a `bpobj_info_t *` rather than a `bpobj_t *`

**Comment by ahrens** [comment]
Let's be sure this fixes https://github.com/zfsonlinux/zfs/issues/7908 as well.

**Comment by ahrens** [comment]
The following script will create ~60 layers of nested bpobj's.  It should reproduce the issue.  I tested this on illumos and it creates the nested bpobj's, but this is not enough to overflow the stack (which is both bigger, and each stack frame is smaller).

```
#!/bin/bash

# note, compression and redundant_metadata settings just reduce space used, not necessary to reproduce the problem
zfs create -o compress=zle -o redundant_metadata=most -o recordsize=512 test/fs

# note, each 16K snapshots results in one layer of recursive bpobj subobj's
n=1000000

echo creating file
/usr/bin/dd if=/dev/urandom of=/test/fs/file conv=notrunc bs=512 count=$n >&/dev/null
zfs snapshot test/fs@first


for (( i=0; i<n; i=i+1 )); do
	echo $i
	/usr/bin/dd if=/dev/zero of=/test/fs/file conv=notrunc bs=512 oseek=$i count=1 >&/dev/null
	zfs snapshot test/fs@$i
	zfs destroy test/fs@$((i-1))
done
```

**Comment by ahrens** [comment]
As far as I can tell, you need 16*1024 snapshots to create each layer of indirection.  So to produce the 38-layer recursion that you saw, you'd need about 650,000 snapshots of one filesystem/zvol.  That's about 1 snapshot per minute for 1.25 years.  (Note that, as in the above script, not all snapshots need to exist simultaneously.)

File: module/zfs/bpobj.c [hunk 7]
```diff
@@ -264,97 +306,176 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+			goto out;
+		}
+		/* A subobj with no subobjs below it can be cleaned up. */
+		if (bpo->bpo_phys->bpo_num_subobjs == 0 ||
+		    !bpo->bpo_havesubobj ||
+		    bpo->bpo_phys->bpo_subobjs == 0) {
+			if (free && (bpi->bpi_parent != NULL)) {
+				bpobj_t *p = bpi->bpi_parent->bpi_bpo;
+				err = dmu_object_free(p->bpo_os,
+				    bpi->bpi_object, tx);
```
Comment (ahrens) [inline module/zfs/bpobj.c]: it doesn't seem right to be accessing bpo_phys after we've freed the object it references.  I think we should do this after "eliminate the empty subobj".  And maybe we can move `ASSERT0(bpo->bpo_phys->bpo_bytes/comp/uncomp);` before this `if (free...` block?

File: module/zfs/bpobj.c [hunk 8]
```diff
@@ -264,97 +306,176 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-			ASSERT3S(bpo->bpo_phys->bpo_num_subobjs, >=, 0);
+		if (free)
+			dmu_buf_will_dirty(sublist->bpo_dbuf, tx);
+
+		list_insert_head(&stack, bpi_alloc(sublist, bpi,
+		    objarray[blkoff], i));
+
+		if (dbuf) {
+			dmu_buf_rele(dbuf, FTAG);
+			dbuf = NULL;
```
Comment (ahrens) [inline module/zfs/bpobj.c]: Since you're doing this, dbuf is not actually cached between each iteration of the loop.  In that case you can simplify the code by eliminating `dbuf` (and calls to dmu_buf_hold/rele) and instead use dmu_read() to read the 8 bytes we need out of `bpo_subobjs`

File: module/zfs/bpobj.c [hunk 9]
```diff
@@ -242,19 +280,23 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+			freed = bp_get_dsize_sync(spa, bp);
 			ASSERT3S(bpo->bpo_phys->bpo_bytes, >=, 0);
 			if (bpo->bpo_havecomp) {
-				bpo->bpo_phys->bpo_comp -= BP_GET_PSIZE(bp);
-				bpo->bpo_phys->bpo_uncomp -= BP_GET_UCSIZE(bp);
+				comp_freed = BP_GET_PSIZE(bp);
+				uncomp_freed = BP_GET_UCSIZE(bp);
 			}
+			propagate_space_reduction(bpi, freed,
+			    comp_freed, uncomp_freed);
```
Comment (ahrens) [inline module/zfs/bpobj.c]: it seems really expensive to do this every time through the loop.  Could we do it once before returning?

File: module/zfs/bpobj.c [hunk 10]
```diff
@@ -242,19 +280,23 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
 		err = func(arg, bp, tx);
 		if (err)
 			break;
+
 		if (free) {
-			bpo->bpo_phys->bpo_bytes -=
-			    bp_get_dsize_sync(dmu_objset_spa(bpo->bpo_os), bp);
+			spa_t *spa = dmu_objset_spa(bpo->bpo_os);
+			comp_freed = uncomp_freed = 0;
+			freed = bp_get_dsize_sync(spa, bp);
```
Comment (ahrens) [inline module/zfs/bpobj.c]: freed, comp_freed, uncomp_freed should be declared here (but see below about calling propagate_space_reduction once, in which case we would want to use them to accumulate the sum for all the bp's we iterate over, in which case they would need to continue to be declared (and initialized!) in the outer scope).

**Comment by PaulZ-98** [comment]
Thanks for the comments.. I'm back from vacation, and will be working on the changes this week.

File: module/zfs/bpobj.c (hunk 8 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Nice.  This eliminates a bunch of code including the call to dmu_object_info since we no longer need to get the epb.

File: module/zfs/bpobj.c [hunk 11]
```diff
@@ -206,29 +206,67 @@ bpobj_is_empty(bpobj_t *bpo)
...
+static void
+propagate_space_reduction(bpobj_info_t *initial_bpi, uint64_t freed,
+    uint64_t comp_freed, uint64_t uncomp_freed)
+{
+	bpobj_info_t *bpi = initial_bpi;
+
+	while (bpi != NULL) {
+		bpobj_t *p = bpi->bpi_bpo;
+
+		p->bpo_phys->bpo_bytes -= freed;
```
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Like this..?
```
+boolean_t
+dmu_buf_is_dirty(dmu_buf_t *db_fake)
+{
+       dmu_buf_impl_t *db = (dmu_buf_impl_t *)db_fake;
+
+       return (db->db_dirtycnt > 0);
+}
+
```

[the remark this answers is not in the document]
Comment (ahrens) [reply module/zfs/bpobj.c]: That seems fine, but we could be more specific by passing the tx, and then doing something like what we do in the beginning of dmu_buf_will_dirty() to see if it's already dirty.  Something like:

```
	mutex_enter(&db->db_mtx);
	for (dbuf_dirty_record_t *dr = db->db_last_dirty;
	    dr != NULL && dr->dr_txg >= tx->tx_txg; dr = dr->dr_next) {
		if (dr->dr_txg == tx->tx_txg) {
			mutex_exit(&db->db_mtx);
			return (B_TRUE);
		}
	}
	mutex_exit(&db->db_mtx);
        return (B_FALSE);
```

[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Had some failures after trying this suggestion.
```
Presumably bpo_dbuf is already dirty, since you aren't dirtying it here. To make this code more obvious, I wonder if we should just eat the cost of calling dmu_buf_will_dirty() again here. Or we could add a dmu_buf_is_dirty() function and do ASSERT(dmu_buf_is_dirty(bpo_dbuf))?
```
```
loading concrete vdev 4, metaslab 12 of 15 ...
loading concrete vdev 4, metaslab 13 of 15 ...
loading concrete vdev 4, metaslab 14 of 15 ... dmu_buf_is_dirty(p->bpo_dbuf, tx) ASSERT at ../../module/zfs/bpobj.c:248:propagate_space_reduction()/var/lib/buildbot/slaves/zfs/Ubuntu_17_04_x86_64_Coverage__TEST_/build/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh[66]: log_must[67]: log_pos: line 253: 27193: Abort
```

So I'm going to have to explicitly call dbuf_will_dirty() and then we won't need the assert.

[the remark this answers is not in the document]
Comment (ahrens) [reply module/zfs/bpobj.c]: That output looks like it's coming from zdb, which shouldn't be dirtying anything (or expecting it to be dirty).  So you may need to look at why the bpobj code is thinking that it's going to be changing the on-disk state when running zdb.

[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: When I moved the call to propagate_space_reduction out of the blkptr loop I had neglected to put if (free) in front of it.  I'm going to fix that and try again asserting that bpo_dbuf is already dirty.

**Comment by PaulZ-98** [comment]
Pushed updated version which addresses the latest round of comments.

File: module/zfs/bpobj.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: It's good now with if (free) propagate...(), and asserting dmu_buf_is_dirty.

File: module/zfs/bpobj.c [hunk 12]
```diff
@@ -206,29 +206,64 @@ bpobj_is_empty(bpobj_t *bpo)
...
 	dmu_buf_t *dbuf = NULL;
-
-	ASSERT(bpobj_is_open(bpo));
-	mutex_enter(&bpo->bpo_lock);
-
-	if (free)
-		dmu_buf_will_dirty(bpo->bpo_dbuf, tx);
+	bpobj_t *bpo = bpi->bpi_bpo;
 
 	for (i = bpo->bpo_phys->bpo_num_blkptrs - 1; i >= 0; i--) {
```
Comment (ahrens) [inline module/zfs/bpobj.c]: since we are decrementing bpo_num_blkptrs as we go, I wonder if this should just be `while (bpo_num_blkptrs > 0)` (and then use `bpo_num_blkptrs - 1` rather than `i` to compute offset,blkoff)

File: module/zfs/bpobj.c [hunk 13]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+				comp_freed += BP_GET_PSIZE(bp);
+				uncomp_freed += BP_GET_UCSIZE(bp);
 			}
 			bpo->bpo_phys->bpo_num_blkptrs--;
 			ASSERT3S(bpo->bpo_phys->bpo_num_blkptrs, >=, 0);
 		}
 	}
+	if (free)
+		propagate_space_reduction(bpi, freed, comp_freed,
+		    uncomp_freed, tx);
```
Comment (ahrens) [inline module/zfs/bpobj.c]: I think it would be fine (and more readable) to combine the two `if (free)` blocks (here and line 306).

File: module/zfs/bpobj.c [hunk 14]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
 	if (dbuf) {
 		dmu_buf_rele(dbuf, FTAG);
 		dbuf = NULL;
 	}
 	if (free) {
-		VERIFY3U(0, ==, dmu_free_range(bpo->bpo_os, bpo->bpo_object,
-		    (i + 1) * sizeof (blkptr_t), DMU_OBJECT_END, tx));
+		VERIFY3U(0, ==, dmu_free_range(bpo->bpo_os,
```
Comment (ahrens) [inline module/zfs/bpobj.c]: you can update this to use `VERIFY0(dmu_free_range...`

File: module/zfs/bpobj.c [hunk 15]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+		    bpo->bpo_object, (i + 1) * sizeof (blkptr_t),
```
Comment (ahrens) [inline module/zfs/bpobj.c]: I think it would be easier to understand if we free from `bpo_num_blkptrs` rather than `i+1`.

File: module/zfs/bpobj.c [hunk 16]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-	if (err) {
-		mutex_exit(&bpo->bpo_lock);
-		return (err);
+static void
+bpobj_iterate_cleanup(list_t *stack, int err)
+{
+	bpobj_t *bpo;
+
+	for (bpobj_info_t *bpi_cleanup = list_head(stack); bpi_cleanup != NULL;
+	    bpi_cleanup = list_next(stack, bpi_cleanup)) {
```
Comment (ahrens) [inline module/zfs/bpobj.c]: It looks like this is using `bpi_cleanup` after it's been freed.  Is this code exercised by the test cases?  Or maybe kmem_free() doesn't poison the memory on ZoL (while testing)?

I think the usual way of doing this would be
```
while ((bpi = list_remove_head(stack)) != NULL) {
  ...
  kmem_free(bpi);
}

File: module/zfs/bpobj.c [hunk 17]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
 
-		if (dbuf == NULL || dbuf->db_offset > offset) {
-			if (dbuf)
-				dmu_buf_rele(dbuf, FTAG);
-			err = dmu_buf_hold(bpo->bpo_os,
-			    bpo->bpo_phys->bpo_subobjs, offset, FTAG, &dbuf, 0);
-			if (err)
-				break;
-		}
+#define	SUBOBJS(x) x->bpo_phys->bpo_num_subobjs
```
Comment (ahrens) [inline module/zfs/bpobj.c]: I don't think this macro increases readability.

[nit] there should be a blank line between functions

File: module/zfs/bpobj.c [hunk 18]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
 
-		ASSERT3U(offset, >=, dbuf->db_offset);
-		ASSERT3U(offset, <, dbuf->db_offset + dbuf->db_size);
+static int
+bpobj_iterate_impl(bpobj_t *initial_bpo, bpobj_itor_t func, void *arg,
+    dmu_tx_t *tx, boolean_t free)
+{
+	list_t stack;
+	bpobj_t *bpo = initial_bpo;
```
Comment (ahrens) [inline module/zfs/bpobj.c]: `bpo` can be declared inside the loop (line 343 can use `bpi_alloc(initial_bpo` directly)

File: module/zfs/bpobj.c [hunk 19]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+			dmu_buf_will_dirty(bpo->bpo_dbuf, tx);
+
+		err = bpobj_iterate_blkptrs(bpi, func, arg, tx, free);
+		if (err != 0) {
+			mutex_exit(&bpo->bpo_lock);
+			if (bpi->bpi_parent != NULL) {
+				bpobj_close(bpo);
+				kmem_free(bpi->bpi_bpo, sizeof (bpobj_t));
 			}
+			kmem_free(bpi, sizeof (bpobj_info_t));
```
Comment (ahrens) [inline module/zfs/bpobj.c]: It might be simpler to push bpi back on to the stack, and then let bpobj_iterate_cleanup() handle it, rather than duplicating its logic here.

File: module/zfs/bpobj.c [hunk 20]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+			continue;
 		}
+		ASSERT(bpo->bpo_havecomp);
+		/*
+		 * Can't clean up bpobj while it still has subobjs.  Place it
+		 * back in the list ahead of its children.  It will be cleaned
+		 * up once the children are all freed.
+		 */
+		if (bpo->bpo_phys->bpo_num_subobjs > 0)
```
Comment (ahrens) [inline module/zfs/bpobj.c]: I think num_subobj has to be nonzero here (otherwise we'd have cleaned up the bpo and `continue`d above).  We wouldn't want `i` to be `-1` below either.

File: module/zfs/bpobj.c [hunk 21]
```diff
@@ -242,119 +277,171 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-			    &used_before, &comp_before, &uncomp_before);
-			if (err != 0) {
-				bpobj_close(&sublist);
-				break;
+	list_create(&stack, sizeof (bpobj_info_t),
+	    offsetof(bpobj_info_t, bpi_node));
+	for (bpobj_info_t *bpi = bpi_alloc(bpo, NULL, 0, 0);
+	    bpi != NULL; bpi = list_remove_head(&stack)) {
+		bpo = bpi->bpi_bpo;
+		mutex_enter(&bpo->bpo_lock);
```
Comment (ahrens) [inline module/zfs/bpobj.c]: `bpo_lock` is not exited in some of the error paths below - the ones where we `break`.

File: module/zfs/bpobj.c (hunk 12 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Looked at doing this but bpo_num_blkptrs is only decremented "if (free)".

File: module/zfs/bpobj.c (hunk 15 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Since this is inside "if (free)" I can use bpo_num_blkptrs here.

File: module/zfs/bpobj.c (hunk 17 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: It was a way to fit line 390 in 80 characters.  ASSERT3U(SUBOBJS(bpo), ==, 0);

File: module/zfs/bpobj.c (hunk 12 above)
Comment (ahrens) [reply module/zfs/bpobj.c]: ah, good catch.

File: module/zfs/bpobj.c (hunk 17 above)
Comment (ahrens) [reply module/zfs/bpobj.c]: IMO, even the uglyness of breaking the line in the middle of a `->` is better than this macro.  If you feel that this macro's abstraction is useful, then let's add an inline function, named appropriately to distinguish between "num_subobjs" and "subobjs [object ID]", and use it everywhere.

Comment (PaulZ-98) [reply module/zfs/bpobj.c]: I will break the line up.

Comment (PaulZ-98) [reply module/zfs/bpobj.c]: We are now rid of the meddlesome macro.

**Comment by PaulZ-98** [comment]
Pushed a version earlier today, updated per @ahrens comments.

File: module/zfs/bpobj.c [hunk 22]
```diff
@@ -242,119 +279,167 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-			ASSERT3S(bpo->bpo_phys->bpo_bytes, >=, 0);
-			bpo->bpo_phys->bpo_comp -= comp_before - comp_after;
-			bpo->bpo_phys->bpo_uncomp -=
-			    uncomp_before - uncomp_after;
-		}
+		ASSERT(bpo->bpo_havecomp);
+		/*
+		 * Can't clean up bpobj while it still has subobjs.  Place it
+		 * back in the list ahead of its children.  It will be cleaned
+		 * up once the children are all freed.
```
Comment (ahrens) [inline module/zfs/bpobj.c]: The general structure of code inside the loop is:
```
bpobj_iterate_blkptrs()
...
if (no more work to do on this one) {
  ...
  continue;
}
/* still need to process subobj's */
...
```
I wonder if it would be more readable to structure this like:
```
bpobj_iterate_blkptrs()
...
if (no more work to do on this one) {
 ...
} else {
  /* still need to process subobj's */
  ...
}
```

File: module/zfs/bpobj.c [hunk 23]
```diff
@@ -242,119 +279,167 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+		 */
+		list_insert_head(&stack, bpi);
 
-		bpobj_close(&sublist);
+		/* Add the last subobj to stack. */
```
Comment (ahrens) [inline module/zfs/bpobj.c]: This comment explains what the code below does, which is useful since it's a bit complicated.  I think it would also be useful to have a higher-level comment that explains the overall algorithm, which would explain _why_ we want to add the last subobj to the stack.  I think that's what @behlendorf was getting at with his previous comment: https://github.com/zfsonlinux/zfs/pull/7675/files#r212765323

File: module/zfs/bpobj.c [hunk 24]
```diff
@@ -242,119 +279,167 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+			/*
+			 * If there are no entries, there should
+			 * be no bytes.
+			 */
+			if (bpobj_is_empty(bpo)) {
+				ASSERT0(bpo->bpo_phys->bpo_bytes);
+				ASSERT0(bpo->bpo_phys->bpo_comp);
+				ASSERT0(bpo->bpo_phys->bpo_uncomp);
 			}
+			if (free && (bpi->bpi_parent != NULL)) {
```
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Would it be clearer to have (bpi->bpi_bpo != initial_bpo) ?  Because it's basically a proxy for that.  We don't free it, and we don't try to reference it's "parent" (i.e. to decrement bpo_num_subobjs) because it doesn't have one.

File: module/zfs/bpobj.c (hunk 22 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Ok.  More indenting but it's better than having to spot the continue statement when just reading the code.

File: module/zfs/bpobj.c (hunk 24 above)
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Yeah I was overly focused on "free == TRUE" case (since that was my test) and that shows in the comments.  I'll use "process" as the verb instead of "freed" and "cleaned up".

File: module/zfs/bpobj.c (hunk 23 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: How's this?
```
/*                                                                              
 * Given an initial bpo, start by freeing the BPs that are directly referenced  
 * by that bpo. If the bpo has subobjs, read in its last subobj and add it      
 * to our LIFO stack. By working through our stack, eventually we will encounter
 * a bpo that has no subobjs.  We can free the bpobj_info_t for it, decrement   
 * its parent's subobj count, and if indicated, free the empty bpo from disk.   
 * Parent subobj(s) in our LIFO stack and will need to have their directly      
 * referenced BPs freed and any additonal subobjs processed until they          
 * too have no more subobjs, as so on.                                          
 */     
static int                                                                      
bpobj_iterate_impl(bpobj_t *initial_bpo, bpobj_itor_t func, void *arg,          
    dmu_tx_t *tx, boolean_t free)                                               
{ ```

File: module/zfs/bpobj.c (hunk 24 above)
[the remark this answers is not in the document]
Comment (ahrens) [reply module/zfs/bpobj.c]: yeah I think `bpi->bpi_bpo != initial_bpo` might be more clear.  That way the reader might realize (even without a comment) that the point is to not free the passed-in bpo.

File: module/zfs/bpobj.c (hunk 23 above)
Comment (ahrens) [reply module/zfs/bpobj.c]: > If the bpo has subobjs, read in its last subobj and add it      
> to our LIFO stack.

You could use the more specific verbs `push` and `pop` when talking about the stack.

Maybe also talk about the fact that we re-push the bpo before pushing its last subobj, and this means that we'll revisit this bpo again after visiting its subobj, and then we will evaluate if we need to repeat this (push last subobj) or if the bpo is now empty.

> We can free the bpobj_info_t for it, decrement   
> its parent's subobj count, and if indicated, free the empty bpo from disk.

I think "indicated" means that `free` is set.  I think the decrement also only happens if `free` is set, so maybe reword this to: `We can free its bpobj_info_t, and if requested also free the now-empty bpo from disk and decrement its parent's subobj count.`

> Parent subobj(s) in our LIFO stack will need to have their directly          
> referenced BPs freed

I think that the parent bpo's would already have their directly referenced BP's freed, before any of their child bpo's are pushed on the stack.  The only bpo's on the stack that have directly referenced BP's would not have any children in the stack yet.  But maybe I've misunderstood what you mean by "parent" here?

To cover the `free` and non-`free` cases, maybe we should talk about `visiting` the BP's and bpo's rather than `freeing` them.  Also I think it's the callback that actually does the freeing of the referenced BP's (and there are some callbacks that don't free all BP's).

Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Thanks.  I suppose if the code had been easy to write the comment would also be easy!

```
/*                                                                              
 * Given an initial bpo, start by freeing the BPs that are directly referenced  
 * by that bpo. If the bpo has subobjs, first re-push it to our LIFO stack so   
 * it can be revisited. Read in its last subobj and push the subobj to our      
 * stack. By popping items off our stack, eventually we will encounter          
 * a bpo that has no subobjs.  We can free its bpobj_info_t, and if             
 * requested also free the now-empty bpo from disk and decrement                
 * its parent's subobj count. We continue popping each subobj from our stack,   
 * re-pushing non-empty subobjs and visiting its last subobj until they too     
 * have no more subobjs, as so on.                                              
 */          ```

File: module/zfs/bpobj.c [hunk 25]
```diff
@@ -242,119 +279,167 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+				}
+				err = dmu_object_free(p->bpo_os,
+				    bpi->bpi_object, tx);
+				if (err) {
+					mutex_exit(&bpo->bpo_lock);
+					break;
+				}
+			}
+			mutex_exit(&bpo->bpo_lock);
+			if (bpi->bpi_parent != NULL) {
```
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: I thought the stack would be empty, so I added a zfs_dbgmsg to see and that is indeed the case.

File: module/zfs/bpobj.c [hunk 26]
```diff
@@ -242,119 +277,186 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+/*
+ * Given an initial bpo, start by freeing the BPs that are directly referenced
+ * by that bpo. If the bpo has subobjs, first re-push it to our LIFO stack so
+ * it can be revisited. Read in its last subobj and push the subobj to our
+ * stack. By popping items off our stack, eventually we will encounter
+ * a bpo that has no subobjs.  We can free its bpobj_info_t, and if
+ * requested also free the now-empty bpo from disk and decrement
+ * its parent's subobj count. We continue popping each subobj from our stack,
+ * re-pushing non-empty subobjs and visiting its last subobj until they too
+ * have no more subobjs, as so on.
```
Comment (ahrens) [inline module/zfs/bpobj.c]: as -> and

File: module/zfs/bpobj.c [hunk 27]
```diff
@@ -242,119 +277,186 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+				bpobj_t *p = bpi->bpi_parent->bpi_bpo;
+
+				ASSERT0(bpo->bpo_phys->bpo_num_blkptrs);
+				ASSERT3U(p->bpo_phys->bpo_num_subobjs, >, 0);
+				ASSERT3U(bpi->bpi_index, ==,
+				    p->bpo_phys->bpo_num_subobjs - 1);
+
+				p->bpo_phys->bpo_num_subobjs--;
+
+				VERIFY3U(0, ==, dmu_free_range(p->bpo_os,
```
Comment (ahrens) [inline module/zfs/bpobj.c]: you can use `VERIFY0` here

File: module/zfs/bpobj.c [hunk 28]
```diff
@@ -242,119 +277,186 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+				bpobj_close(bpo);
+				kmem_free(bpi->bpi_bpo, sizeof (bpobj_t));
+			}
+			kmem_free(bpi, sizeof (bpobj_info_t));
+		} else {
+			ASSERT(bpo->bpo_havecomp);
+			/*
+			 * Still need to process subobjs.  Place the bpi back
+			 * in the list ahead of its children.  It will be
+			 * processed again up once the children are all
```
Comment (ahrens) [inline module/zfs/bpobj.c]: I think we actually process (visit) this bpi again after visiting just one child.  At which point if there are more children we'll re-push ourself and push one more child.

typo: extra "up"?

**Comment by ahrens** [comment]
@sdimitro 
> [2] Whenever we find subobjs in a bpo, we repush it on the stack and then push on top of it the first subobj that we want to process, so it gets processed next. When the subobjs are done, we execute call `bpobj_iterate_blkptrs()` function a second time for the same object. Is that ok?

In the `free` case, we can make this work because we should be changing the bpo to indicate that the BP's that have been visited are no longer part of the bpo.  Similarly, when finish processing a subobj, we remove it from the parent bpo.  Since this happens before the parent bpo is visited again, the already-processed subobj will not be there when we re-visit the parent bpo.

However, I don't see how this works in the non-`free` case.  It seems like we'd visit the direct BP's over and over, and we'd also keep pushing the same "last subobj" every time we visit the bpo.  So this would cause an infinite loop.  `zdb` should hit this easily, and there are also some lesser-used code paths in the kernel that do not `free`.

The `bpobj_info_t` may need to record the progress as we visit it, so that we can determine which subobj is the next one to visit.

**Comment by sdimitro** [comment]
I think that if our goal is to emulate the recursive stack from the old code explicitly we could keep most changes of this review the same but re-organize certain a few code blocks within `bpobj_iterate_impl()`.

Giving this a try on the high-level the restructured code would look like this:
```
typedef struct bpobj_info {
	...
	uint64_t bpi_unprocessed_subobjs; // <--- initialized to 0
	boolean_t visited; // <--- initialized to B_FALSE
	...
} bpobj_info_t;

...

static int
bpobj_iterate_impl(...)
{
	...
	for (bpobj_info_t *bpi = bpi_alloc(initial_bpo, NULL, 0, 0);
	    bpi != NULL; bpi = list_head(&stack)) {
		bpobj_t *bpo = bpi->bpi_bpo;

		ASSERT(MUTEX_HELD(bpo));

		if (!bpi_visited) {
			mutex_enter(bpo_lock);
			ASSERT(bpobj_is_open(bpo)); //..etc
			... bpobj_iterate_blkptrs() ...
			... if the the bpo has subobjs then set bpi_unprocessed_subobjs = bpo->bpo_phys->bpo_num_subobjs ...
			bpi_visited = B_TRUE
		} else if (bpi_visited && bpi_unprocessed_subobjs == 0) {
			... < the bpo didn't have any subobj or we processed all of them> ...
			... free if you have to, etc...
			... remove/pop from stack() ...
			mutex_exit(bpo_lock);
		} else {
			... <the bpo was visited before but we have subobjs to process> ...
			ASSERT(MUTEX_HELD(bpo_lock)); // ...etc
			...  decrement bpi_unprocessed_subobjs and push the next subobj to the stack ...
		}
		...
	}
}
```

File: module/zfs/bpobj.c [hunk 29]
```diff
@@ -242,119 +277,185 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-	/* If there are no entries, there should be no bytes. */
-	if (bpobj_is_empty(bpo)) {
-		ASSERT0(bpo->bpo_phys->bpo_bytes);
-		ASSERT0(bpo->bpo_phys->bpo_comp);
-		ASSERT0(bpo->bpo_phys->bpo_uncomp);
-	}
-
-	mutex_exit(&bpo->bpo_lock);
+	/* if error or ERESTART, need to clean up by closing subobjs */
+	bpobj_iterate_cleanup(&stack, err);
```
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Agree.. I did this but without the else.  I can just ASSERT(list_is_empty..)

**Comment by PaulZ-98** [comment]
Pushed a new version addressing @sdimitro suggestions.  I had trouble trying to use list_head vs. list_remove_head in the main for loop, so the code and comments to re-push bpo are still there.  But I was able to use the 2 new struct members bpi_visited and bpi_unprocessed_subobjs to help with the free == B_FALSE case.

File: module/zfs/bpobj.c [hunk 30]
```diff
@@ -242,119 +280,207 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-	if (bpobj_is_empty(bpo)) {
-		ASSERT0(bpo->bpo_phys->bpo_bytes);
-		ASSERT0(bpo->bpo_phys->bpo_comp);
-		ASSERT0(bpo->bpo_phys->bpo_uncomp);
+	/*
+	 * Cleanup anything left on the "stack" after we left the loop.
+	 * Every bpo on the stack is locked so we must remember to undo
+	 * that now (in LIFO order).
+	 */
+	while ((bpi = list_remove_head(&stack)) != NULL) {
```
Comment (sdimitro) [inline module/zfs/bpobj.c]: If we still have entries on our stack then it means that we've
encountered some kind of error, can we assert somewhere
that this is the case? Like inside the loop or right before it
like this:
```
if (!list_is_empty(&stack))
    ASSERT(err != 0);
```

File: module/zfs/bpobj.c [hunk 31]
```diff
@@ -242,119 +280,207 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-			if (err != 0) {
-				bpobj_close(&sublist);
+			/*
+			 * Finished processing this bpo. Unlock, and free
+			 * our "stack" info.
+			 */
+			list_remove_head(&stack);
+			kmem_free(bpi, sizeof (bpobj_info_t));
+		} else {
+			ASSERT(bpo->bpo_havecomp);
```
Comment (sdimitro) [inline module/zfs/bpobj.c]: style nit: instead of
```
{
   ASSERT(bpo->bpo_havecomp);
   /*
    * Still need to process subobjs.
    */
   ...
}
```
switch the order, and maybe rephrase to something like this?
```
{
   /*
    * We have unprocessed subobjs. Process the next one.
    */
   ASSERT(bpo->bpo_havecomp);
   ...
}
```

File: module/zfs/bpobj.c [hunk 32]
```diff
@@ -242,119 +280,207 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+ * requested also free the now-empty bpo from disk and decrement
+ * its parent's subobj count. We continue popping each subobj from our stack,
+ * visiting its last subobj until they too have no more subobjs, and so on.
+ */
+static int
+bpobj_iterate_impl(bpobj_t *initial_bpo, bpobj_itor_t func, void *arg,
+    dmu_tx_t *tx, boolean_t free)
+{
+	list_t stack;
+	bpobj_t *bpo;
```
Comment (sdimitro) [inline module/zfs/bpobj.c]: style nit: inline within the 2 loops

File: module/zfs/bpobj.c [hunk 33]
```diff
@@ -242,119 +280,207 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+					    bpo->bpo_phys->bpo_subobjs != 0) {
+						ASSERT0(bpo->bpo_phys->
+						    bpo_num_subobjs);
+						err = dmu_object_free(
+						    bpo->bpo_os,
+						    bpo->bpo_phys->bpo_subobjs,
+						    tx);
+						if (err)
+							break;
+						dmu_buf_will_dirty(
```
Comment (sdimitro) [inline module/zfs/bpobj.c]: I can be wrong about this but won't we have called `dmu_buf_will_dirty()` on the `bpo_dbuf` already, at the beginning of this loop? Do we need to do this again?

File: module/zfs/bpobj.c [hunk 34]
```diff
@@ -242,119 +280,207 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
-			err = dmu_object_free(bpo->bpo_os,
-			    objarray[blkoff], tx);
+			err = bpobj_open(sublist, bpo->bpo_os,
+			    obj_from_sublist);
 			if (err)
 				break;
-			bpo->bpo_phys->bpo_num_subobjs--;
-			ASSERT3S(bpo->bpo_phys->bpo_num_subobjs, >=, 0);
+			if (free)
+				dmu_buf_will_dirty(sublist->bpo_dbuf, tx);
```
Comment (sdimitro) [inline module/zfs/bpobj.c]: Same question as above? Won't we call `dmu_buf_will_dirty()` when we enter the loop next time?

File: module/zfs/bpobj.c [hunk 35]
```diff
@@ -242,119 +280,207 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+			if (err != 0)
 				break;
 		}
+		/*
+		 * We've finished with this bpo's directly-referenced BP's.
+		 * If it has no subobjs, we are done processing it. We can free
+		 * its bpobj_info_t (unless it is the topmost, initial_bpo).
+		 * If we are freeing from disk, we can also do that.
+		 */
+		if (bpo->bpo_phys->bpo_num_subobjs == 0 ||
```
Comment (sdimitro) [inline module/zfs/bpobj.c]: I may be missing some edge-case here so please correct me if I do.

For this case in the loop we have all these predicates for what it seems like should be the same thing:
```
if (bpo->bpo_phys->bpo_num_subobjs == 0 ||
    !bpo->bpo_havesubobj ||
    bpo->bpo_phys->bpo_subobjs == 0 ||
    bpi->bpi_unprocessed_subobjs == 0) {
        ...
}
```

Is there any chance that we can enter this if-clause and `bpi->bpi_unprocessed_subobjs` is not 0 but one of the other predicates are true?

I think it would be cleaner if we made all the control flow in the loop based only in `bpi` related information.
Could we do something like this maybe?
```
static bpobj_info_t *
bpi_alloc(bpobj_t *bpo, bpobj_info_t *parent, uint64_t obj, uint64_t index)
{
	...
	if (bpo->bpo_havesubobj && bpo->bpo_phys->bpo_subobjs != 0) {
		bpi->bpi_unprocessed_subobjs = bpo->bpo_phys->bpo_num_subobjs;
	}
	return (bpi);
}

static int
bpobj_iterate_impl(bpobj_t *initial_bpo, bpobj_itor_t func, void *arg,
    dmu_tx_t *tx, boolean_t free) {
	...
	if (!visited) {
		...
	}

	if (bpi->bpi_unprocessed_subobjs == 0) {
		...
	} else {
	...
}
```

Again, if I may be wrong about this.

File: module/zfs/bpobj.c (hunk 30 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: yes ASSERT0(err) at top of loop with the other asserts.

File: module/zfs/bpobj.c (hunk 31 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: ok

File: module/zfs/bpobj.c (hunk 32 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Was able to do bpo.  bpi is needed outside the scope of the while statement.  stack is needed by the whole function.

File: module/zfs/bpobj.c (hunk 35 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: This would probably work, but its just moving the logic into bpi_alloc.  It might be a bit ungainly as it is but I think it's pretty clear we are saying "if anything says we're empty".  So I'd like to leave it.

File: module/zfs/bpobj.c (hunk 34 above)
Comment (PaulZ-98) [reply module/zfs/bpobj.c]: I'll test it without the extra calls to will_dirty.

**Comment by PaulZ-98** [comment]
Pushed an updated version @sdimitro @ahrens

**Comment by PaulZ-98** [comment]
Also rebased @behlendorf

File: module/zfs/bpobj.c (hunk 35 above)
Comment (sdimitro) [reply module/zfs/bpobj.c]: If it would work then I think it would be better to change it.
I think it is confusing having all these predicates because as we've seen from earlier revisions having `bpi->bpi_unprocessed_subobjs == 0` does not mean that `bpo->bpo_phys->bpo_num_subobjs` is also zero (that is the case when `free` == 0). It is better to have a single-point of reference if we can and not obscure the logic with multiple ones.

Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Ok.  Pushed a new version with this.

File: module/zfs/bpobj.c [hunk 36]
```diff
@@ -242,119 +282,200 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+
+		if (bpi->bpi_visited == B_FALSE) {
+			err = bpobj_iterate_blkptrs(bpi, func, arg, tx, free);
+			bpi->bpi_visited = B_TRUE;
+			if (err != 0)
 				break;
 		}
+		/*
+		 * We've finished with this bpo's directly-referenced BP's.
+		 * If it has no subobjs, we are done processing it. We can free
```
Comment (ahrens) [inline module/zfs/bpobj.c]: How about `If we have also processed all its subobjs, we are done processing it.`

File: module/zfs/bpobj.c [hunk 37]
```diff
@@ -242,119 +282,200 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+				if (free) {
+					bpobj_t *p = bpi->bpi_parent->bpi_bpo;
+
+					ASSERT0(bpo->bpo_phys->bpo_num_blkptrs);
+					ASSERT3U(p->bpo_phys->bpo_num_subobjs,
+					    >, 0);
+					ASSERT3U(bpi->bpi_index, ==,
+					    p->bpo_phys->bpo_num_subobjs - 1);
+
+					p->bpo_phys->bpo_num_subobjs--;
```
Comment (ahrens) [inline module/zfs/bpobj.c]: assert that it's dirty here?

File: module/zfs/bpobj.c [hunk 38]
```diff
@@ -242,119 +282,200 @@ bpobj_iterate_impl(bpobj_t *bpo, bpobj_itor_t func, void *arg, dmu_tx_t *tx,
...
+
+					VERIFY0(dmu_free_range(p->bpo_os,
+					    p->bpo_phys->bpo_subobjs,
+					    bpi->bpi_index * sizeof (uint64_t),
+					    sizeof (uint64_t), tx));
+
+					/* eliminate the empty subobj */
```
Comment (ahrens) [inline module/zfs/bpobj.c]: `empty subobj list`?

File: module/zfs/bpobj.c (hunk 30 above)
Comment (ahrens) [reply module/zfs/bpobj.c]: I don't think that's what @sdimitro was suggesting.  We want to assert that in the non-error case, the list is empty.

Comment (PaulZ-98) [reply module/zfs/bpobj.c]: Ok.  That ASSERT got lost, it used to be in the cleanup loop.

**Comment by PaulZ-98** [comment]
Pushed an updated version in response to @ahrens comments.
