### PR TITLE
Fix zdb -R with 'b' flag

### LINKED ISSUE #9640: zdb -R with 'b' flag fails to display block
### Describe the problem you're observing
zdb -R <pool> <dva>:b fails due to the indirect block being compressed, and the 'b' and 'd' flag not working in tandem when specified.
```
# zdb -ddddddbbbbbb tank/fs3 2 |more
Dataset tank/fs3 [ZPL], ID 27, cr_txg 623816, 153M, 8 objects, rootbp DVA[0]=<0:1401fa00:200> DVA[1]=<0:16025800:200> [L0 DMU objset] fletcher4 lz4 unencrypted LE co
ntiguous unique double size=1000L/200P birth=1055959L/1055959P fill=8 cksum=e983cfb88:52a126b42fe:f469c017435a:1f766d5ef4ccad

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         2    2   128K     1K     9K     512    10K  100.00  ZFS plain file (K=inherit) (Z=inherit)
                                               168   bonus  System attributes
	dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED 
	dnode maxblkid: 9
	path	/syslog
	uid     0
	gid     0
	atime	Mon Nov 25 10:32:09 2019
	mtime	Mon Sep 16 13:23:08 2019
	ctime	Mon Sep 16 13:23:08 2019
	crtime	Mon Sep 16 13:23:08 2019
	gen	623821
	mode	100640
	size	9314
	parent	34
	links	1
	pflags	40800000004
Indirect blocks:
               0 L1  DVA[0]=<0:9001c400:400> DVA[1]=<0:9401c400:400> [L1 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique double size=20000L/400P birth
=623821L/623821P fill=10 cksum=a0eda09ccb:3f4c80a76e8b:10ccdab5375fde:390bb6be5fb51f1
               0  L0 DVA[0]=<0:6041e00:200> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=400L/200P birth=623821L/623821P fill=1 cks
um=239a072c46:9690c9e7f2d:1a8b7b42bdbb0:383da26fd31df3
             400  L0 DVA[0]=<0:6042000:200> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=400L/200P birth=623821L/623821P fill=1 cks
um=11315ef78a:682088d7a82:14c44240d2ce5:2e49aa8d55de8f
             800  L0 DVA[0]=<0:6042200:400> [L0 ZFS plain file] fletcher4 uncompressed unencrypted LE contiguous unique single size=400L/400P birth=623821L/623821P f
ill=1 cksum=4873895d37:24e4311be1f1:c75d3de2c9706:328e984cc1588a8
...
...
            2400  L0 DVA[0]=<0:6043800:200> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=400L/200P birth=623821L/623821P fill=1 cks
um=88486bc73:3cc931b02dc:dbd9bb44b44a:21935a57df9bd3

		segment [0000000000000000, 0000000000002800) size   10K

# zdb -R tank 0:9001c400:400:b
Found vdev: /root/file1
Segmentation fault
# zdb -R tank 0:9001c400:400:bd
Found vdev: /root/file1
EMBEDDED [L19 unallocated] et=1 �(�� size=1b42bdcL/5cP birth=16501189062636899706L
# zdb -R tank 0:9001c400:400:db
^C
# zdb -R tank 0:9001c400:400:b80
Found vdev: /root/file1
len < buflen
ASSERT at ../../module/zfs/spa_misc.c:1519:snprintf_blkptr()Aborted
# zdb -R tank 0:9001c400:400:db80
***Invalid flag: 0
Found vdev: /root/file1
Trying 00400 -> 00600 (inherit)
ret == 0 (0x16 == 0)
ASSERT at ../../module/zfs/zio_compress.c:162:zio_decompress_data()Aborted
# zdb -R tank 0:9001c400:400:id
Found vdev: /root/file1
Trying 00400 -> 00600 (inherit)
ret == 0 (0x16 == 0)
ASSERT at ../../module/zfs/zio_compress.c:162:zio_decompress_data()Aborted
```

### PR DESCRIPTION
**Pull request by PaulZ-98**
zdb -R :b fails due to the indirect block being compressed,
and the 'b' and 'd' flag not working in tandem when specified.
Fix the flag parsing code and create a zfs test for zdb -R
block display.  Also fix the zio flags where the dotted notation
for the vdev portion of DVA (i.e. 0.0:offset:length) fails.

Signed-off-by: Paul Zuchowski <pzuchowski@datto.com>
Fixes #9640

### Motivation and Context
zdb -R block display functionality did not handle the decompress flag, or its block offset parsing.  If a block was compressed, but not decompressed, the display code would seg fault.  A zfs test for the block display functionality was lacking.

### Description
Fix the parsing code to handle :b :d and the block offset properly.  Detect a bad block, retry with decompression, and if block is still bad, warn instead of seg faulting.  Limit the indirect block display to the logical size given by the user, not the inflated size chosen by the decompression algorithm guessing.  Create a zfs test which compares the -R block display to the -ddddddbbbbbb block display.

### How Has This Been Tested?
Developed a zfs test for block display.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: cmd/zdb/zdb.c [hunk 1]
```diff
@@ -6346,6 +6347,34 @@ zdb_parse_block_sizes(char *sizes, uint64_t *lsize, uint64_t *psize)
...
+		return (B_FALSE);
+	}
+	if (BP_GET_PSIZE(bp) > SPA_MAXBLOCKSIZE) {
+		return (B_FALSE);
+	}
+	if (BP_IS_EMBEDDED(bp)) {
+		if (BPE_GET_ETYPE(bp) >= NUM_BP_EMBEDDED_TYPES) {
+			return (B_FALSE);
+		}
+	}
```
Comment (behlendorf) [inline cmd/zdb/zdb.c]: It would be nice to include the DVA checks from `zfs_blkptr_verify` here.  Or possibly better yet, do a little refactoring so there's a single shared function to validate bps.  This could be left as a follow up improvement.

File: cmd/zdb/zdb.c [hunk 2]
```diff
@@ -6489,10 +6530,9 @@ zdb_read_block(char *thing, spa_t *spa)
 		 */
 		zio_nowait(zio_vdev_child_io(zio, bp, vd, offset, pabd,
 		    psize, ZIO_TYPE_READ, ZIO_PRIORITY_SYNC_READ,
-		    ZIO_FLAG_DONT_CACHE | ZIO_FLAG_DONT_QUEUE |
```
Comment (behlendorf) [inline cmd/zdb/zdb.c]: Why was `ZIO_FLAG_DONT_QUEUE` removed from here?  Did it result in problems?  I'm not certain, since it wasn't commented, but my hunch is it was included to ensure the vdev queue never tries to create an aggregate IO for this read via `vdev_queue_aggregate()`.

Comment (PaulZ-98) [reply cmd/zdb/zdb.c]: This was to get around this issue:
```
# zdb -R testpool 1.0:8038600:600:d
Found vdev: /root/x.2
tree->avl_numnodes > 0
ASSERT at ../../module/avl/avl.c:747:avl_remove()Aborted
```
I'd have to go back and look at the reason that the avl_tree was already empty when the zio was not queued..  I'll let you know.

Comment (PaulZ-98) [reply cmd/zdb/zdb.c]: ZIO_FLAG_DONT_QUEUE is only set in zdb (before this PR), in vdev_queue_aggregate, and in vdev_queue_io.  It looks like it is only used to prevent re-queueing of a queued zio (vdev_queue.c line 808).  So I don't believe zdb should be setting this flag, but would like confirmation.

Comment (behlendorf) [reply cmd/zdb/zdb.c]: After looking at this again, you're right the makes sense.  Though I still personally find the name a bit confusing!  OK, so this does need to go.

File: cmd/zdb/zdb.c [hunk 3]
```diff
@@ -6408,34 +6437,46 @@ zdb_read_block(char *thing, spa_t *spa)
...
+					    strchr(flagbitstr, *p) == NULL) {
+						offstr[j] = *p;
+						j++;
+						if (i + j > strlen(flagstr))
+							break;
+						p++;
+						nextbit = flagbits[(uchar_t)*p];
+					}
+					blkptr_offset = strtoull(offstr, &end,
+					    16);
```
Comment (behlendorf) [inline cmd/zdb/zdb.c]: Since for indirect blocks the offsets will always be 128-byte aligned, I think we can add an additional sanity check here to print a fatal error when given a non-aligned offset.

Please also add to the man page that `zdb -R` requires that all provided values be specified in hex and that the traditional leading `0x` is optional.  I bumped on this a few time and didn't see it documented anywhere.

File: cmd/zdb/zdb.c [hunk 4]
```diff
@@ -6578,14 +6618,28 @@ zdb_read_block(char *thing, spa_t *spa)
 		borrowed = B_TRUE;
 	}
 
+	/* Try to detect invalid block pointer. */
+	if ((flags & ZDB_FLAG_PRINT_BLKPTR || flags & ZDB_FLAG_INDIRECT) &&
+	    !(flags & ZDB_FLAG_DECOMPRESS)) {
```
Comment (behlendorf) [inline cmd/zdb/zdb.c]: The warning is helpful, but perhaps we can do better.  We have this nice `zdb_blkptr_verify()` function to sanity check block pointers.  I'd argue that for `-i` and `-b` it would make sense to automatically retry with `-d` when `zdb_blkptr_verify()` fails and only then print an error when both fail.  That's one less thing to have to remember when debugging.

Comment (PaulZ-98) [reply cmd/zdb/zdb.c]: Good idea on retry with -d.  I'll also see how hard it is to refactor zfs_blkptr_verify to avoid the code duplication and let you know about that.

Comment (PaulZ-98) [reply cmd/zdb/zdb.c]: I have made the suggested changes including refactoring zfs_blkptr_verify.

File: tests/zfs-tests/tests/functional/cli_root/zdb/zdb_display_block.ksh [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+
+# get object number of file
+listing=$(ls -i $init_data)
+set -A array $listing
+obj=${array[0]}
+log_note "file $init_data has object number $obj"
+
+output=$(zdb -ddddddbbbbbb $TESTPOOL/$TESTFS $obj 2> /dev/null \
+    |grep -m 1 "L1  DVA" |head -n1)
+dva=$(grep -oP 'DVA\[0\]=<\K.*?(?=>)' <<< "$output")
```
Comment (freqlabs) [inline tests/zfs-tests/tests/functional/cli_root/zdb/zdb_display_block.ksh]: For compatibility with FreeBSD please avoid using the Perl extensions with grep. This looks the same as what was changed in 6f481612f37a4cffaff142b80f6a4c37257406c6 for an example of an alternative that works on FreeBSD.

Comment (PaulZ-98) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_display_block.ksh]: Because of multiple DVA copies I think the suggested sed method needs another filter on it (sed is taking final '>' as end delimiter).

```
$ export output="0 L1 DVA[0]=<0:40109600:2000> DVA[1]=<0:50000800:2000> [L1 ZFS plain file]"
$ echo $output | sed -Ene 's/^.+DVA\[0\]=<(.+)>.*/\1/p'
0:40109600:2000> DVA[1]=<0:50000800:2000
$ echo $output | sed -Ene 's/^.+DVA\[0\]=<(.+)>.*/\1/p' | awk '{split($0,array,">")} END{print array[1]}'
0:40109600:2000
```

Comment (freqlabs) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_display_block.ksh]: How about this and I will update the existing instances to the same:
```
$ echo $output | sed -Ene 's/^.+DVA\[0\]=<([^>]+)>.*/\1/p'
0:40109600:2000
```

Comment (PaulZ-98) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_display_block.ksh]: Nice.  You speak fluent sed!  Will update zdb_display_block.ksh here.

**Comment by PaulZ-98** [comment]
https://github.com/zfsonlinux/zfs/pull/9729/commits/bd02fa3da20dcab7da03534c724d2403b69fa8b7
has the updated changes.  Let me know if I need to re-push due to the other commits being in this PR too.

**Comment by behlendorf** [comment]
@PaulZ-98 since #9733 has been merged please go ahead and rebase this.

**Comment by PaulZ-98** [comment]
All the builds failed.  Is something going on with the build scripts or is it this PR?

File: module/zfs/zio.c [hunk 6]
```diff
@@ -890,36 +890,69 @@ zio_root(spa_t *spa, zio_done_func_t *done, void *private, enum zio_flag flags)
...
+ *    2) BLK_VERIFY_HALT (call zfs_panic_remover on error)
+ */
+static boolean_t
+zio_panic_recover(enum blk_verify_flag blk_verify, const char *fmt, ...)
+{
+	/* determine if the caller should return (B_TRUE) or keep checking */
+	if (blk_verify == BLK_VERIFY_ONLY)
+		return (B_TRUE);
+
+	zfs_panic_recover(fmt);
```
[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/zio.c]: I implemented this for checking all the blkptr_t fields.  Down in the DVA validation, there are continue statements after the zfs_panic_recover calls.  So I probably can't just return a boolean result of zfs_blkptr_verify_impl there.  Should I be checking zfs_recover to decide whether to continue?

[the remark this answers is not in the document]
Comment (behlendorf) [reply module/zfs/zio.c]: I see.  Then perhaps the cleanest thing to do would be to set a `valid` flag for all of the checks and return that.

This way when `BLK_VERIFY_ONLY` is set all errors in a block pointer are logged (instead of just the first).  When `BLK_VERIFY_HALT` is set the behavior is unchanged aside from the new return value.

I'm thinking `zfs_blkptr_verify_log` would be a better name for the wrapper function as well.  What do you think about this:

```
static void
zfs_blkptr_verify(spa_t *spa, const blkptr_t *bp, boolean_t config_held)
{
        boolean_t valid = B_TRUE; 

        if (!DMU_OT_IS_VALID(BP_GET_TYPE(bp))) {
                valid = zfs_blkptr_verify_log(
                    "blkptr at %p has invalid TYPE %llu",
                    bp, (longlong_t)BP_GET_TYPE(bp));
        }
        ...

        for (int i = 0; i < BP_GET_NDVAS(bp); i++) {
                uint64_t vdevid = DVA_GET_VDEV(&bp->blk_dva[i]);

                if (vdevid >= spa->spa_root_vdev->vdev_children) {
                        valid = zfs_blkptr_verify_log(
                            "blkptr at %p DVA %u has invalid VDEV %llu",
                            bp, i, (longlong_t)vdevid);
                        continue;
                }
                ...
        }
        ...

        return (valid);
}
```

[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/zio.c]: Thanks I'll give this a try.

[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/zio.c]: Here's a sample.
{code}
# zdb -G -R tank 0:9001c400:400:b
Found vdev: /root/file1
DVA[0]=<0:6041e00:200> [L0 ZFS plain file] fletcher4 lz4 unencrypted LE contiguous unique single size=400L/200P birth=623821L/623821P fill=1 cksum=239a072c46:9690c9e7f2d:1a8b7b42bdbb0:383da26fd31df3
ZFS_DBGMSG(zdb) START:
spa.c:5051:spa_open_common(): spa_open_common: opening tank
spa_misc.c:410:spa_load_note(): spa_load(tank, config trusted): LOADING
vdev.c:125:vdev_dbgmsg(): file vdev '/root/file1': best uberblock found for spa tank. txg 1482823
spa_misc.c:410:spa_load_note(): spa_load(tank, config untrusted): using uberblock with txg=1482823
spa_misc.c:410:spa_load_note(): spa_load(tank, config trusted): spa_load_verify found 0 metadata errors and 1 data errors
spa_misc.c:410:spa_load_note(): spa_load(tank, config trusted): LOADED
zio.c:914:zfs_blkptr_verify_log(): tank: blkptr at 0x3482000 has invalid TYPE 158
zio.c:914:zfs_blkptr_verify_log(): tank: blkptr at 0x3482000 has invalid CHECKSUM 127
zio.c:914:zfs_blkptr_verify_log(): tank: blkptr at 0x3482000 has invalid COMPRESS 45
zio.c:914:zfs_blkptr_verify_log(): tank: blkptr at 0x3482000 DVA 0 has invalid VDEV 290
zio.c:914:zfs_blkptr_verify_log(): tank: blkptr at 0x3482000 DVA 1 has invalid VDEV 5177392
zio.c:914:zfs_blkptr_verify_log(): tank: blkptr at 0x3482000 DVA 2 has invalid VDEV 10240
ZFS_DBGMSG(zdb) END
{\code}

[the remark this answers is not in the document]
Comment (PaulZ-98) [reply module/zfs/zio.c]: Was talking with Tom about this and he thinks we shouldn't be printing out all these ominous messages for something that ultimately worked on the retry.  I could further refactor this to defer the printing either to the caller or to a different interface (or another BLK_VERIFY enum) that gets called when zfs_blkptr_verify is FALSE... what's your thinking on this?

[the remark this answers is not in the document]
Comment (behlendorf) [reply module/zfs/zio.c]: Adding another enum which could be used by `zdb` seems like a reasonable way to go.  Perhaps, `BLK_VERIFY_LOG` (which does log), `BLK_VERIFY_ONLY` (which does not log), and `BLK_VERIFY_HALT`.  Then the caller would be able to determine if it merits logging.

Offhand, the only place we might not want to log this would be `zdb`.  But even there you'd need to specify `-G` to see the errors.  In all other places, the block pointer should always be valid.  If it's ever not that's noteworthy and I think worth logging.

**Comment by PaulZ-98** [comment]
I cleaned up the Makefile.am for the zdb tests and the tests are looking better.  Is the ztest failure a known issue (Debian 10)?

**Comment by freqlabs** [comment]
It looks like the ztest failure is due to a failed assertion that the spa errlog is empty after a scrub (ztest.c:6012). Your zio changes don't seem to be the cause of this.
