### PR TITLE
Clearer wording on Errata #4 for non-destructive remedy

### LINKED ISSUE #8682: Errata #4 doesn't mention non-destructive mitigation option
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 0.8.0 rc4 
SPL Version	| 

### Describe the problem you're observing
@behlendorf Recently clarified how Errata #4 is actually processed in this comment:

https://github.com/zfsonlinux/zfs/issues/8625#issuecomment-485004208

from there:

> Deleting all the snapshots on the original source pool should be sufficient. The reason is that the fundamental fix for raw send issue was to associate an "IVset guid" with each snapshot. It acts as an identifier for the set of IVs used to encrypt a given snapshot and is now required during a raw receive. Since snapshot are immutable by design this "IVset guid" couldn't be associated with existing snapshots.
> 
> The errata will be reported in `zpool status` when either:
> 
>     1. The `bookmarks_v2` feature has not been enabled, or
> 
>     2. A snapshot is detected without the required "IVset guid"
> 
> 
> If nothing is reported then all the snapshots in your encrypted pool do include the "IVset guid". I hope that helps clear things up.

If this fact was to be communicated more clearly, it could help people who have top-level encrypted datasets and who don't want to destroy their whole pools, as mentioned in this comment of mine:
https://github.com/zfsonlinux/zfs/pull/8308#issuecomment-476116094
### Describe how to reproduce the problem
Simply creating new snapshots and deleting old ones is sufficient to get rid of the warning.

### PR DESCRIPTION
**Pull request by JMoVS**
Errata #4 doesn’t mention a non-destructive way to clear it. This commits fixes #8682

### Motivation and Context
Users of existing pools, especially pools with top-level encrypted datasets could run into trouble trying to work around Errata #4. After @behlendorf's clarification, there is a non-destructive way that is possible. This commit mentions that.

This commit attempts to fix #8682.

### Description
Just a documentation change where previous Errata #4 changes were made-

### How Has This Been Tested?
only documentation changes, haven't tested them myself.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rlaager** [comment]
You have this:
> Enable the bookmark_v2 feature, backup these datasets to new encrypted datasets, and destroy the old ones or create new snapshots and destroy all snapshots that were created before enabling bookmark_v2.

It wasn't clear to me the precedence of that "or". I read it a couple times and it wasn't making sense, as new datasets wouldn't have snapshots to delete. In reading the referenced issue, it sounds like deleting the snapshots is an alternative to creating new datasets.

Also, from what I can see, creating snapshots is not required to fix the issue. The deletion is the important part.

How about something like this:
> Enable the bookmark_v2 feature. Then, copy these datasets to new encrypted datasets, and destroy the old datasets. Alternatively, destroy all snapshots (on encrypted datasets) that were created before enabling bookmark_v2.

Or focus on the snapshot deletion first, which might be even better:
> Enable the bookmark_v2 feature. Destroy all snapshots (on encrypted datasets) that were created before enabling bookmark_v2. If preserving those snapshots is required, copy them to new encrypted datasets with zfs send.

**Comment by JMoVS** [comment]
> Enable the bookmark_v2 feature. Destroy all snapshots (on encrypted datasets) that were created before enabling bookmark_v2. If preserving those snapshots is required, copy them to new encrypted datasets with zfs send.

I like that wording a lot. And you're right: It's about getting rid of existing snapshots.

**Comment by rlaager** [comment]
> > Enable the bookmark_v2 feature. Destroy all snapshots (on encrypted datasets) that were created before enabling bookmark_v2. If preserving those snapshots is required, copy them to new encrypted datasets with zfs send.
> 
> I like that wording a lot. And you're right: It's about getting rid of existing snapshots.

Can you update the PR accordingly?

File: cmd/zpool/zpool_main.c [hunk 1]
```diff
@@ -2572,12 +2572,15 @@ show_import(nvlist_t *config)
...
-				    "datasets, and destroy the old ones. "
-				    "If this pool does\n\tnot contain any "
-				    "encrypted datasets, simply enable the "
-				    "bookmark_v2\n\tfeature.\n"));
+				    "the bookmark_v2 feature. Destroy all "
+				    "snapshots (on encrypted datasets) that "
+				    "were created before enabling bookmark_v2. "
+				    "If preserving those snapshots is "
+				    "required, copy them to new encrypted "
+				    "datasets with zfs send. If this pool "
```
Comment (JMoVS) [inline cmd/zpool/zpool_main.c]: this line is worrying me. Existing snapshots won't be able to be `raw`-received even into new encrypted datasets, so effectively one would either have to lose raw-recv capability for these snapshots or copy it. Do we have to make that clearer?

File: cmd/zpool/zpool_main.c [hunk 2]
```diff
@@ -7637,12 +7640,15 @@ status_callback(zpool_handle_t *zhp, void *data)
...
-			    "enable the bookmark_v2 feature, backup\n\tany "
-			    "existing encrypted datasets to new encrypted "
-			    "datasets,\n\tand destroy the old ones. If this "
-			    "pool does not contain any\n\tencrypted "
+			    "enable the bookmark_v2 feature	Destroy all "
+			    "snapshots (on encrypted datasets) that "
+			    "were created before enabling bookmark_v2. "
+			    "If preserving those snapshots is "
+			    "required, copy them to new encrypted "
+			    "datasets with zfs send. If this pool "
```
Comment (JMoVS) [inline cmd/zpool/zpool_main.c]: same issue as https://github.com/zfsonlinux/zfs/pull/8683/commits/004156a553673f414d3370ad6dd74fc525a9713a#r279896207

File: cmd/zpool/zpool_main.c (hunk 1 above)
Comment (rlaager) [reply cmd/zpool/zpool_main.c]: I'm not 100% certain, but I thought the approach was to do a non-raw send from $pool/$old_dataset to $pool/$new_dataset. Then the snapshots in $new_dataset were written with an "IVset GUID", and thus everything is fine?

File: cmd/zpool/zpool_main.c [hunk 3]
```diff
@@ -7637,12 +7640,15 @@ status_callback(zpool_handle_t *zhp, void *data)
 			    "contain an on-disk incompatibility\n\twhich "
 			    "needs to be corrected.\n"));
 			(void) printf(gettext("action: To correct the issue "
-			    "enable the bookmark_v2 feature, backup\n\tany "
-			    "existing encrypted datasets to new encrypted "
-			    "datasets,\n\tand destroy the old ones. If this "
-			    "pool does not contain any\n\tencrypted "
+			    "enable the bookmark_v2 feature	Destroy all "
```
Comment (rlaager) [inline cmd/zpool/zpool_main.c]: Typo on this line? It looks like there is a tab between feature and Destroy, with no period.

File: cmd/zpool/zpool_main.c (hunk 1 above)
Comment (JMoVS) [reply cmd/zpool/zpool_main.c]: Yes, that is fine, that is true. I was just wondering if the requirement/necessity (it will refuse to send raw, but then also sending a -R won't work or a -p for properties because that would force a raw send in the current state of things 😆 if I checked it correctly...

Comment (JMoVS) [reply cmd/zpool/zpool_main.c]: so I was wondering whether to change it maybe to
```
If preserving those snapshots is required, zfs send (non-raw) them to new encrypted datasets.
```

Comment (rlaager) [reply cmd/zpool/zpool_main.c]: Sure

**Comment by JMoVS** [comment]
there's a very weird mixture of tabs vs spaces going on in that code section...

File: cmd/zpool/zpool_main.c (hunk 3 above)
Comment (JMoVS) [reply cmd/zpool/zpool_main.c]: fixed

File: cmd/zpool/zpool_main.c (hunk 1 above)
Comment (JMoVS) [reply cmd/zpool/zpool_main.c]: changed

File: cmd/zpool/zpool_main.c [hunk 4]
```diff
@@ -2572,12 +2572,15 @@ show_import(nvlist_t *config)
...
-				    "these datasets\n\tto new encrypted "
-				    "datasets, and destroy the old ones. "
-				    "If this pool does\n\tnot contain any "
-				    "encrypted datasets, simply enable the "
-				    "bookmark_v2\n\tfeature.\n"));
+				    "the bookmark_v2 feature. Destroy all "
+				    "snapshots (on encrypted datasets) that "
+				    "were created before enabling bookmark_v2. "
+				    "If preserving those snapshots is "
+				    "required, zfs send (non-raw) them "
```
Comment (behlendorf) [inline cmd/zpool/zpool_main.c]: nit. 'zfs send' would be consistent with the 'zfs recv' usage above.

File: cmd/zpool/zpool_main.c [hunk 5]
```diff
@@ -7637,12 +7640,15 @@ status_callback(zpool_handle_t *zhp, void *data)
...
 			(void) printf(gettext("action: To correct the issue "
-			    "enable the bookmark_v2 feature, backup\n\tany "
-			    "existing encrypted datasets to new encrypted "
-			    "datasets,\n\tand destroy the old ones. If this "
-			    "pool does not contain any\n\tencrypted "
+			    "enable the bookmark_v2 feature. Destroy all "
+			    "snapshots (on encrypted datasets) that "
+			    "were created before enabling bookmark_v2. "
+			    "If preserving those snapshots is "
+			    "required, zfs send (non-raw) them "
```
Comment (behlendorf) [inline cmd/zpool/zpool_main.c]: nit: 'zfs send'

**Comment by JMoVS** [comment]
> The wording sounds good to me. This is an approval for that much.
> 
> I have not personally confirmed that deleting snapshots is sufficient. I am relying on the quotes from Brian to that effect.
> 
> I also have not personally run this code to verify the `zpool status` output is correctly line-wrapped and tabbed. @JMoVS, can you paste in an example of the `zpool status` output?

I verified that getting rid of snapshots (and a subsequent reimport of the pool which is always necessary) was sufficient to get rid of the Errata on O3X (I'm an O3X user). I'll see if I can directly pull in that commit into the O3X codebase and test it directly, otherwise I very welcome if somebody else can more easily confirm correct formatting of the `zpool status` output ;-)

File: cmd/zpool/zpool_main.c [hunk 6]
```diff
@@ -2572,12 +2572,15 @@ show_import(nvlist_t *config)
 				    "incompatibility\n\twhich may cause "
 				    "on-disk corruption with 'zfs recv' and "
 				    "which needs\n\tto be corrected. Enable "
-				    "the bookmark_v2 feature, backup "
-				    "these datasets\n\tto new encrypted "
-				    "datasets, and destroy the old ones. "
-				    "If this pool does\n\tnot contain any "
-				    "encrypted datasets, simply enable the "
-				    "bookmark_v2\n\tfeature.\n"));
+				    "the bookmark_v2 feature. Destroy all "
```
Comment (tcaputi) [inline cmd/zpool/zpool_main.c]: nit: i would connect these 2 sentences with an "and'

**Comment by tcaputi** [comment]
Small correction, any bookmarks created before enabling bookmark_v2 will also need to be destroyed.

**Comment by JMoVS** [comment]
@tcaputi I changed it to include bookmarks in the language.

@all please check again that I didn't mess it up now. If you want me to rebase and squash it to 1 commit again, let me know. There is a weird mix of tabs and spaces in that code section - I maintained how it was

**Comment by behlendorf** [comment]
@JMoVS @rlaager @tcaputi I think the proposed wording is a different improvement but still a little awkward.  How about this alternate proposed wording:

"Existing encrypted snapshots and bookmarks contain an on-disk incompatibility.  This may cause on-disk corruption if they are used with 'zfs recv'.  To correct the issue enable the bookmark_v2 feature.  No additional action is needed if there are no encrypted snapshots or bookmarks.  If preserving the encrypted snapshots and bookmarks is required use a non-raw send to backup and restore them.  Alternately, they may be removed to resolve the incompatibility."

**Comment by JMoVS** [comment]
> @JMoVS @rlaager @tcaputi I think the proposed wording is a different improvement but still a little awkward. How about this alternate proposed wording:
> 
> "Existing encrypted snapshots and bookmarks contain an on-disk incompatibility. This may cause on-disk corruption if they are used with 'zfs recv'. To correct the issue enable the bookmark_v2 feature. No additional action is needed if there are no encrypted snapshots or bookmarks. If preserving the encrypted snapshots and bookmarks is required use a non-raw send to backup and restore them. Alternately, they may be removed to resolve the incompatibility."

I like it, though my German (not sure if same rules apply in English) mind would put 2 additional commas in:

```...To correct the issue[,] enable the bookmark_v2 feature...``` and ```If preserving the encrypted snapshots and bookmarks is required[,] use a non-raw send to backup and restore them.```

**Comment by rlaager** [comment]
I agree with adding those commas.

**Comment by JMoVS** [comment]
@rlaager I take your comment as a "go ahead with the new wording and integrate the commas" ;-)

**Comment by JMoVS** [comment]
@rlaager I take that as an "ok go".

@behlendorf I split your text up a bit for the `status_callback` part as it separates status from action. Aside from that splitting still the exact same text.

And I think I finally figured out the new lines and limited it to 80 characters. Still, please test it.

**Comment by JMoVS** [comment]
ha! This time I even got the STYLE test to give me a green check mark! 💪🏼

**Comment by JMoVS** [comment]
You’re welcome;-)
Should I squash it down to a single commit or will you squash and merge it?
