### PR TITLE
fix dsl_scan_ds_clone_swapped logic

### LINKED ISSUE #9140: suspicious code in dsl_scan_ds_clone_swapped, related to sequential scan
Sorry for not following the template.
This _potential_ issue was found through a code review.
The code in question:
```.c
        if (scan_ds_queue_contains(scn, ds1->ds_object, &mintxg)) {
                scan_ds_queue_remove(scn, ds1->ds_object);
                scan_ds_queue_insert(scn, ds2->ds_object, mintxg);
        }
        if (scan_ds_queue_contains(scn, ds2->ds_object, &mintxg)) {
                scan_ds_queue_remove(scn, ds2->ds_object);
                scan_ds_queue_insert(scn, ds1->ds_object, mintxg);
        }
````

I see two potential problems.

If the first condition is true then the second condition will always be true as well.
That's because the first block replaces `ds1->ds_object` with `ds2->ds_object` in the queue.
So, the second block will do a reverse replacement.
I feel that it is unlikely that that is the intended behavior.

Also, I think that it is possible that both `ds1->ds_object` and `ds2->ds_object` may already be on the queue.  If that's the case, then the code will attempt to do a duplicate insertion.

Maybe the code should first check if object IDs are on the queue and remember the results.
Then do necessary removals (if either ID is present, then both should be removed?).
And then do necessary insertions (insert the other ID for each originally present ID).

CC: @tcaputi @ahrens

### PR DESCRIPTION
**Pull request by avg-I**
The was incorrect with respect to swapping dataset IDs both in the
on-disk ZAP object and the in-memory queue.

In both cases, if ds1 was already present, then it would be first
replaced with ds2 and then ds would be replaced back with ds1.
Also, both cases did not properly handle a situation where both ds1 and
ds2 are already queued.  A duplicate insertion would be attempted and
its failure would result in a panic.

This change should fix #9140.

Signed-off-by: Andriy Gapon <avg@FreeBSD.org>

### CODE REVIEW

**Comment by avg-I** [comment]
Note that I was not sure if `mintxg1` and `mintxg2` are required to be equal (as they are for the ZAP).
If that's the case, then the code could be made simpler.

**Comment by avg-I** [comment]
CC @tcaputi

**Comment by tcaputi** [comment]
The first part of the fix (dealing with `scan_ds_queue_contains()`) looks good to me. For the second part, don't we need similar handling for when both the clone and origin are in the zap?

**Comment by avg-I** [comment]
I think that that is completly handled in the first branch. It handles two sub-cases: (a) only ds1 is in the ZAP; (b) both ds1 and ds2 are in the ZAP. So, the second branch needs to deal only with the case where only ds2 is in the ZAP.

**Comment by tcaputi** [comment]
Ah, I see. I think it would be good to break that up similarly to how you did with `scan_ds_queue_contains()`. This way its easy to see that these code paths are doing very similar things.

**Comment by avg-I** [comment]
Okay, I will do that!
Just want to clarify first if mintxg-s can ever be different between the origin and the clone  or if they must always be the same.
Thanks!

**Comment by tcaputi** [comment]
I'm not sure about the mintxgs. I would assume they can be different.

**Comment by avg-I** [comment]
It's just that the code dealing with the ZAP asserts that ds1's mintxg is equal to ds1's and ds2's ds_prev_snap_txg (and ds_prev_snap_txg -s must obviously be equal to each other).
And also the same is asserted for ds2's mintxg.

So, I guessed that mintxg-s recorded in the in-memory queue must obey the same rule.
Maybe @ahrens can help us here.

**Comment by ahrens** [comment]
@avg-I That's right, since we are doing a clone-swap, ds1 and ds2 have the same prev snap, and their `mintxg`s in the on-disk queue (`scn_queue_obj`) should be the same as that prev snap's birth.  I'm not as familiar with the in-memory queue.

File: module/zfs/dsl_scan.c [hunk 1]
```diff
@@ -2184,52 +2184,57 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
...
-		scan_ds_queue_insert(scn, ds2->ds_object, mintxg);
-	}
-	if (scan_ds_queue_contains(scn, ds2->ds_object, &mintxg)) {
+	if (ds2_queued)
 		scan_ds_queue_remove(scn, ds2->ds_object);
-		scan_ds_queue_insert(scn, ds1->ds_object, mintxg);
+	if (ds1_queued)
+		scan_ds_queue_insert(scn, ds2->ds_object, mintxg1);
+	if (ds2_queued)
+		scan_ds_queue_insert(scn, ds1->ds_object, mintxg2);
```
[the remark this answers is not in the document]
Comment (avg-I) [reply module/zfs/dsl_scan.c]: The problem with the suggested approach that if both ds1 and ds2 are already queued then the first block will try to insert a duplicate ds2 and that will cause a panic.

File: module/zfs/dsl_scan.c [hunk 2]
```diff
@@ -2184,52 +2184,57 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
...
+
+	ds1_queued = zap_lookup_int_key(dp->dp_meta_objset,
+	    scn->scn_phys.scn_queue_obj, ds1->ds_object, &mintxg1) == 0;
+	ds2_queued = zap_lookup_int_key(dp->dp_meta_objset,
+	    scn->scn_phys.scn_queue_obj, ds2->ds_object, &mintxg2) == 0;
+
+	/* Sanity checking. */
+	if (ds1_queued) {
```
[the remark this answers is not in the document]
Comment (avg-I) [reply module/zfs/dsl_scan.c]: Okay, I was not completely sure about that.  I will add the checks, then.

File: module/zfs/dsl_scan.c [hunk 3]
```diff
@@ -2184,52 +2184,57 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
 {
```
[the remark this answers is not in the document]
Comment (avg-I) [reply module/zfs/dsl_scan.c]: I agree. But I would prefer to let someone who is more familiar with the code do that.

File: module/zfs/dsl_scan.c [hunk 4]
```diff
@@ -2184,52 +2184,57 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
...
 	}
 
-	if (zap_lookup_int_key(dp->dp_meta_objset, scn->scn_phys.scn_queue_obj,
-	    ds1->ds_object, &mintxg) == 0) {
-		int err;
-		ASSERT3U(mintxg, ==, dsl_dataset_phys(ds1)->ds_prev_snap_txg);
-		ASSERT3U(mintxg, ==, dsl_dataset_phys(ds2)->ds_prev_snap_txg);
-		VERIFY3U(0, ==, zap_remove_int(dp->dp_meta_objset,
+	if (ds1_queued && ds2_queued) {
+		/* Nothing to do if both are queued (or both are not queued). */
```
[the remark this answers is not in the document]
Comment (avg-I) [reply module/zfs/dsl_scan.c]: The only reason I* structured them differently is that I was not sure if mintxg values obey the same rules for both queues. I will change them both to the second form (because of the issue with the first form).

**Comment by behlendorf** [comment]
@tcaputi would you mind reviewing this.

File: module/zfs/dsl_scan.c [hunk 5]
```diff
@@ -2184,52 +2184,75 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
...
+	/* Sanity checking. */
+	if (ds1_queued) {
+		ASSERT3U(mintxg1, ==, dsl_dataset_phys(ds1)->ds_prev_snap_txg);
+		ASSERT3U(mintxg1, ==, dsl_dataset_phys(ds2)->ds_prev_snap_txg);
 	}
-	if (scan_ds_queue_contains(scn, ds2->ds_object, &mintxg)) {
+	if (ds2_queued) {
+		ASSERT3U(mintxg2, ==, dsl_dataset_phys(ds1)->ds_prev_snap_txg);
+		ASSERT3U(mintxg2, ==, dsl_dataset_phys(ds2)->ds_prev_snap_txg);
+	}
```
Comment (tcaputi) [inline module/zfs/dsl_scan.c]: Can you explain the sanity check here (and below?). If both are queued this looks impossible to me unless mintxg1 == mintxg2.

File: module/zfs/dsl_scan.c [hunk 6]
```diff
@@ -2184,52 +2184,75 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
 {
```
Comment (tcaputi) [inline module/zfs/dsl_scan.c]: while we're here can you change the comment above the function to say `origin` instead of `parent`?

File: module/zfs/dsl_scan.c (hunk 5 above)
Comment (ahrens) [reply module/zfs/dsl_scan.c]: ds1 and ds2 have the same `ds_prev` (see assertion in the beginning of `dsl_dataset_clone_swap_sync_impl()`).  So if `mintxgX` is the prev snap txg (as asserted here), then mintxg1==mintxg2.

Comment (avg-I) [reply module/zfs/dsl_scan.c]: Yes, I think that all mintxg-s must be equal and the asserts are implicitly asserting that.

File: module/zfs/dsl_scan.c (hunk 6 above)
Comment (avg-I) [reply module/zfs/dsl_scan.c]: I think that a simple s/parent/origin/ would not produce a good result.
Also, it seems that there is such a term as "clone parent-child dependency relationship", so "parent" is not completely out of place. And an unqualified "origin" seems to mean an origin snapshot.
Anyway, "parent" is more ambiguous than "origin" in this context, so I'll try to improve that comment.

File: module/zfs/dsl_scan.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (avg-I) [reply module/zfs/dsl_scan.c]: @ahrens, I am just not entirely sure if the in-memory and on-disk queues can indeed be different in this respect.
If they can be different, then I need to understand why / how.
I need some help with writing the requested comment.
Maybe @tcaputi could provide it.

File: module/zfs/dsl_scan.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (avg-I) [reply module/zfs/dsl_scan.c]: @ahrens, I am not sure how to fit the requested comment into the new control flow.
I mean that removing "both queued" case would not only result in the duplicate insertion, but it would also result in obviously incorrect logic where we swap just one ds but not the other (because of else-if).
In other words, I am not sure how to word a comment that would explain why the code does not do an obviously wrong thing.

**Comment by avg-I** [comment]
@behlendorf , I can add the comments requested by Matt, but I genuinely cannot understand what they should say. (And in one case why it's needed at all).
So, if someone else can write them or can help me write them, then I can add them.

File: module/zfs/dsl_scan.c [hunk 7]
```diff
@@ -2184,52 +2184,75 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
...
+		ASSERT3U(mintxg1, ==, dsl_dataset_phys(ds2)->ds_prev_snap_txg);
 	}
-	if (scan_ds_queue_contains(scn, ds2->ds_object, &mintxg)) {
+	if (ds2_queued) {
+		ASSERT3U(mintxg2, ==, dsl_dataset_phys(ds1)->ds_prev_snap_txg);
+		ASSERT3U(mintxg2, ==, dsl_dataset_phys(ds2)->ds_prev_snap_txg);
+	}
+
+	if (ds1_queued && ds2_queued) {
+		/* Nothing to do if both are queued (or both are not queued). */
```
Comment (ahrens) [inline module/zfs/dsl_scan.c]: How about changing this comment to:
`If both are queued, we don't need to do anything.  The swapping code below would not handle this case correctly, since we can't insert ds2 if it is already there.`

File: module/zfs/dsl_scan.c [hunk 8]
```diff
@@ -2184,52 +2184,75 @@ dsl_scan_ds_clone_swapped(dsl_dataset_t *ds1, dsl_dataset_t *ds2, dmu_tx_t *tx)
...
 	}
 
-	if (zap_lookup_int_key(dp->dp_meta_objset, scn->scn_phys.scn_queue_obj,
-	    ds1->ds_object, &mintxg) == 0) {
-		int err;
-		ASSERT3U(mintxg, ==, dsl_dataset_phys(ds1)->ds_prev_snap_txg);
-		ASSERT3U(mintxg, ==, dsl_dataset_phys(ds2)->ds_prev_snap_txg);
-		VERIFY3U(0, ==, zap_remove_int(dp->dp_meta_objset,
+	/*
+	 * Handle the on-disk scan queue.
```
Comment (ahrens) [inline module/zfs/dsl_scan.c]: How about adding this to the comment:
`The on-disk state is an out-of-date version of the in-memory state, so the in-memory and on-disk values for `ds1_queued` and `ds2_queued` may be different.  Therefore we need to apply the swap logic to the on-disk state independently of the in-memory state.`

File: module/zfs/dsl_scan.c (hunk 7 above)
Comment (avg-I) [reply module/zfs/dsl_scan.c]: Thank you for the suggestion! I will take it.
At the same time it's not the only problem with the hypothetical alternative mentioned in the comment. It would attempt to replace ds1 with ds2 but not in the opposite direction because of `else if`. And without the `else if` there would be another problem: replacing ds1 with ds2 and then ds2 back with ds1.
So, in my opinion, even if the queue silently ignored duplicate inserts, it would be very hard (if possible) to handle the case where both ds1 and ds2 are queued without explicitly handling that case in one way or another.
E.g., the proposed code shows one way; the existing code for the on-disk queue shows another: having the enqueue operation return an error code, checking for an error, and if the error is EEXIST, then backing out the original removal. Which is more work than just doing nothing in the first place.

File: module/zfs/dsl_scan.c (hunk 8 above)
Comment (avg-I) [reply module/zfs/dsl_scan.c]: Thank you!
