### PR TITLE
zio_decompress_data always ASSERTs successful decompression

### LINKED ISSUE #9612: zio_decompress_data always ASSERTs successful decompression
### Describe the problem you're observing
zdb_read_block with the 'd' flag tries all the compression algorithms and some are expected to fail.  So the ASSERT is triggered by zdb_read_block when it shouldn't be.

### Describe how to reproduce the problem
\# zdb -R tank 0:2a856400:600:id
Found vdev: /root/file1
Trying 00600 -> 00800 (inherit)
ret == 0 (0x16 == 0)
ASSERT at ../../module/zfs/zio_compress.c:162:zio_decompress_data()
\#

Create an interface which zdb can call to decompress the data and avoid the ASSERT.

### PR DESCRIPTION
**Pull request by PaulZ-98**
zio_decompress_data affects zdb by always ASSERTing successful decompression

This interferes with zdb_read_block trying all the decompression algoirithms when the 'd' flag is specified, as some are expected to fail.  Also control the output when guessing algorithms, try the more common compression types first, allow specifying lsize/psize, and fix an uninitialized variable.

Signed-off-by: Paul Zuchowski <pzuchowski@datto.com>
Fixes #9612

### Motivation and Context
Improve the behavior of zdb -R with the 'd' flag for decompression.  As noted above, not all the use cases are working.

### Description
Remove the ASSERT.  Control the output when guessing algorithms by adding a 'v' verbose flag.
Try the more common compression types first.
Allow specifying lsize/psize to limit the upper range of the decompressed size when guessing.  (You can copy and paste lsize/psize from the block pointer output.). Examples:
```
zdb -eR tank 0:2e0004992000:4000L/1000P:d
zdb -eR tank 0:2e0004992000:4000/1000:d
zdb -eR tank 0:2e0004992000:1000:d
```
Fix an uninitialized variable dmu_objset_stats_t dds in dump_objset() which results in random false positive for inconsistent dataset in zdb output.
Eliminate the 'p' flag for -R since it is never used.
Man page changes.

### How Has This Been Tested?
Manually, and created a zfs test for the decompression features.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: cmd/zdb/zdb.c [hunk 1]
```diff
@@ -6529,45 +6551,50 @@ zdb_read_block(char *thing, spa_t *spa)
...
 			(void) printf("Decompress of %s failed\n", thing);
 			goto out;
 		}
 		buf = lbuf;
-		size = lsize;
+		if (*cfuncp == ZIO_COMPRESS_ZLE) {
+			printf("\nZLE decompression was selected. ");
+			printf("If you suspect\n");
+			printf("the results are wrong, try avoiding ZLE by\n");
+			printf("setting and exporting ZDB_NO_ZLE=\"true\"\n\n");
```
Comment (behlendorf) [inline cmd/zdb/zdb.c]: nit: can you use a single `printf()` call for this.  For example:

```
                        printf("\nZLE decompression was selected. If you "
                            "suspect the results are wrong,\ntry avoiding ZLE "
                            "by setting and exporting ZDB_NO_ZLE=\"true\"\n");
```

File: cmd/zdb/zdb.c [hunk 2]
```diff
@@ -6529,45 +6551,50 @@ zdb_read_block(char *thing, spa_t *spa)
...
+		}
+
```
Comment (behlendorf) [inline cmd/zdb/zdb.c]: nit: extra new line

File: cmd/zdb/zdb.c [hunk 3]
```diff
@@ -6345,8 +6364,8 @@ zdb_vdev_lookup(vdev_t *vdev, const char *path)
  *		 e: Byteswap data before dumping
  *		 g: Display data as a gang block header
  *		 i: Display as an indirect block
- *		 p: Do I/O to physical offset
```
Comment (behlendorf) [inline cmd/zdb/zdb.c]: `ZDB_FLAG_PHYS` was removed because it was never implemented, correct?

File: module/zfs/zio_compress.c [hunk 4]
```diff
@@ -147,12 +147,20 @@ zio_decompress_data_buf(enum zio_compress c, void *src, void *dst,
...
 	int ret = zio_decompress_data_buf(c, tmp, dst, s_len, d_len);
 	abd_return_buf(src, tmp, s_len);
+	return (ret);
+}
+
+int
+zio_decompress_data(enum zio_compress c, abd_t *src, void *dst,
+    size_t s_len, size_t d_len)
+{
+	int ret = zio_decompress_data_impl(c, src, dst, s_len, d_len);
```
Comment (behlendorf) [inline module/zfs/zio_compress.c]: Perhaps we should instead remove the `ASSERT0` and update the comment to explain that decompression should never fail but the error is handled regardless.  We do want to handle this case as gracefully as possible even if it shouldn't occur.

**Comment by ikozhukhov** [comment]
mossed previous update with `zdb_checksum.ksh` ?

**Comment by PaulZ-98** [comment]
I will rebase making sure to pick up the most recent zdb related changes, and update the description above to reflect what we decided to do.

File: tests/zfs-tests/tests/functional/cli_root/zdb/zdb_decompress.ksh [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+default_mirror_setup_noexit $DISKS
+log_must zfs set recordsize=$blksize $TESTPOOL/$TESTFS
+log_must zfs set compression=lzjb $TESTPOOL/$TESTFS
+
+# 16 chars 256 times = 4k = block size
+typeset one_k=""
+for i in {1..$write_count}
+do
+	four_k=$one_k$pattern
+done
```
Comment (freqlabs) [inline tests/zfs-tests/tests/functional/cli_root/zdb/zdb_decompress.ksh]: It looks like both occurrences of `one_k` should be `four_k` here.

**Comment by ikozhukhov** [comment]
give me please 1-2 days on testing. if it is critical, you can merge it and i'll report tests/review results later.

**Comment by PaulZ-98** [comment]
Later today I will be addressing the test procedure issue that @freqlabs pointed out.

**Comment by ikozhukhov** [comment]
```
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_001_neg.ksh (run as root) [03:54] [PASS]
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_002_pos.ksh (run as root) [00:28] [PASS]
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_003_pos.ksh (run as root) [00:15] [PASS]
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_004_pos.ksh (run as root) [00:15] [PASS]
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_005_pos.ksh (run as root) [00:22] [PASS]
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_006_pos.ksh (run as root) [01:15] [PASS]
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_checksum.ksh (run as root) [00:18] [PASS]
Test: /opt/zfs-tests/tests/functional/cli_root/zdb/zdb_decompress.ksh (run as root) [00:59] [PASS]

Results Summary
PASS       8

Running Time:   00:07:50
Percent passed: 100.0%
Log directory:  /var/tmp/test_results/20191211T222800
```

**Comment by PaulZ-98** [comment]
Thanks for checking @ikozhukhov
