### PR TITLE
Handle compressed buffers in __dbuf_hold_impl()

### LINKED ISSUE #5742: BUG: unable to handle kernel paging request at ffffc90029404000
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04
Linux Kernel                 | 4.4.0-31-generic
Architecture                 | x86_64
ZFS Version                  | 0.7.0-rc3
SPL Version                  | 0.7.0-rc3

### Describe the problem you're observing
Saved a pool with the same version (fully upgraded pool) ```zfs send -R -D -e -v rpool@beforesend```.
When I want to recv it back I get the following BUG
### Describe how to reproduce the problem
zfs upgrade with 0.7.0-rc3
zfs send -R -D -e -v &lt;pool&gt;@&lt;snap&gt;
zfs revc -v -s -F &lt;pool&gt;

### Include any warning/errors/backtraces from the system logs
```
Feb  5 10:20:43 ubuntu kernel: [ 2953.988382] ZFS: Loaded module v0.7.0-rc3_72_g298ec40, ZFS pool version 5000, ZFS filesystem version 5
Feb  5 10:20:43 ubuntu kernel: [ 2954.846751] ZPIOS: Loaded module v0.7.0-rc3_72_g298ec40
Feb  5 10:21:43 ubuntu kernel: [ 3014.796064] SPL: using hostid 0x007f0101
Feb  5 10:23:43 ubuntu kernel: [ 3134.134301] BUG: unable to handle kernel paging request at ffffc90029404000
Feb  5 10:23:43 ubuntu kernel: [ 3134.134330] IP: [<ffffffff813ff224>] __memmove+0x24/0x1a0
Feb  5 10:23:43 ubuntu kernel: [ 3134.134342] PGD 2250a1067 PUD 2250a2067 PMD 15c02e067 PTE 0
Feb  5 10:23:43 ubuntu kernel: [ 3134.134354] Oops: 0000 [#1] SMP 
Feb  5 10:23:43 ubuntu kernel: [ 3134.134361] Modules linked in: zpios(OE) zfs(POE) zcommon(POE) zavl(POE) icp(POE) znvpair(POE) zunicode(POE) splat(OE) spl(OE) binfmt_misc ctr ccm drbg ansi_cprng dm_crypt algif_skcipher af_alg rfcomm bnep snd_hda_codec_hdmi arc4 intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp iwldvm kvm_intel dell_wmi sparse_keymap mac80211 kvm dell_laptop dcdbas irqbypass dell_smm_hwmon crct10dif_pclmul crc32_pclmul aesni_intel btusb btrtl snd_hda_codec_idt btbcm btintel snd_hda_codec_generic bluetooth aes_x86_64 lrw iwlwifi gf128mul snd_hda_intel glue_helper ablk_helper snd_hda_codec joydev input_leds snd_seq_midi snd_seq_midi_event cfg80211 snd_hda_core cryptd serio_raw snd_hwdep snd_rawmidi snd_pcm lpc_ich snd_seq snd_seq_device snd_timer mei_me mei snd 8250_fintek soundcore shpchp mac_hid dell_smo8800 dell_rbtn parport_pc ppdev lp parport autofs4 overlay nls_utf8 isofs nls_iso8859_1 dm_mirror dm_region_hash dm_log uas usb_storage nouveau ahci mxm_wmi libahci i2c_algo_bit ttm drm_kms_helper syscopyarea sysfillrect psmouse sysimgblt fb_sys_fops e1000e drm ptp wmi pps_core video fjes [last unloaded: spl]
Feb  5 10:23:43 ubuntu kernel: [ 3134.134611] CPU: 6 PID: 25398 Comm: receive_writer Tainted: P           OE   4.4.0-31-generic #50-Ubuntu
Feb  5 10:23:43 ubuntu kernel: [ 3134.134620] Hardware name: Dell Inc. Latitude E6530/0GMVN7, BIOS A17 08/19/2015
Feb  5 10:23:43 ubuntu kernel: [ 3134.134626] task: ffff8801fd97b700 ti: ffff88007f130000 task.ti: ffff88007f130000
Feb  5 10:23:43 ubuntu kernel: [ 3134.134635] RIP: 0010:[<ffffffff813ff224>]  [<ffffffff813ff224>] __memmove+0x24/0x1a0
Feb  5 10:23:43 ubuntu kernel: [ 3134.134644] RSP: 0018:ffff88007f133cc8  EFLAGS: 00010206
Feb  5 10:23:43 ubuntu kernel: [ 3134.134650] RAX: ffffc90014a3f000 RBX: ffff88005cdf5800 RCX: 0000000000015000
Feb  5 10:23:43 ubuntu kernel: [ 3134.134656] RDX: 0000000000020000 RSI: ffffc90029404000 RDI: ffffc90014a4a000
Feb  5 10:23:43 ubuntu kernel: [ 3134.134662] RBP: ffff88007f133d00 R08: 0000000000000001 R09: 00000000090f5000
Feb  5 10:23:43 ubuntu kernel: [ 3134.134668] R10: ffff88011e2dd080 R11: ffffffff81ccf1ea R12: ffffffffc0c89090
Feb  5 10:23:43 ubuntu kernel: [ 3134.134674] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Feb  5 10:23:43 ubuntu kernel: [ 3134.134680] FS:  0000000000000000(0000) GS:ffff88022dd80000(0000) knlGS:0000000000000000
Feb  5 10:23:43 ubuntu kernel: [ 3134.134687] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Feb  5 10:23:43 ubuntu kernel: [ 3134.134692] CR2: ffffc90029404000 CR3: 00000001e339f000 CR4: 00000000001406e0
Feb  5 10:23:43 ubuntu kernel: [ 3134.134699] Stack:
Feb  5 10:23:43 ubuntu kernel: [ 3134.134702]  ffffffffc0b65db5 0000000000000000 000000027f133ce8 ffff88005cdf5800
Feb  5 10:23:43 ubuntu kernel: [ 3134.134714]  ffffffffc0c89090 0000000000000000 0000000000000000 ffff88007f133d48
Feb  5 10:23:43 ubuntu kernel: [ 3134.134726]  ffffffffc0b66118 ffff88011d3ff1c0 00000000f912e000 ffff88007f133e30
Feb  5 10:23:43 ubuntu kernel: [ 3134.134738] Call Trace:
Feb  5 10:23:43 ubuntu kernel: [ 3134.134803]  [<ffffffffc0b65db5>] ? __dbuf_hold_impl+0x2d5/0x590 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.134827]  [<ffffffffc0b66118>] dbuf_hold_impl+0xa8/0xd0 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.134851]  [<ffffffffc0b67676>] dbuf_hold+0x36/0x60 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.134876]  [<ffffffffc0b6eea5>] dmu_buf_hold_noread+0x85/0xe0 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.134904]  [<ffffffffc0b6ef2f>] dmu_buf_hold+0x2f/0x80 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.134930]  [<ffffffffc0b79d25>] receive_writer_thread+0x425/0x6f0 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.134963]  [<ffffffffc0b79905>] ? receive_writer_thread+0x5/0x6f0 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.135001]  [<ffffffffc0b79900>] ? receive_freeobjects.isra.12+0xe0/0xe0 [zfs]
Feb  5 10:23:43 ubuntu kernel: [ 3134.135031]  [<ffffffffc07d74f1>] thread_generic_wrapper+0x71/0x80 [spl]
Feb  5 10:23:43 ubuntu kernel: [ 3134.135046]  [<ffffffffc07d7480>] ? __thread_exit+0x20/0x20 [spl]
Feb  5 10:23:43 ubuntu kernel: [ 3134.135059]  [<ffffffff810a0808>] kthread+0xd8/0xf0
Feb  5 10:23:43 ubuntu kernel: [ 3134.135066]  [<ffffffff810a0730>] ? kthread_create_on_node+0x1e0/0x1e0
Feb  5 10:23:43 ubuntu kernel: [ 3134.135075]  [<ffffffff8182decf>] ret_from_fork+0x3f/0x70
Feb  5 10:23:43 ubuntu kernel: [ 3134.135081]  [<ffffffff810a0730>] ? kthread_create_on_node+0x1e0/0x1e0
Feb  5 10:23:43 ubuntu kernel: [ 3134.135087] Code: 88 0c 17 88 0f c3 90 48 89 f8 48 83 fa 20 0f 82 03 01 00 00 48 39 fe 7d 0f 49 89 f0 49 01 d0 49 39 f8 0f 8f 9f 00 00 00 48 89 d1 <f3> a4 c3 48 81 fa a8 02 00 00 72 05 40 38 fe 74 3b 48 83 ea 20 
Feb  5 10:23:43 ubuntu kernel: [ 3134.135204] RIP  [<ffffffff813ff224>] __memmove+0x24/0x1a0
Feb  5 10:23:43 ubuntu kernel: [ 3134.135212]  RSP <ffff88007f133cc8>
Feb  5 10:23:43 ubuntu kernel: [ 3134.135216] CR2: ffffc90029404000
Feb  5 10:23:43 ubuntu kernel: [ 3134.144797] ---[ end trace 58627849f4392b17 ]---
```

### PR DESCRIPTION
**Pull request by dweeezil**
### Description

In __dbuf_hold_impl(), if a buffer is currently syncing and is still
referenced from db_data, a copy is made in case it is dirtied again in
the txg.  Previously, the buffer for the copy was simply allocated with
arc_alloc_buf() which doesn't handle compressed or encrypted buffers
(which are a special case of a compressed buffer).  The result was
typically an invalid memory access because the newly-allocated buffer
was of the uncompressed size.

This commit fixes the problem by handling the 2 compressed cases,
encrypted and unencrypted, respectively, with arc_alloc_raw_buf() and
arc_alloc_compressed_buf().

Although using the proper allocation functions fixes the invalid memory
access by allocating a buffer of the compressed size, another unrelated
issue made it impossible to properly detect compressed buffers in the
first place.  The header's compression flag was set to ZIO_COMPRESS_OFF
in arc_write() when it was possible that an attached buffer was actually
compressed.  This commit adds logic to only set ZIO_COMPRESS_OFF in
the non-ZIO_RAW case which wil handle both cases of compressed buffers
(encrypted or unencrypted).

### Motivation and Context
Fixes #5742 and possibly other yet-undetected cases.

### How Has This Been Tested?

A compressed deduped send stream which previously caused the system to panic was used as the test for this patch.  The fix to ```__dbuf_hold_impl()``` fixes the out-of-bound memory access and the fix to ```arc_write()``` causes received dataset to properly match the original dataset.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by gmelikov** [comment]
I think it would be great to add the test for this case in zfs-tests.

**Comment by dinatale2** [comment]
@dweeezil I agree with @gmelikov. If possible, please add a test case for this to the test suite. Even if it's for only this specific case, it will set the ground work for others to make similar test cases.

**Comment by dweeezil** [comment]
@dinatale2 and @gmelikov I'm open to ideas as to how to design a test suite component for this.  In this case, I have a 50MB send stream saved in a file which was used for testing.  I suppose the test suite could try to fabricate the send stream but there would be no guarantee that the send stream would actually trigger the bug in the first place.  The bug fixed here is highly timing dependent.  I think at some point, the test suite infrastructure ought to have the ability to fetch a known-triggering send stream from somewhere.  Maybe we could store them in the zfs-images repository?  I'll try to work up a test case script which creates the send stream as I did manually because I think it's the best we can do now.

File: module/zfs/dbuf.c [hunk 1]
```diff
@@ -2784,15 +2789,45 @@ __dbuf_hold_impl(struct dbuf_hold_impl_data *dh)
 	    dh->dh_dn->dn_object != DMU_META_DNODE_OBJECT &&
 	    dh->dh_db->db_state == DB_CACHED && dh->dh_db->db_data_pending) {
 		dh->dh_dr = dh->dh_db->db_data_pending;
-
 		if (dh->dh_dr->dt.dl.dr_data == dh->dh_db->db_buf) {
```
Comment (behlendorf) [inline module/zfs/dbuf.c]: For the sake of readability what do you think about moving the contents of this conditional in to a helper function.  We can declare it `noinline static void` to prevent gcc from inline it and increasing the stack depth.  This should also let you avoid having to add additional member to the `dbuf_hold_impl_data` struct.

Comment (dweeezil) [reply module/zfs/dbuf.c]: Which conditional are you referring to?  In line 2792, both ```dh_dr``` and ```dh_db``` were already in the ```dbuf_hold_impl_data``` struct.  I'm not sure how this could be made more readable versus the rest of the function.

**Comment by dweeezil** [comment]
@behlendorf Regarding a test case, I could give it a try, but as I alluded to in a previous comment, I'm not sure how reliable it would be.  My plan for a test case would be to concoct a test which did something similar to what I did to reproduce this in the first place:
 - Create a pool with dedup and compression enabled on the top-level dataset
 - Create a new dataset in the pool
 - Repeatedly copy ```/usr/bin``` into different directories in the dataset
   - cp -a /usr/bin /tank/ds/bin1
   - cp -a /usr/bin /tank/ds/bin2
   - ... a bunch more times
 - Snapshot the dataset
 - Produce a compressed deduped send stream from the dataset and receive it to a new dataset

Then compare the received dataset against the original dataset.  Using ```/usr/bin``` can be a pain because in most distros the ```/usr/bin``` directory contains a bunch of "wide" symlinks which aren't handled properly by a simple "diff -ur" between the source and the copy.

Also, as I suggested in a previous comment, there's no guarantee that such a send stream would even trigger the bug so the test wouldn't be completely reliable in the first place.

File: module/zfs/dbuf.c (hunk 1 above)
Comment (behlendorf) [reply module/zfs/dbuf.c]: @dweeezil sorry I wasn't very clear.  What I'm suggesting is pulling this entire block out in to a helper function like this, behlendorf/zfs@950e2b1011725978aa8a1ffaed831396a63d191c (untested).  As long as the function is marked `noinline` we should be able to prevent gcc from inlining it and contributing to the stack depth.  Then we can use some local variable to make it more readable.  What do you think?

**Comment by behlendorf** [comment]
I'm ok with relying on manual testing for this one.

File: module/zfs/dbuf.c (hunk 1 above)
Comment (dweeezil) [reply module/zfs/dbuf.c]: @behlendorf OK, that makes sense.  I'll refactor it as you suggest and rerun the tests.  For future regression testing,  maybe we could stash the send stream I'm using (50MiB) in the zfs-images repo or maybe even make a new repo for send streams.

Comment (behlendorf) [reply module/zfs/dbuf.c]: Sure, that would make sense.  Another idea which was floated was to provide a counterpart to `zstreamdump` which would make it easy to generate interesting streams for testing.

**Comment by dweeezil** [comment]
I just re-pushed the branch with @behlendorf's re-factoring and added a comment to the new function.  For the moment, the re-factoring is a separate commit to preserve the original patch.  They can be squashed before merging.

**Comment by behlendorf** [comment]
@dweeezil merged, thanks for getting to the root cause.  Since this issue impacts the 0.7.x releases could you also open a new PR against the zfs-0.7-release branch sans the encryption portion.

**Comment by dweeezil** [comment]
@behlendorf OK, I'll get an 0.7 version made ASAP.
