### PR TITLE
Fixes for SPARC support

### LINKED ISSUE #6733: zfs-0.7.1 won't build on Gentoo Linux/SPARC (kmod builds; userspace tools don't)
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Gentoo Linux
Distribution Version    |  Live
Linux Kernel                 |  Linux hostname 4.9.49-gentoo-r1 #2 SMP Sat Oct 7 04:48:20 CST 2017 sparc64 sun4v UltraSparc T2 (Niagara2) GNU/Linux
Architecture                 |  UltraSPARC T2
ZFS Version                  |  0.7.1-r0-gentoo
SPL Version                  |  0.7.1-r0-gentoo

### Describe the problem you're observing

Build fails with mysterious assembler errors in `zfs-0.7.1/lib/libspl/asm-generic/atomic.c`. The build log is attached below.

### Describe how to reproduce the problem

Build the package on a relevant system.

### Include any warning/errors/backtraces from the system logs

Build log (relevant sections): 

```

Making all in asm-generic
make[4]: Entering directory '/var/tmp/portage/sys-fs/zfs-0.7.1-r1/work/zfs-0.7.1/lib/libspl/asm-generic'
sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../../zfs_config.h -I../../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -fPIC -c -S atomic.c -o atomic.S
make[4]: Leaving directory '/var/tmp/portage/sys-fs/zfs-0.7.1-r1/work/zfs-0.7.1/lib/libspl/asm-generic'
make[4]: Entering directory '/var/tmp/portage/sys-fs/zfs-0.7.1-r1/work/zfs-0.7.1/lib/libspl'
\
#	source='getexecname.c' object='getexecname.lo' libtool=yes 
\
#	source='gethrtime.c' object='gethrtime.lo' libtool=yes 
\
#	source='gethrestime.c' object='gethrestime.lo' libtool=yes 
\
#	source='getmntany.c' object='getmntany.lo' libtool=yes 
\
#	source='list.c' object='list.lo' libtool=yes 
\
#	source='mkdirp.c' object='mkdirp.lo' libtool=yes 
\
#	source='page.c' object='page.lo' libtool=yes 
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o getexecname.lo getexecname.c
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o gethrtime.lo gethrtime.c
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o gethrestime.lo gethrestime.c
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o getmntany.lo getmntany.c
\
#	source='strlcat.c' object='strlcat.lo' libtool=yes 
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o list.lo list.c
\
#	source='strlcpy.c' object='strlcpy.lo' libtool=yes 
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o mkdirp.lo mkdirp.c
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o page.lo page.c
\
#	source='strnlen.c' object='strnlen.lo' libtool=yes 
\
#	source='timestamp.c' object='timestamp.lo' libtool=yes 
\
#	source='zone.c' object='zone.lo' libtool=yes 
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o strlcat.lo strlcat.c
\
#	source='../../lib/libspl/asm-generic/atomic.S' object='atomic.lo' libtool=yes 
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o strlcpy.lo strlcpy.c
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o strnlen.lo strnlen.c
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o timestamp.lo timestamp.c
/bin/sh ../../libtool  --tag=CC --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -DNDEBUG -Wall -Wstrict-prototypes -Wno-unused-but-set-variable -Wno-bool-compare -fno-strict-aliasing -std=gnu99  -Wframe-larger-than=1024 -O2 -mcpu=niagara2 -mtune=niagara2 -pipe -c -o zone.lo zone.c
/bin/sh ../../libtool  --silent  --mode=compile sparc-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -include ../../zfs_config.h -I../../lib/libspl/include  -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAVE_LARGE_STACKS=1 -DTEXT_DOMAIN=\"zfs-linux-user\" -DLIBEXECDIR=\"/usr/libexec\" -DRUNSTATEDIR=\"/var/lib/run\" -DSBINDIR=\"/sbin\" -DSYSCONFDIR=\"/etc\"  -I../../lib/libspl/include  -c -o atomic.lo ../../lib/libspl/asm-generic/atomic.S
atomic.c: Assembler messages:
atomic.c:83: Error: Architecture mismatch on "bne,pn %icc,.L7 ,pn %icc,.L7".
atomic.c:83:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:91: Error: Architecture mismatch on "bne,pn %icc,.L8 ,pn %icc,.L8".
atomic.c:91:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:93: Error: Architecture mismatch on "return %i7+8".
atomic.c:93:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:107: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:107:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:135: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:135:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:141: Error: Architecture mismatch on "ba,pt %xcc,.L5 ,pt %xcc,.L5".
atomic.c:141:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:160: Error: Architecture mismatch on "bne,pn %icc,.L13 ,pn %icc,.L13".
atomic.c:160:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:168: Error: Architecture mismatch on "bne,pn %icc,.L14 ,pn %icc,.L14".
atomic.c:168:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:170: Error: Architecture mismatch on "return %i7+8".
atomic.c:170:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:184: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:184:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:212: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:212:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:218: Error: Architecture mismatch on "ba,pt %xcc,.L12 ,pt %xcc,.L12".
atomic.c:218:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:237: Error: Architecture mismatch on "bne,pn %icc,.L19 ,pn %icc,.L19".
atomic.c:237:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:245: Error: Architecture mismatch on "bne,pn %icc,.L20 ,pn %icc,.L20".
atomic.c:245:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:247: Error: Architecture mismatch on "return %i7+8".
atomic.c:247:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:261: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:261:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:289: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:289:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:295: Error: Architecture mismatch on "ba,pt %xcc,.L18 ,pt %xcc,.L18".
atomic.c:295:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:314: Error: Architecture mismatch on "bne,pn %icc,.L25 ,pn %icc,.L25".
atomic.c:314:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:322: Error: Architecture mismatch on "bne,pn %icc,.L26 ,pn %icc,.L26".
atomic.c:322:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:324: Error: Architecture mismatch on "return %i7+8".
atomic.c:324:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:338: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:338:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:366: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:366:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:372: Error: Architecture mismatch on "ba,pt %xcc,.L24 ,pt %xcc,.L24".
atomic.c:372:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:391: Error: Architecture mismatch on "bne,pn %icc,.L31 ,pn %icc,.L31".
atomic.c:391:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:399: Error: Architecture mismatch on "bne,pn %icc,.L32 ,pn %icc,.L32".
atomic.c:399:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:401: Error: Architecture mismatch on "return %i7+8".
atomic.c:401:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:415: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:415:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:443: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:443:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:449: Error: Architecture mismatch on "ba,pt %xcc,.L30 ,pt %xcc,.L30".
atomic.c:449:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:468: Error: Architecture mismatch on "bne,pn %icc,.L37 ,pn %icc,.L37".
atomic.c:468:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:476: Error: Architecture mismatch on "bne,pn %icc,.L38 ,pn %icc,.L38".
atomic.c:476:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:478: Error: Architecture mismatch on "return %i7+8".
atomic.c:478:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:492: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:492:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:520: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:520:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:526: Error: Architecture mismatch on "ba,pt %xcc,.L36 ,pt %xcc,.L36".
atomic.c:526:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:545: Error: Architecture mismatch on "bne,pn %icc,.L43 ,pn %icc,.L43".
atomic.c:545:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:553: Error: Architecture mismatch on "bne,pn %icc,.L44 ,pn %icc,.L44".
atomic.c:553:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:555: Error: Architecture mismatch on "return %i7+8".
atomic.c:555:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:569: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:569:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:597: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:597:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:603: Error: Architecture mismatch on "ba,pt %xcc,.L42 ,pt %xcc,.L42".
atomic.c:603:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:622: Error: Architecture mismatch on "bne,pn %icc,.L49 ,pn %icc,.L49".
atomic.c:622:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:630: Error: Architecture mismatch on "bne,pn %icc,.L50 ,pn %icc,.L50".
atomic.c:630:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:632: Error: Architecture mismatch on "return %i7+8".
atomic.c:632:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:646: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:646:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:674: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:674:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:680: Error: Architecture mismatch on "ba,pt %xcc,.L48 ,pt %xcc,.L48".
atomic.c:680:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:699: Error: Architecture mismatch on "bne,pn %icc,.L55 ,pn %icc,.L55".
atomic.c:699:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:709: Error: Architecture mismatch on "bne,pn %icc,.L56 ,pn %icc,.L56".
atomic.c:709:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:711: Error: Architecture mismatch on "return %i7+8".
atomic.c:711:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:725: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:725:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:753: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:753:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:759: Error: Architecture mismatch on "ba,pt %xcc,.L54 ,pt %xcc,.L54".
atomic.c:759:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:778: Error: Architecture mismatch on "bne,pn %icc,.L61 ,pn %icc,.L61".
atomic.c:778:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:786: Error: Architecture mismatch on "bne,pn %icc,.L62 ,pn %icc,.L62".
atomic.c:786:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:788: Error: Architecture mismatch on "return %i7+8".
atomic.c:788:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:802: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:802:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:830: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:830:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:836: Error: Architecture mismatch on "ba,pt %xcc,.L60 ,pt %xcc,.L60".
atomic.c:836:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:855: Error: Architecture mismatch on "bne,pn %icc,.L67 ,pn %icc,.L67".
atomic.c:855:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:863: Error: Architecture mismatch on "bne,pn %icc,.L68 ,pn %icc,.L68".
atomic.c:863:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:865: Error: Architecture mismatch on "return %i7+8".
atomic.c:865:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:879: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:879:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:907: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:907:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:913: Error: Architecture mismatch on "ba,pt %xcc,.L66 ,pt %xcc,.L66".
atomic.c:913:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:932: Error: Architecture mismatch on "bne,pn %icc,.L73 ,pn %icc,.L73".
atomic.c:932:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:940: Error: Architecture mismatch on "bne,pn %icc,.L74 ,pn %icc,.L74".
atomic.c:940:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:942: Error: Architecture mismatch on "return %i7+8".
atomic.c:942:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:956: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:956:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:984: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:984:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:990: Error: Architecture mismatch on "ba,pt %xcc,.L72 ,pt %xcc,.L72".
atomic.c:990:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1009: Error: Architecture mismatch on "bne,pn %icc,.L79 ,pn %icc,.L79".
atomic.c:1009:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1017: Error: Architecture mismatch on "bne,pn %icc,.L80 ,pn %icc,.L80".
atomic.c:1017:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1019: Error: Architecture mismatch on "return %i7+8".
atomic.c:1019:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1033: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1033:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1061: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1061:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1067: Error: Architecture mismatch on "ba,pt %xcc,.L78 ,pt %xcc,.L78".
atomic.c:1067:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1086: Error: Architecture mismatch on "bne,pn %icc,.L85 ,pn %icc,.L85".
atomic.c:1086:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1094: Error: Architecture mismatch on "bne,pn %icc,.L86 ,pn %icc,.L86".
atomic.c:1094:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1096: Error: Architecture mismatch on "return %i7+8".
atomic.c:1096:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1110: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1110:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1138: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1138:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1144: Error: Architecture mismatch on "ba,pt %xcc,.L84 ,pt %xcc,.L84".
atomic.c:1144:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1163: Error: Architecture mismatch on "bne,pn %icc,.L91 ,pn %icc,.L91".
atomic.c:1163:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1171: Error: Architecture mismatch on "bne,pn %icc,.L92 ,pn %icc,.L92".
atomic.c:1171:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1173: Error: Architecture mismatch on "return %i7+8".
atomic.c:1173:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1187: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1187:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1215: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1215:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1221: Error: Architecture mismatch on "ba,pt %xcc,.L90 ,pt %xcc,.L90".
atomic.c:1221:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1240: Error: Architecture mismatch on "bne,pn %icc,.L97 ,pn %icc,.L97".
atomic.c:1240:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1248: Error: Architecture mismatch on "bne,pn %icc,.L98 ,pn %icc,.L98".
atomic.c:1248:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1250: Error: Architecture mismatch on "return %i7+8".
atomic.c:1250:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1264: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1264:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1292: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1292:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1298: Error: Architecture mismatch on "ba,pt %xcc,.L96 ,pt %xcc,.L96".
atomic.c:1298:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1317: Error: Architecture mismatch on "bne,pn %icc,.L103 ,pn %icc,.L103".
atomic.c:1317:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1325: Error: Architecture mismatch on "bne,pn %icc,.L104 ,pn %icc,.L104".
atomic.c:1325:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1327: Error: Architecture mismatch on "return %i7+8".
atomic.c:1327:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1341: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1341:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1369: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1369:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1375: Error: Architecture mismatch on "ba,pt %xcc,.L102 ,pt %xcc,.L102".
atomic.c:1375:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1394: Error: Architecture mismatch on "bne,pn %icc,.L109 ,pn %icc,.L109".
atomic.c:1394:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1404: Error: Architecture mismatch on "bne,pn %icc,.L110 ,pn %icc,.L110".
atomic.c:1404:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1406: Error: Architecture mismatch on "return %i7+8".
atomic.c:1406:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1420: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1420:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1448: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1448:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1454: Error: Architecture mismatch on "ba,pt %xcc,.L108 ,pt %xcc,.L108".
atomic.c:1454:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1473: Error: Architecture mismatch on "bne,pn %icc,.L115 ,pn %icc,.L115".
atomic.c:1473:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1481: Error: Architecture mismatch on "bne,pn %icc,.L116 ,pn %icc,.L116".
atomic.c:1481:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1483: Error: Architecture mismatch on "return %i7+8".
atomic.c:1483:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1497: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1497:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1525: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1525:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1531: Error: Architecture mismatch on "ba,pt %xcc,.L114 ,pt %xcc,.L114".
atomic.c:1531:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1550: Error: Architecture mismatch on "bne,pn %icc,.L121 ,pn %icc,.L121".
atomic.c:1550:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1558: Error: Architecture mismatch on "bne,pn %icc,.L122 ,pn %icc,.L122".
atomic.c:1558:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1560: Error: Architecture mismatch on "return %i7+8".
atomic.c:1560:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1574: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1574:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1602: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1602:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1608: Error: Architecture mismatch on "ba,pt %xcc,.L120 ,pt %xcc,.L120".
atomic.c:1608:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1627: Error: Architecture mismatch on "bne,pn %icc,.L127 ,pn %icc,.L127".
atomic.c:1627:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1635: Error: Architecture mismatch on "bne,pn %icc,.L128 ,pn %icc,.L128".
atomic.c:1635:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1637: Error: Architecture mismatch on "return %i7+8".
atomic.c:1637:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1651: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1651:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1679: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1679:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1685: Error: Architecture mismatch on "ba,pt %xcc,.L126 ,pt %xcc,.L126".
atomic.c:1685:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1704: Error: Architecture mismatch on "bne,pn %icc,.L133 ,pn %icc,.L133".
atomic.c:1704:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1712: Error: Architecture mismatch on "bne,pn %icc,.L134 ,pn %icc,.L134".
atomic.c:1712:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1714: Error: Architecture mismatch on "return %i7+8".
atomic.c:1714:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1728: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1728:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1756: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1756:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1762: Error: Architecture mismatch on "ba,pt %xcc,.L132 ,pt %xcc,.L132".
atomic.c:1762:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1781: Error: Architecture mismatch on "bne,pn %icc,.L139 ,pn %icc,.L139".
atomic.c:1781:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1789: Error: Architecture mismatch on "bne,pn %icc,.L140 ,pn %icc,.L140".
atomic.c:1789:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1791: Error: Architecture mismatch on "return %i7+8".
atomic.c:1791:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1805: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1805:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1833: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1833:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1839: Error: Architecture mismatch on "ba,pt %xcc,.L138 ,pt %xcc,.L138".
atomic.c:1839:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1858: Error: Architecture mismatch on "bne,pn %icc,.L145 ,pn %icc,.L145".
atomic.c:1858:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1866: Error: Architecture mismatch on "bne,pn %icc,.L146 ,pn %icc,.L146".
atomic.c:1866:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1868: Error: Architecture mismatch on "return %i7+8".
atomic.c:1868:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1882: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1882:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1910: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1910:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1916: Error: Architecture mismatch on "ba,pt %xcc,.L144 ,pt %xcc,.L144".
atomic.c:1916:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1935: Error: Architecture mismatch on "bne,pn %icc,.L151 ,pn %icc,.L151".
atomic.c:1935:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1943: Error: Architecture mismatch on "bne,pn %icc,.L152 ,pn %icc,.L152".
atomic.c:1943:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1945: Error: Architecture mismatch on "return %i7+8".
atomic.c:1945:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1959: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1959:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1987: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:1987:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:1993: Error: Architecture mismatch on "ba,pt %xcc,.L150 ,pt %xcc,.L150".
atomic.c:1993:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2012: Error: Architecture mismatch on "bne,pn %icc,.L157 ,pn %icc,.L157".
atomic.c:2012:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2022: Error: Architecture mismatch on "bne,pn %icc,.L158 ,pn %icc,.L158".
atomic.c:2022:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2024: Error: Architecture mismatch on "return %i7+8".
atomic.c:2024:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2038: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2038:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2066: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2066:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2072: Error: Architecture mismatch on "ba,pt %xcc,.L156 ,pt %xcc,.L156".
atomic.c:2072:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2091: Error: Architecture mismatch on "bne,a,pn %icc,.L162 ,a,pn %icc,.L162".
atomic.c:2091:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2092: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2092:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2099: Error: Architecture mismatch on "bne,a,pn %icc,.L163 ,a,pn %icc,.L163".
atomic.c:2099:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2100: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2100:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2101: Error: Architecture mismatch on "return %i7+8".
atomic.c:2101:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2181: Error: Architecture mismatch on "bne,pn %icc,.L168 ,pn %icc,.L168".
atomic.c:2181:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2189: Error: Architecture mismatch on "bne,pn %icc,.L169 ,pn %icc,.L169".
atomic.c:2189:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2191: Error: Architecture mismatch on "return %i7+8".
atomic.c:2191:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2205: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2205:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2233: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2233:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2239: Error: Architecture mismatch on "ba,pt %xcc,.L167 ,pt %xcc,.L167".
atomic.c:2239:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2258: Error: Architecture mismatch on "bne,pn %icc,.L174 ,pn %icc,.L174".
atomic.c:2258:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2266: Error: Architecture mismatch on "bne,pn %icc,.L175 ,pn %icc,.L175".
atomic.c:2266:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2268: Error: Architecture mismatch on "return %i7+8".
atomic.c:2268:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2282: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2282:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2310: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2310:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2316: Error: Architecture mismatch on "ba,pt %xcc,.L173 ,pt %xcc,.L173".
atomic.c:2316:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2335: Error: Architecture mismatch on "bne,pn %icc,.L180 ,pn %icc,.L180".
atomic.c:2335:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2343: Error: Architecture mismatch on "bne,pn %icc,.L181 ,pn %icc,.L181".
atomic.c:2343:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2345: Error: Architecture mismatch on "return %i7+8".
atomic.c:2345:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2359: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2359:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2387: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2387:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2393: Error: Architecture mismatch on "ba,pt %xcc,.L179 ,pt %xcc,.L179".
atomic.c:2393:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2412: Error: Architecture mismatch on "bne,pn %icc,.L186 ,pn %icc,.L186".
atomic.c:2412:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2420: Error: Architecture mismatch on "bne,pn %icc,.L187 ,pn %icc,.L187".
atomic.c:2420:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2422: Error: Architecture mismatch on "return %i7+8".
atomic.c:2422:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2436: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2436:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2464: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2464:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2470: Error: Architecture mismatch on "ba,pt %xcc,.L185 ,pt %xcc,.L185".
atomic.c:2470:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2489: Error: Architecture mismatch on "bne,pn %icc,.L192 ,pn %icc,.L192".
atomic.c:2489:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2497: Error: Architecture mismatch on "bne,pn %icc,.L193 ,pn %icc,.L193".
atomic.c:2497:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2499: Error: Architecture mismatch on "return %i7+8".
atomic.c:2499:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2513: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2513:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2541: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2541:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2547: Error: Architecture mismatch on "ba,pt %xcc,.L191 ,pt %xcc,.L191".
atomic.c:2547:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2566: Error: Architecture mismatch on "bne,pn %icc,.L198 ,pn %icc,.L198".
atomic.c:2566:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2574: Error: Architecture mismatch on "bne,pn %icc,.L199 ,pn %icc,.L199".
atomic.c:2574:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2576: Error: Architecture mismatch on "return %i7+8".
atomic.c:2576:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2590: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2590:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2618: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2618:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2624: Error: Architecture mismatch on "ba,pt %xcc,.L197 ,pt %xcc,.L197".
atomic.c:2624:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2643: Error: Architecture mismatch on "bne,pn %icc,.L204 ,pn %icc,.L204".
atomic.c:2643:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2651: Error: Architecture mismatch on "bne,pn %icc,.L205 ,pn %icc,.L205".
atomic.c:2651:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2653: Error: Architecture mismatch on "return %i7+8".
atomic.c:2653:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2667: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2667:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2695: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2695:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2701: Error: Architecture mismatch on "ba,pt %xcc,.L203 ,pt %xcc,.L203".
atomic.c:2701:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2720: Error: Architecture mismatch on "bne,pn %icc,.L210 ,pn %icc,.L210".
atomic.c:2720:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2730: Error: Architecture mismatch on "bne,pn %icc,.L211 ,pn %icc,.L211".
atomic.c:2730:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2732: Error: Architecture mismatch on "return %i7+8".
atomic.c:2732:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2746: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2746:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2774: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2774:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2780: Error: Architecture mismatch on "ba,pt %xcc,.L209 ,pt %xcc,.L209".
atomic.c:2780:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2799: Error: Architecture mismatch on "bne,a,pn %icc,.L215 ,a,pn %icc,.L215".
atomic.c:2799:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2800: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2800:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2807: Error: Architecture mismatch on "bne,a,pn %icc,.L216 ,a,pn %icc,.L216".
atomic.c:2807:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2808: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2808:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2809: Error: Architecture mismatch on "return %i7+8".
atomic.c:2809:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2889: Error: Architecture mismatch on "bne,pn %icc,.L221 ,pn %icc,.L221".
atomic.c:2889:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2897: Error: Architecture mismatch on "bne,pn %icc,.L222 ,pn %icc,.L222".
atomic.c:2897:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2899: Error: Architecture mismatch on "return %i7+8".
atomic.c:2899:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2913: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2913:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2941: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2941:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2947: Error: Architecture mismatch on "ba,pt %xcc,.L220 ,pt %xcc,.L220".
atomic.c:2947:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2966: Error: Architecture mismatch on "bne,pn %icc,.L227 ,pn %icc,.L227".
atomic.c:2966:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2974: Error: Architecture mismatch on "bne,pn %icc,.L228 ,pn %icc,.L228".
atomic.c:2974:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2976: Error: Architecture mismatch on "return %i7+8".
atomic.c:2976:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:2990: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:2990:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3018: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3018:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3024: Error: Architecture mismatch on "ba,pt %xcc,.L226 ,pt %xcc,.L226".
atomic.c:3024:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3043: Error: Architecture mismatch on "bne,pn %icc,.L233 ,pn %icc,.L233".
atomic.c:3043:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3051: Error: Architecture mismatch on "bne,pn %icc,.L234 ,pn %icc,.L234".
atomic.c:3051:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3053: Error: Architecture mismatch on "return %i7+8".
atomic.c:3053:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3067: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3067:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3095: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3095:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3101: Error: Architecture mismatch on "ba,pt %xcc,.L232 ,pt %xcc,.L232".
atomic.c:3101:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3120: Error: Architecture mismatch on "bne,pn %icc,.L239 ,pn %icc,.L239".
atomic.c:3120:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3128: Error: Architecture mismatch on "bne,pn %icc,.L240 ,pn %icc,.L240".
atomic.c:3128:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3130: Error: Architecture mismatch on "return %i7+8".
atomic.c:3130:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3144: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3144:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3172: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3172:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3178: Error: Architecture mismatch on "ba,pt %xcc,.L238 ,pt %xcc,.L238".
atomic.c:3178:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3197: Error: Architecture mismatch on "bne,pn %icc,.L245 ,pn %icc,.L245".
atomic.c:3197:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3205: Error: Architecture mismatch on "bne,pn %icc,.L246 ,pn %icc,.L246".
atomic.c:3205:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3207: Error: Architecture mismatch on "return %i7+8".
atomic.c:3207:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3221: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3221:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3249: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3249:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3255: Error: Architecture mismatch on "ba,pt %xcc,.L244 ,pt %xcc,.L244".
atomic.c:3255:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3274: Error: Architecture mismatch on "bne,pn %icc,.L251 ,pn %icc,.L251".
atomic.c:3274:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3282: Error: Architecture mismatch on "bne,pn %icc,.L252 ,pn %icc,.L252".
atomic.c:3282:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3284: Error: Architecture mismatch on "return %i7+8".
atomic.c:3284:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3298: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3298:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3326: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3326:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3332: Error: Architecture mismatch on "ba,pt %xcc,.L250 ,pt %xcc,.L250".
atomic.c:3332:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3351: Error: Architecture mismatch on "bne,pn %icc,.L257 ,pn %icc,.L257".
atomic.c:3351:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3359: Error: Architecture mismatch on "bne,pn %icc,.L258 ,pn %icc,.L258".
atomic.c:3359:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3361: Error: Architecture mismatch on "return %i7+8".
atomic.c:3361:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3375: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3375:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3403: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3403:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3409: Error: Architecture mismatch on "ba,pt %xcc,.L256 ,pt %xcc,.L256".
atomic.c:3409:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3428: Error: Architecture mismatch on "bne,pn %icc,.L263 ,pn %icc,.L263".
atomic.c:3428:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3437: Error: Architecture mismatch on "bne,pn %icc,.L264 ,pn %icc,.L264".
atomic.c:3437:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3439: Error: Architecture mismatch on "return %i7+8".
atomic.c:3439:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3453: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3453:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3481: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3481:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3487: Error: Architecture mismatch on "ba,pt %xcc,.L262 ,pt %xcc,.L262".
atomic.c:3487:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3506: Error: Architecture mismatch on "bne,pn %icc,.L269 ,pn %icc,.L269".
atomic.c:3506:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3514: Error: Architecture mismatch on "bne,pn %icc,.L270 ,pn %icc,.L270".
atomic.c:3514:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3516: Error: Architecture mismatch on "return %i7+8".
atomic.c:3516:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3530: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3530:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3558: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3558:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3564: Error: Architecture mismatch on "ba,pt %xcc,.L268 ,pt %xcc,.L268".
atomic.c:3564:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3583: Error: Architecture mismatch on "bne,pn %icc,.L275 ,pn %icc,.L275".
atomic.c:3583:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3591: Error: Architecture mismatch on "bne,pn %icc,.L276 ,pn %icc,.L276".
atomic.c:3591:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3593: Error: Architecture mismatch on "return %i7+8".
atomic.c:3593:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3607: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3607:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3635: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3635:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3641: Error: Architecture mismatch on "ba,pt %xcc,.L274 ,pt %xcc,.L274".
atomic.c:3641:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3660: Error: Architecture mismatch on "bne,pn %icc,.L281 ,pn %icc,.L281".
atomic.c:3660:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3668: Error: Architecture mismatch on "bne,pn %icc,.L282 ,pn %icc,.L282".
atomic.c:3668:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3670: Error: Architecture mismatch on "return %i7+8".
atomic.c:3670:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3684: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3684:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3712: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3712:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3718: Error: Architecture mismatch on "ba,pt %xcc,.L280 ,pt %xcc,.L280".
atomic.c:3718:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3737: Error: Architecture mismatch on "bne,pn %icc,.L287 ,pn %icc,.L287".
atomic.c:3737:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3745: Error: Architecture mismatch on "bne,pn %icc,.L288 ,pn %icc,.L288".
atomic.c:3745:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3747: Error: Architecture mismatch on "return %i7+8".
atomic.c:3747:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3761: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3761:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3789: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3789:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3795: Error: Architecture mismatch on "ba,pt %xcc,.L286 ,pt %xcc,.L286".
atomic.c:3795:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3814: Error: Architecture mismatch on "bne,pn %icc,.L293 ,pn %icc,.L293".
atomic.c:3814:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3822: Error: Architecture mismatch on "bne,pn %icc,.L294 ,pn %icc,.L294".
atomic.c:3822:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3824: Error: Architecture mismatch on "return %i7+8".
atomic.c:3824:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3838: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3838:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3866: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3866:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3872: Error: Architecture mismatch on "ba,pt %xcc,.L292 ,pt %xcc,.L292".
atomic.c:3872:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3891: Error: Architecture mismatch on "bne,pn %icc,.L299 ,pn %icc,.L299".
atomic.c:3891:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3899: Error: Architecture mismatch on "bne,pn %icc,.L300 ,pn %icc,.L300".
atomic.c:3899:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3901: Error: Architecture mismatch on "return %i7+8".
atomic.c:3901:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3915: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3915:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3943: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3943:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3949: Error: Architecture mismatch on "ba,pt %xcc,.L298 ,pt %xcc,.L298".
atomic.c:3949:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3968: Error: Architecture mismatch on "bne,pn %icc,.L305 ,pn %icc,.L305".
atomic.c:3968:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3976: Error: Architecture mismatch on "bne,pn %icc,.L306 ,pn %icc,.L306".
atomic.c:3976:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3978: Error: Architecture mismatch on "return %i7+8".
atomic.c:3978:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:3992: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:3992:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4020: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4020:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4026: Error: Architecture mismatch on "ba,pt %xcc,.L304 ,pt %xcc,.L304".
atomic.c:4026:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4045: Error: Architecture mismatch on "bne,pn %icc,.L311 ,pn %icc,.L311".
atomic.c:4045:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4054: Error: Architecture mismatch on "bne,pn %icc,.L312 ,pn %icc,.L312".
atomic.c:4054:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4056: Error: Architecture mismatch on "return %i7+8".
atomic.c:4056:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4070: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4070:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4098: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4098:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4104: Error: Architecture mismatch on "ba,pt %xcc,.L310 ,pt %xcc,.L310".
atomic.c:4104:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4123: Error: Architecture mismatch on "bne,pn %icc,.L317 ,pn %icc,.L317".
atomic.c:4123:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4131: Error: Architecture mismatch on "bne,pn %icc,.L318 ,pn %icc,.L318".
atomic.c:4131:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4133: Error: Architecture mismatch on "return %i7+8".
atomic.c:4133:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4147: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4147:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4176: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4176:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4182: Error: Architecture mismatch on "ba,pt %xcc,.L316 ,pt %xcc,.L316".
atomic.c:4182:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4201: Error: Architecture mismatch on "bne,pn %icc,.L323 ,pn %icc,.L323".
atomic.c:4201:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4209: Error: Architecture mismatch on "bne,pn %icc,.L324 ,pn %icc,.L324".
atomic.c:4209:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4211: Error: Architecture mismatch on "return %i7+8".
atomic.c:4211:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4225: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4225:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4254: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4254:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4260: Error: Architecture mismatch on "ba,pt %xcc,.L322 ,pt %xcc,.L322".
atomic.c:4260:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4279: Error: Architecture mismatch on "bne,pn %icc,.L329 ,pn %icc,.L329".
atomic.c:4279:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4287: Error: Architecture mismatch on "bne,pn %icc,.L330 ,pn %icc,.L330".
atomic.c:4287:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4289: Error: Architecture mismatch on "return %i7+8".
atomic.c:4289:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4303: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4303:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4332: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4332:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4338: Error: Architecture mismatch on "ba,pt %xcc,.L328 ,pt %xcc,.L328".
atomic.c:4338:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4357: Error: Architecture mismatch on "bne,pn %icc,.L335 ,pn %icc,.L335".
atomic.c:4357:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4365: Error: Architecture mismatch on "bne,pn %icc,.L336 ,pn %icc,.L336".
atomic.c:4365:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4367: Error: Architecture mismatch on "return %i7+8".
atomic.c:4367:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4381: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4381:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4410: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4410:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4416: Error: Architecture mismatch on "ba,pt %xcc,.L334 ,pt %xcc,.L334".
atomic.c:4416:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4435: Error: Architecture mismatch on "bne,pn %icc,.L341 ,pn %icc,.L341".
atomic.c:4435:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4443: Error: Architecture mismatch on "bne,pn %icc,.L342 ,pn %icc,.L342".
atomic.c:4443:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4445: Error: Architecture mismatch on "return %i7+8".
atomic.c:4445:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4459: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4459:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4488: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4488:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4494: Error: Architecture mismatch on "ba,pt %xcc,.L340 ,pt %xcc,.L340".
atomic.c:4494:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4513: Error: Architecture mismatch on "bne,pn %icc,.L347 ,pn %icc,.L347".
atomic.c:4513:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4521: Error: Architecture mismatch on "bne,pn %icc,.L348 ,pn %icc,.L348".
atomic.c:4521:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4523: Error: Architecture mismatch on "return %i7+8".
atomic.c:4523:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4537: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4537:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4566: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4566:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4572: Error: Architecture mismatch on "ba,pt %xcc,.L346 ,pt %xcc,.L346".
atomic.c:4572:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4591: Error: Architecture mismatch on "bne,pn %icc,.L353 ,pn %icc,.L353".
atomic.c:4591:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4599: Error: Architecture mismatch on "bne,pn %icc,.L354 ,pn %icc,.L354".
atomic.c:4599:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4601: Error: Architecture mismatch on "return %i7+8".
atomic.c:4601:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4615: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4615:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4644: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4644:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4650: Error: Architecture mismatch on "ba,pt %xcc,.L352 ,pt %xcc,.L352".
atomic.c:4650:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4669: Error: Architecture mismatch on "bne,pn %icc,.L359 ,pn %icc,.L359".
atomic.c:4669:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4677: Error: Architecture mismatch on "bne,pn %icc,.L360 ,pn %icc,.L360".
atomic.c:4677:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4679: Error: Architecture mismatch on "return %i7+8".
atomic.c:4679:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4693: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4693:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4722: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4722:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4728: Error: Architecture mismatch on "ba,pt %xcc,.L358 ,pt %xcc,.L358".
atomic.c:4728:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4747: Error: Architecture mismatch on "bne,pn %icc,.L365 ,pn %icc,.L365".
atomic.c:4747:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4757: Error: Architecture mismatch on "bne,pn %icc,.L366 ,pn %icc,.L366".
atomic.c:4757:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4759: Error: Architecture mismatch on "return %i7+8".
atomic.c:4759:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4773: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4773:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4802: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4802:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4808: Error: Architecture mismatch on "ba,pt %xcc,.L364 ,pt %xcc,.L364".
atomic.c:4808:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4827: Error: Architecture mismatch on "bne,pn %icc,.L371 ,pn %icc,.L371".
atomic.c:4827:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4835: Error: Architecture mismatch on "bne,pn %icc,.L372 ,pn %icc,.L372".
atomic.c:4835:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4837: Error: Architecture mismatch on "return %i7+8".
atomic.c:4837:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4851: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4851:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4880: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4880:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4886: Error: Architecture mismatch on "ba,pt %xcc,.L370 ,pt %xcc,.L370".
atomic.c:4886:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4905: Error: Architecture mismatch on "bne,pn %icc,.L377 ,pn %icc,.L377".
atomic.c:4905:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4913: Error: Architecture mismatch on "bne,pn %icc,.L378 ,pn %icc,.L378".
atomic.c:4913:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4915: Error: Architecture mismatch on "return %i7+8".
atomic.c:4915:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4929: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4929:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4958: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:4958:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4964: Error: Architecture mismatch on "ba,pt %xcc,.L376 ,pt %xcc,.L376".
atomic.c:4964:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4983: Error: Architecture mismatch on "bne,pn %icc,.L383 ,pn %icc,.L383".
atomic.c:4983:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4991: Error: Architecture mismatch on "bne,pn %icc,.L384 ,pn %icc,.L384".
atomic.c:4991:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:4993: Error: Architecture mismatch on "return %i7+8".
atomic.c:4993:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5007: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5007:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5036: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5036:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5042: Error: Architecture mismatch on "ba,pt %xcc,.L382 ,pt %xcc,.L382".
atomic.c:5042:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5061: Error: Architecture mismatch on "bne,pn %icc,.L389 ,pn %icc,.L389".
atomic.c:5061:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5069: Error: Architecture mismatch on "bne,pn %icc,.L390 ,pn %icc,.L390".
atomic.c:5069:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5071: Error: Architecture mismatch on "return %i7+8".
atomic.c:5071:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5085: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5085:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5114: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5114:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5120: Error: Architecture mismatch on "ba,pt %xcc,.L388 ,pt %xcc,.L388".
atomic.c:5120:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5139: Error: Architecture mismatch on "bne,pn %icc,.L395 ,pn %icc,.L395".
atomic.c:5139:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5147: Error: Architecture mismatch on "bne,pn %icc,.L396 ,pn %icc,.L396".
atomic.c:5147:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5149: Error: Architecture mismatch on "return %i7+8".
atomic.c:5149:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5163: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5163:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5192: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5192:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5198: Error: Architecture mismatch on "ba,pt %xcc,.L394 ,pt %xcc,.L394".
atomic.c:5198:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5217: Error: Architecture mismatch on "bne,pn %icc,.L401 ,pn %icc,.L401".
atomic.c:5217:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5225: Error: Architecture mismatch on "bne,pn %icc,.L402 ,pn %icc,.L402".
atomic.c:5225:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5227: Error: Architecture mismatch on "return %i7+8".
atomic.c:5227:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5241: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5241:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5270: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5270:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5276: Error: Architecture mismatch on "ba,pt %xcc,.L400 ,pt %xcc,.L400".
atomic.c:5276:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5295: Error: Architecture mismatch on "bne,pn %icc,.L407 ,pn %icc,.L407".
atomic.c:5295:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5303: Error: Architecture mismatch on "bne,pn %icc,.L408 ,pn %icc,.L408".
atomic.c:5303:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5305: Error: Architecture mismatch on "return %i7+8".
atomic.c:5305:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5319: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5319:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5348: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5348:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5354: Error: Architecture mismatch on "ba,pt %xcc,.L406 ,pt %xcc,.L406".
atomic.c:5354:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5373: Error: Architecture mismatch on "bne,pn %icc,.L413 ,pn %icc,.L413".
atomic.c:5373:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5381: Error: Architecture mismatch on "bne,pn %icc,.L414 ,pn %icc,.L414".
atomic.c:5381:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5383: Error: Architecture mismatch on "return %i7+8".
atomic.c:5383:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5397: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5397:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5426: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5426:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5432: Error: Architecture mismatch on "ba,pt %xcc,.L412 ,pt %xcc,.L412".
atomic.c:5432:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5451: Error: Architecture mismatch on "bne,pn %icc,.L419 ,pn %icc,.L419".
atomic.c:5451:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5461: Error: Architecture mismatch on "bne,pn %icc,.L420 ,pn %icc,.L420".
atomic.c:5461:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5463: Error: Architecture mismatch on "return %i7+8".
atomic.c:5463:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5477: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5477:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5506: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5506:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5512: Error: Architecture mismatch on "ba,pt %xcc,.L418 ,pt %xcc,.L418".
atomic.c:5512:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5531: Error: Architecture mismatch on "bne,pn %icc,.L425 ,pn %icc,.L425".
atomic.c:5531:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5539: Error: Architecture mismatch on "bne,pn %icc,.L426 ,pn %icc,.L426".
atomic.c:5539:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5541: Error: Architecture mismatch on "return %i7+8".
atomic.c:5541:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5555: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5555:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5584: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5584:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5590: Error: Architecture mismatch on "ba,pt %xcc,.L424 ,pt %xcc,.L424".
atomic.c:5590:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5609: Error: Architecture mismatch on "bne,pn %icc,.L431 ,pn %icc,.L431".
atomic.c:5609:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5617: Error: Architecture mismatch on "bne,pn %icc,.L432 ,pn %icc,.L432".
atomic.c:5617:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5619: Error: Architecture mismatch on "return %i7+8".
atomic.c:5619:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5633: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5633:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5662: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5662:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5668: Error: Architecture mismatch on "ba,pt %xcc,.L430 ,pt %xcc,.L430".
atomic.c:5668:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5687: Error: Architecture mismatch on "bne,pn %icc,.L437 ,pn %icc,.L437".
atomic.c:5687:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5695: Error: Architecture mismatch on "bne,pn %icc,.L438 ,pn %icc,.L438".
atomic.c:5695:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5697: Error: Architecture mismatch on "return %i7+8".
atomic.c:5697:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5711: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5711:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5740: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5740:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5746: Error: Architecture mismatch on "ba,pt %xcc,.L436 ,pt %xcc,.L436".
atomic.c:5746:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5765: Error: Architecture mismatch on "bne,pn %icc,.L443 ,pn %icc,.L443".
atomic.c:5765:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5773: Error: Architecture mismatch on "bne,pn %icc,.L444 ,pn %icc,.L444".
atomic.c:5773:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5775: Error: Architecture mismatch on "return %i7+8".
atomic.c:5775:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5789: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5789:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5818: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5818:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5824: Error: Architecture mismatch on "ba,pt %xcc,.L442 ,pt %xcc,.L442".
atomic.c:5824:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5843: Error: Architecture mismatch on "bne,pn %icc,.L449 ,pn %icc,.L449".
atomic.c:5843:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5851: Error: Architecture mismatch on "bne,pn %icc,.L450 ,pn %icc,.L450".
atomic.c:5851:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5853: Error: Architecture mismatch on "return %i7+8".
atomic.c:5853:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5867: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5867:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5896: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5896:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5902: Error: Architecture mismatch on "ba,pt %xcc,.L448 ,pt %xcc,.L448".
atomic.c:5902:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5921: Error: Architecture mismatch on "bne,pn %icc,.L455 ,pn %icc,.L455".
atomic.c:5921:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5929: Error: Architecture mismatch on "bne,pn %icc,.L456 ,pn %icc,.L456".
atomic.c:5929:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5931: Error: Architecture mismatch on "return %i7+8".
atomic.c:5931:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5945: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5945:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5974: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:5974:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5980: Error: Architecture mismatch on "ba,pt %xcc,.L454 ,pt %xcc,.L454".
atomic.c:5980:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:5999: Error: Architecture mismatch on "bne,pn %icc,.L461 ,pn %icc,.L461".
atomic.c:5999:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6007: Error: Architecture mismatch on "bne,pn %icc,.L462 ,pn %icc,.L462".
atomic.c:6007:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6009: Error: Architecture mismatch on "return %i7+8".
atomic.c:6009:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6023: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6023:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6052: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6052:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6058: Error: Architecture mismatch on "ba,pt %xcc,.L460 ,pt %xcc,.L460".
atomic.c:6058:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6077: Error: Architecture mismatch on "bne,pn %icc,.L467 ,pn %icc,.L467".
atomic.c:6077:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6087: Error: Architecture mismatch on "bne,pn %icc,.L468 ,pn %icc,.L468".
atomic.c:6087:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6089: Error: Architecture mismatch on "return %i7+8".
atomic.c:6089:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6103: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6103:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6132: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6132:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6138: Error: Architecture mismatch on "ba,pt %xcc,.L466 ,pt %xcc,.L466".
atomic.c:6138:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6157: Error: Architecture mismatch on "bne,a,pn %icc,.L472 ,a,pn %icc,.L472".
atomic.c:6157:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6158: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6158:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6165: Error: Architecture mismatch on "bne,pn %icc,.L473 ,pn %icc,.L473".
atomic.c:6165:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6167: Error: Architecture mismatch on "return %i7+8".
atomic.c:6167:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6200: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6200:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6248: Error: Architecture mismatch on "bne,pn %icc,.L478 ,pn %icc,.L478".
atomic.c:6248:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6256: Error: Architecture mismatch on "bne,pn %icc,.L479 ,pn %icc,.L479".
atomic.c:6256:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6258: Error: Architecture mismatch on "return %i7+8".
atomic.c:6258:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6272: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6272:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6301: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6301:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6307: Error: Architecture mismatch on "ba,pt %xcc,.L477 ,pt %xcc,.L477".
atomic.c:6307:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6326: Error: Architecture mismatch on "bne,pn %icc,.L484 ,pn %icc,.L484".
atomic.c:6326:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6334: Error: Architecture mismatch on "bne,pn %icc,.L485 ,pn %icc,.L485".
atomic.c:6334:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6336: Error: Architecture mismatch on "return %i7+8".
atomic.c:6336:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6350: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6350:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6379: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6379:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6385: Error: Architecture mismatch on "ba,pt %xcc,.L483 ,pt %xcc,.L483".
atomic.c:6385:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6404: Error: Architecture mismatch on "bne,pn %icc,.L490 ,pn %icc,.L490".
atomic.c:6404:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6412: Error: Architecture mismatch on "bne,pn %icc,.L491 ,pn %icc,.L491".
atomic.c:6412:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6414: Error: Architecture mismatch on "return %i7+8".
atomic.c:6414:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6428: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6428:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6457: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6457:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6463: Error: Architecture mismatch on "ba,pt %xcc,.L489 ,pt %xcc,.L489".
atomic.c:6463:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6482: Error: Architecture mismatch on "bne,pn %icc,.L496 ,pn %icc,.L496".
atomic.c:6482:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6490: Error: Architecture mismatch on "bne,pn %icc,.L497 ,pn %icc,.L497".
atomic.c:6490:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6492: Error: Architecture mismatch on "return %i7+8".
atomic.c:6492:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6506: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6506:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6535: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6535:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6541: Error: Architecture mismatch on "ba,pt %xcc,.L495 ,pt %xcc,.L495".
atomic.c:6541:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6560: Error: Architecture mismatch on "bne,pn %icc,.L502 ,pn %icc,.L502".
atomic.c:6560:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6568: Error: Architecture mismatch on "bne,pn %icc,.L503 ,pn %icc,.L503".
atomic.c:6568:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6570: Error: Architecture mismatch on "return %i7+8".
atomic.c:6570:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6584: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6584:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6613: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6613:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6619: Error: Architecture mismatch on "ba,pt %xcc,.L501 ,pt %xcc,.L501".
atomic.c:6619:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6638: Error: Architecture mismatch on "bne,pn %icc,.L508 ,pn %icc,.L508".
atomic.c:6638:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6646: Error: Architecture mismatch on "bne,pn %icc,.L509 ,pn %icc,.L509".
atomic.c:6646:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6648: Error: Architecture mismatch on "return %i7+8".
atomic.c:6648:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6662: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6662:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6691: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6691:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6697: Error: Architecture mismatch on "ba,pt %xcc,.L507 ,pt %xcc,.L507".
atomic.c:6697:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6716: Error: Architecture mismatch on "bne,pn %icc,.L514 ,pn %icc,.L514".
atomic.c:6716:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6724: Error: Architecture mismatch on "bne,pn %icc,.L515 ,pn %icc,.L515".
atomic.c:6724:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6726: Error: Architecture mismatch on "return %i7+8".
atomic.c:6726:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6740: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6740:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6769: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6769:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6775: Error: Architecture mismatch on "ba,pt %xcc,.L513 ,pt %xcc,.L513".
atomic.c:6775:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6794: Error: Architecture mismatch on "bne,pn %icc,.L520 ,pn %icc,.L520".
atomic.c:6794:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6804: Error: Architecture mismatch on "bne,pn %icc,.L521 ,pn %icc,.L521".
atomic.c:6804:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6806: Error: Architecture mismatch on "return %i7+8".
atomic.c:6806:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6820: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6820:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6849: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6849:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6855: Error: Architecture mismatch on "ba,pt %xcc,.L519 ,pt %xcc,.L519".
atomic.c:6855:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6874: Error: Architecture mismatch on "bne,a,pn %icc,.L525 ,a,pn %icc,.L525".
atomic.c:6874:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6875: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6875:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6882: Error: Architecture mismatch on "bne,pn %icc,.L526 ,pn %icc,.L526".
atomic.c:6882:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6884: Error: Architecture mismatch on "return %i7+8".
atomic.c:6884:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6917: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6917:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6965: Error: Architecture mismatch on "bne,pn %icc,.L531 ,pn %icc,.L531".
atomic.c:6965:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6973: Error: Architecture mismatch on "bne,pn %icc,.L532 ,pn %icc,.L532".
atomic.c:6973:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6975: Error: Architecture mismatch on "return %i7+8".
atomic.c:6975:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:6989: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:6989:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7018: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7018:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7024: Error: Architecture mismatch on "ba,pt %xcc,.L530 ,pt %xcc,.L530".
atomic.c:7024:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7043: Error: Architecture mismatch on "bne,pn %icc,.L537 ,pn %icc,.L537".
atomic.c:7043:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7051: Error: Architecture mismatch on "bne,pn %icc,.L538 ,pn %icc,.L538".
atomic.c:7051:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7053: Error: Architecture mismatch on "return %i7+8".
atomic.c:7053:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7067: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7067:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7096: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7096:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7102: Error: Architecture mismatch on "ba,pt %xcc,.L536 ,pt %xcc,.L536".
atomic.c:7102:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7121: Error: Architecture mismatch on "bne,pn %icc,.L543 ,pn %icc,.L543".
atomic.c:7121:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7129: Error: Architecture mismatch on "bne,pn %icc,.L544 ,pn %icc,.L544".
atomic.c:7129:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7131: Error: Architecture mismatch on "return %i7+8".
atomic.c:7131:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7145: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7145:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7174: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7174:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7180: Error: Architecture mismatch on "ba,pt %xcc,.L542 ,pt %xcc,.L542".
atomic.c:7180:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7199: Error: Architecture mismatch on "bne,pn %icc,.L549 ,pn %icc,.L549".
atomic.c:7199:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7207: Error: Architecture mismatch on "bne,pn %icc,.L550 ,pn %icc,.L550".
atomic.c:7207:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7209: Error: Architecture mismatch on "return %i7+8".
atomic.c:7209:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7223: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7223:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7252: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7252:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7258: Error: Architecture mismatch on "ba,pt %xcc,.L548 ,pt %xcc,.L548".
atomic.c:7258:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7277: Error: Architecture mismatch on "bne,pn %icc,.L555 ,pn %icc,.L555".
atomic.c:7277:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7285: Error: Architecture mismatch on "bne,pn %icc,.L556 ,pn %icc,.L556".
atomic.c:7285:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7287: Error: Architecture mismatch on "return %i7+8".
atomic.c:7287:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7301: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7301:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7330: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7330:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7336: Error: Architecture mismatch on "ba,pt %xcc,.L554 ,pt %xcc,.L554".
atomic.c:7336:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7355: Error: Architecture mismatch on "bne,pn %icc,.L561 ,pn %icc,.L561".
atomic.c:7355:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7363: Error: Architecture mismatch on "bne,pn %icc,.L562 ,pn %icc,.L562".
atomic.c:7363:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7365: Error: Architecture mismatch on "return %i7+8".
atomic.c:7365:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7379: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7379:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7408: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7408:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7414: Error: Architecture mismatch on "ba,pt %xcc,.L560 ,pt %xcc,.L560".
atomic.c:7414:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7433: Error: Architecture mismatch on "bne,pn %icc,.L567 ,pn %icc,.L567".
atomic.c:7433:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7441: Error: Architecture mismatch on "bne,pn %icc,.L568 ,pn %icc,.L568".
atomic.c:7441:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7443: Error: Architecture mismatch on "return %i7+8".
atomic.c:7443:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7457: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7457:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7486: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7486:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7492: Error: Architecture mismatch on "ba,pt %xcc,.L566 ,pt %xcc,.L566".
atomic.c:7492:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7511: Error: Architecture mismatch on "bne,pn %icc,.L573 ,pn %icc,.L573".
atomic.c:7511:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7519: Error: Architecture mismatch on "bne,pn %icc,.L574 ,pn %icc,.L574".
atomic.c:7519:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7521: Error: Architecture mismatch on "return %i7+8".
atomic.c:7521:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7535: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7535:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7564: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7564:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7570: Error: Architecture mismatch on "ba,pt %xcc,.L572 ,pt %xcc,.L572".
atomic.c:7570:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7589: Error: Architecture mismatch on "bne,pn %icc,.L579 ,pn %icc,.L579".
atomic.c:7589:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7598: Error: Architecture mismatch on "bne,pn %icc,.L580 ,pn %icc,.L580".
atomic.c:7598:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7614: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7614:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7643: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7643:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7649: Error: Architecture mismatch on "ba,pt %xcc,.L578 ,pt %xcc,.L578".
atomic.c:7649:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7668: Error: Architecture mismatch on "bne,pn %icc,.L585 ,pn %icc,.L585".
atomic.c:7668:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7676: Error: Architecture mismatch on "bne,pn %icc,.L586 ,pn %icc,.L586".
atomic.c:7676:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7678: Error: Architecture mismatch on "return %i7+8".
atomic.c:7678:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7692: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7692:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7721: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7721:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7727: Error: Architecture mismatch on "ba,pt %xcc,.L584 ,pt %xcc,.L584".
atomic.c:7727:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7746: Error: Architecture mismatch on "bne,pn %icc,.L591 ,pn %icc,.L591".
atomic.c:7746:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7754: Error: Architecture mismatch on "bne,pn %icc,.L592 ,pn %icc,.L592".
atomic.c:7754:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7756: Error: Architecture mismatch on "return %i7+8".
atomic.c:7756:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7770: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7770:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7799: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7799:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7805: Error: Architecture mismatch on "ba,pt %xcc,.L590 ,pt %xcc,.L590".
atomic.c:7805:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7824: Error: Architecture mismatch on "bne,pn %icc,.L597 ,pn %icc,.L597".
atomic.c:7824:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7832: Error: Architecture mismatch on "bne,pn %icc,.L598 ,pn %icc,.L598".
atomic.c:7832:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7834: Error: Architecture mismatch on "return %i7+8".
atomic.c:7834:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7848: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7848:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7877: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7877:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7883: Error: Architecture mismatch on "ba,pt %xcc,.L596 ,pt %xcc,.L596".
atomic.c:7883:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7902: Error: Architecture mismatch on "bne,pn %icc,.L603 ,pn %icc,.L603".
atomic.c:7902:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7910: Error: Architecture mismatch on "bne,pn %icc,.L604 ,pn %icc,.L604".
atomic.c:7910:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7912: Error: Architecture mismatch on "return %i7+8".
atomic.c:7912:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7926: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7926:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7955: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:7955:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7961: Error: Architecture mismatch on "ba,pt %xcc,.L602 ,pt %xcc,.L602".
atomic.c:7961:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7980: Error: Architecture mismatch on "bne,pn %icc,.L609 ,pn %icc,.L609".
atomic.c:7980:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7988: Error: Architecture mismatch on "bne,pn %icc,.L610 ,pn %icc,.L610".
atomic.c:7988:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:7990: Error: Architecture mismatch on "return %i7+8".
atomic.c:7990:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8004: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8004:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8033: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8033:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8039: Error: Architecture mismatch on "ba,pt %xcc,.L608 ,pt %xcc,.L608".
atomic.c:8039:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8058: Error: Architecture mismatch on "bne,pn %icc,.L615 ,pn %icc,.L615".
atomic.c:8058:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8066: Error: Architecture mismatch on "bne,pn %icc,.L616 ,pn %icc,.L616".
atomic.c:8066:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8068: Error: Architecture mismatch on "return %i7+8".
atomic.c:8068:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8082: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8082:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8111: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8111:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8117: Error: Architecture mismatch on "ba,pt %xcc,.L614 ,pt %xcc,.L614".
atomic.c:8117:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8136: Error: Architecture mismatch on "bne,pn %icc,.L621 ,pn %icc,.L621".
atomic.c:8136:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8144: Error: Architecture mismatch on "bne,pn %icc,.L622 ,pn %icc,.L622".
atomic.c:8144:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8146: Error: Architecture mismatch on "return %i7+8".
atomic.c:8146:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8160: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8160:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8189: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8189:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8195: Error: Architecture mismatch on "ba,pt %xcc,.L620 ,pt %xcc,.L620".
atomic.c:8195:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8214: Error: Architecture mismatch on "bne,pn %icc,.L627 ,pn %icc,.L627".
atomic.c:8214:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8222: Error: Architecture mismatch on "bne,pn %icc,.L628 ,pn %icc,.L628".
atomic.c:8222:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8224: Error: Architecture mismatch on "return %i7+8".
atomic.c:8224:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8238: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8238:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8267: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8267:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8273: Error: Architecture mismatch on "ba,pt %xcc,.L626 ,pt %xcc,.L626".
atomic.c:8273:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8292: Error: Architecture mismatch on "bne,pn %icc,.L633 ,pn %icc,.L633".
atomic.c:8292:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8301: Error: Architecture mismatch on "bne,pn %icc,.L634 ,pn %icc,.L634".
atomic.c:8301:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8317: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8317:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8346: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8346:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8352: Error: Architecture mismatch on "ba,pt %xcc,.L632 ,pt %xcc,.L632".
atomic.c:8352:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8371: Error: Architecture mismatch on "bne,pn %icc,.L640 ,pn %icc,.L640".
atomic.c:8371:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8375: Error: Architecture mismatch on "be,pn %icc,.L641 ,pn %icc,.L641".
atomic.c:8375:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8381: Error: Architecture mismatch on "bne,pn %icc,.L642 ,pn %icc,.L642".
atomic.c:8381:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8383: Error: Architecture mismatch on "return %i7+8".
atomic.c:8383:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8387: Error: Architecture mismatch on "ba,pt %xcc,.L637 ,pt %xcc,.L637".
atomic.c:8387:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8401: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8401:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8430: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8430:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8436: Error: Architecture mismatch on "ba,pt %xcc,.L639 ,pt %xcc,.L639".
atomic.c:8436:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8455: Error: Architecture mismatch on "bne,pn %icc,.L648 ,pn %icc,.L648".
atomic.c:8455:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8459: Error: Architecture mismatch on "be,pn %icc,.L649 ,pn %icc,.L649".
atomic.c:8459:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8465: Error: Architecture mismatch on "bne,pn %icc,.L650 ,pn %icc,.L650".
atomic.c:8465:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8467: Error: Architecture mismatch on "return %i7+8".
atomic.c:8467:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8471: Error: Architecture mismatch on "ba,pt %xcc,.L645 ,pt %xcc,.L645".
atomic.c:8471:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8485: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8485:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8514: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8514:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8520: Error: Architecture mismatch on "ba,pt %xcc,.L647 ,pt %xcc,.L647".
atomic.c:8520:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8539: Error: Architecture mismatch on "bne,pn %icc,.L656 ,pn %icc,.L656".
atomic.c:8539:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8545: Error: Architecture mismatch on "be,pn %icc,.L657 ,pn %icc,.L657".
atomic.c:8545:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8551: Error: Architecture mismatch on "bne,pn %icc,.L658 ,pn %icc,.L658".
atomic.c:8551:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8553: Error: Architecture mismatch on "return %i7+8".
atomic.c:8553:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8557: Error: Architecture mismatch on "ba,pt %xcc,.L653 ,pt %xcc,.L653".
atomic.c:8557:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8571: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8571:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8600: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8600:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8606: Error: Architecture mismatch on "ba,pt %xcc,.L655 ,pt %xcc,.L655".
atomic.c:8606:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8625: Error: Architecture mismatch on "bne,pn %icc,.L664 ,pn %icc,.L664".
atomic.c:8625:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8631: Error: Architecture mismatch on "be,pn %icc,.L665 ,pn %icc,.L665".
atomic.c:8631:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8637: Error: Architecture mismatch on "bne,pn %icc,.L666 ,pn %icc,.L666".
atomic.c:8637:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8639: Error: Architecture mismatch on "return %i7+8".
atomic.c:8639:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8643: Error: Architecture mismatch on "ba,pt %xcc,.L661 ,pt %xcc,.L661".
atomic.c:8643:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8657: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8657:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8686: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8686:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8692: Error: Architecture mismatch on "ba,pt %xcc,.L663 ,pt %xcc,.L663".
atomic.c:8692:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8711: Error: Architecture mismatch on "bne,pn %icc,.L672 ,pn %icc,.L672".
atomic.c:8711:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8715: Error: Architecture mismatch on "be,pn %icc,.L673 ,pn %icc,.L673".
atomic.c:8715:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8721: Error: Architecture mismatch on "bne,pn %icc,.L674 ,pn %icc,.L674".
atomic.c:8721:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8723: Error: Architecture mismatch on "return %i7+8".
atomic.c:8723:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8727: Error: Architecture mismatch on "ba,pt %xcc,.L669 ,pt %xcc,.L669".
atomic.c:8727:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8741: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8741:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8770: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8770:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8776: Error: Architecture mismatch on "ba,pt %xcc,.L671 ,pt %xcc,.L671".
atomic.c:8776:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8795: Error: Architecture mismatch on "bne,pn %icc,.L680 ,pn %icc,.L680".
atomic.c:8795:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8799: Error: Architecture mismatch on "be,pn %icc,.L681 ,pn %icc,.L681".
atomic.c:8799:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8805: Error: Architecture mismatch on "bne,pn %icc,.L682 ,pn %icc,.L682".
atomic.c:8805:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8807: Error: Architecture mismatch on "return %i7+8".
atomic.c:8807:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8811: Error: Architecture mismatch on "ba,pt %xcc,.L677 ,pt %xcc,.L677".
atomic.c:8811:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8825: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8825:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8854: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8854:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8860: Error: Architecture mismatch on "ba,pt %xcc,.L679 ,pt %xcc,.L679".
atomic.c:8860:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8879: Error: Architecture mismatch on "bne,pn %icc,.L688 ,pn %icc,.L688".
atomic.c:8879:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8883: Error: Architecture mismatch on "be,pn %icc,.L689 ,pn %icc,.L689".
atomic.c:8883:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8889: Error: Architecture mismatch on "bne,pn %icc,.L690 ,pn %icc,.L690".
atomic.c:8889:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8891: Error: Architecture mismatch on "return %i7+8".
atomic.c:8891:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8895: Error: Architecture mismatch on "ba,pt %xcc,.L685 ,pt %xcc,.L685".
atomic.c:8895:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8909: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8909:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8938: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8938:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8944: Error: Architecture mismatch on "ba,pt %xcc,.L687 ,pt %xcc,.L687".
atomic.c:8944:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8964: Error: Architecture mismatch on "bne,pn %icc,.L696 ,pn %icc,.L696".
atomic.c:8964:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8968: Error: Architecture mismatch on "be,pn %icc,.L697 ,pn %icc,.L697".
atomic.c:8968:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8974: Error: Architecture mismatch on "bne,pn %icc,.L698 ,pn %icc,.L698".
atomic.c:8974:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8979: Error: Architecture mismatch on "be,a,pn %icc,.L693 ,a,pn %icc,.L693".
atomic.c:8979:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8981: Error: Architecture mismatch on "ba,pt %xcc,.L693 ,pt %xcc,.L693".
atomic.c:8981:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:8996: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:8996:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9025: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9025:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9031: Error: Architecture mismatch on "ba,pt %xcc,.L695 ,pt %xcc,.L695".
atomic.c:9031:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9050: Error: Architecture mismatch on "bne,a,pn %icc,.L703 ,a,pn %icc,.L703".
atomic.c:9050:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9051: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9051:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9054: Error: Architecture mismatch on "be,a,pn %icc,.L706 ,a,pn %icc,.L706".
atomic.c:9054:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9061: Error: Architecture mismatch on "bne,a,pn %icc,.L705 ,a,pn %icc,.L705".
atomic.c:9061:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9062: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9062:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9063: Error: Architecture mismatch on "return %i7+8".
atomic.c:9063:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9143: Error: Architecture mismatch on "bne,pn %icc,.L711 ,pn %icc,.L711".
atomic.c:9143:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9151: Error: Architecture mismatch on "bne,pn %icc,.L712 ,pn %icc,.L712".
atomic.c:9151:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9153: Error: Architecture mismatch on "return %i7+8".
atomic.c:9153:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9167: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9167:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9196: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9196:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9202: Error: Architecture mismatch on "ba,pt %xcc,.L710 ,pt %xcc,.L710".
atomic.c:9202:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9221: Error: Architecture mismatch on "bne,pn %icc,.L717 ,pn %icc,.L717".
atomic.c:9221:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9229: Error: Architecture mismatch on "bne,pn %icc,.L718 ,pn %icc,.L718".
atomic.c:9229:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9231: Error: Architecture mismatch on "return %i7+8".
atomic.c:9231:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9245: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9245:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9274: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9274:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9280: Error: Architecture mismatch on "ba,pt %xcc,.L716 ,pt %xcc,.L716".
atomic.c:9280:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9299: Error: Architecture mismatch on "bne,pn %icc,.L723 ,pn %icc,.L723".
atomic.c:9299:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9307: Error: Architecture mismatch on "bne,pn %icc,.L724 ,pn %icc,.L724".
atomic.c:9307:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9309: Error: Architecture mismatch on "return %i7+8".
atomic.c:9309:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9323: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9323:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9352: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9352:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9358: Error: Architecture mismatch on "ba,pt %xcc,.L722 ,pt %xcc,.L722".
atomic.c:9358:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9377: Error: Architecture mismatch on "bne,pn %icc,.L729 ,pn %icc,.L729".
atomic.c:9377:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9385: Error: Architecture mismatch on "bne,pn %icc,.L730 ,pn %icc,.L730".
atomic.c:9385:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9387: Error: Architecture mismatch on "return %i7+8".
atomic.c:9387:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9401: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9401:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9430: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9430:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9436: Error: Architecture mismatch on "ba,pt %xcc,.L728 ,pt %xcc,.L728".
atomic.c:9436:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9455: Error: Architecture mismatch on "bne,pn %icc,.L735 ,pn %icc,.L735".
atomic.c:9455:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9463: Error: Architecture mismatch on "bne,pn %icc,.L736 ,pn %icc,.L736".
atomic.c:9463:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9465: Error: Architecture mismatch on "return %i7+8".
atomic.c:9465:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9479: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9479:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9508: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9508:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9514: Error: Architecture mismatch on "ba,pt %xcc,.L734 ,pt %xcc,.L734".
atomic.c:9514:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9533: Error: Architecture mismatch on "bne,pn %icc,.L741 ,pn %icc,.L741".
atomic.c:9533:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9541: Error: Architecture mismatch on "bne,pn %icc,.L742 ,pn %icc,.L742".
atomic.c:9541:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9543: Error: Architecture mismatch on "return %i7+8".
atomic.c:9543:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9557: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9557:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9586: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9586:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9592: Error: Architecture mismatch on "ba,pt %xcc,.L740 ,pt %xcc,.L740".
atomic.c:9592:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9611: Error: Architecture mismatch on "bne,pn %icc,.L747 ,pn %icc,.L747".
atomic.c:9611:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9619: Error: Architecture mismatch on "bne,pn %icc,.L748 ,pn %icc,.L748".
atomic.c:9619:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9621: Error: Architecture mismatch on "return %i7+8".
atomic.c:9621:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9635: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9635:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9664: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9664:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9670: Error: Architecture mismatch on "ba,pt %xcc,.L746 ,pt %xcc,.L746".
atomic.c:9670:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9690: Error: Architecture mismatch on "bne,pn %icc,.L753 ,pn %icc,.L753".
atomic.c:9690:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9698: Error: Architecture mismatch on "bne,pn %icc,.L754 ,pn %icc,.L754".
atomic.c:9698:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9700: Error: Architecture mismatch on "return %i7+8".
atomic.c:9700:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9715: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9715:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9744: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9744:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9750: Error: Architecture mismatch on "ba,pt %xcc,.L752 ,pt %xcc,.L752".
atomic.c:9750:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9769: Error: Architecture mismatch on "bne,pn %icc,.L758 ,pn %icc,.L758".
atomic.c:9769:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9775: Error: Architecture mismatch on "bne,pn %icc,.L759 ,pn %icc,.L759".
atomic.c:9775:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9777: Error: Architecture mismatch on "return %i7+8".
atomic.c:9777:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9780: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9780:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9811: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9811:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9859: Error: Architecture mismatch on "bne,a,pn %icc,.L769 ,a,pn %icc,.L769".
atomic.c:9859:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9860: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9860:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9865: Error: Architecture mismatch on "be,pt %icc,.L762 ,pt %icc,.L762".
atomic.c:9865:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9870: Error: Architecture mismatch on "bne,pn %icc,.L770 ,pn %icc,.L770".
atomic.c:9870:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9873: Error: Architecture mismatch on "return %i7+8".
atomic.c:9873:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9882: Error: Architecture mismatch on "be,pt %icc,.L771 ,pt %icc,.L771".
atomic.c:9882:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9884: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9884:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9914: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9914:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9992: Error: Architecture mismatch on "bne,a,pn %icc,.L781 ,a,pn %icc,.L781".
atomic.c:9992:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9993: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:9993:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:9998: Error: Architecture mismatch on "be,pt %icc,.L774 ,pt %icc,.L774".
atomic.c:9998:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:10003: Error: Architecture mismatch on "bne,pn %icc,.L782 ,pn %icc,.L782".
atomic.c:10003:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:10006: Error: Architecture mismatch on "return %i7+8".
atomic.c:10006:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:10015: Error: Architecture mismatch on "be,pt %icc,.L783 ,pt %icc,.L783".
atomic.c:10015:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:10017: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:10017:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
atomic.c:10047: Error: Architecture mismatch on "stx %g0,[%fp-8]".
atomic.c:10047:  (Requires v9|v9a|v9b|v9c|v9d|v9e|v9v|v9m; requested architecture is sparclite.)
make[4]: *** [Makefile:582: atomic.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/var/tmp/portage/sys-fs/zfs-0.7.1-r1/work/zfs-0.7.1/lib/libspl'
make[3]: *** [Makefile:626: all-recursive] Error 1
make[3]: Leaving directory '/var/tmp/portage/sys-fs/zfs-0.7.1-r1/work/zfs-0.7.1/lib/libspl'
make[2]: *** [Makefile:458: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/sys-fs/zfs-0.7.1-r1/work/zfs-0.7.1/lib'
make[1]: *** [Makefile:611: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-fs/zfs-0.7.1-r1/work/zfs-0.7.1'
make: *** [Makefile:480: all] Error 2
```

### LINKED ISSUE #6738: zfs on sparc needs const static int sha1_consts[] = { ... } inside SHA1Transform() to compile
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Gentoo Linux
Distribution Version    |  Live
Linux Kernel                 |  4.9.49
Architecture                 |  UltraSPARC T2
ZFS Version                  |  [all]
SPL Version                  |  [all]

### Describe the problem you're observing

https://github.com/bahamas10/openzfs/blob/d4732e670edab07052ad1ccbcb4497c9bf6df199/usr/src/common/crypto/sha1/sha1.c#L502-L538

We need that as well, as `SHA1_CONST` macro has defined the behavior is to use this array on sparc, yet which was not implemented in the sources, which would result in the linker not finding the corresponding symbol `sha1_consts`.

https://github.com/zfsonlinux/zfs/blob/87f9371aefca857e7091dfdee3ec2d36b0de54c4/module/icp/include/sha1/sha1_consts.h#L46-L49

### Describe how to reproduce the problem

[inapplicable]

### Include any warning/errors/backtraces from the system logs

[inapplicable]

### PR DESCRIPTION
**Pull request by KireinaHoro**
### Description

Current code base almost compiles on SPARC, yet a few fixes are required for the code to compile
(and work efficiently). Code in this PR comes from OpenZFS project, nearly all of them dates back
to OpenZFS launch (~12 yrs ago).

### Motivation and Context

Fixes #6738.
Fixes #6733.

### How Has This Been Tested?

Compile passed (including all compile-time unit tests) on an UltraSPARC T2 machine (namely a Sun Enterprise T5120).
`ztest` finished successfully with return value 0.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

File: module/icp/algs/sha1/sha1.c [hunk 1]
```diff
@@ -48,8 +48,8 @@ static void Encode(uint8_t *, const uint32_t *, size_t);
 #if defined(__sparc)
 
 #define	SHA1_TRANSFORM(ctx, in) \
-		SHA1Transform((ctx)->state[0], (ctx)->state[1], (ctx)->state[2], \
-				(ctx)->state[3], (ctx)->state[4], (ctx), (in))
+	SHA1Transform((ctx)->state[0], (ctx)->state[1], (ctx)->state[2], \
+		(ctx)->state[3], (ctx)->state[4], (ctx), (in))
```
Comment (behlendorf) [inline module/icp/algs/sha1/sha1.c]: nit: It looks like this style fix should be in 3b05b504be9c4b845a5e6b563dcf38e026327498

File: lib/libspl/Makefile.am [hunk 2]
```diff
@@ -13,7 +13,8 @@ DEFAULT_INCLUDES += \
 	-I$(top_srcdir)/lib/libspl/include
 
 AM_CCASFLAGS = \
-	-I$(top_srcdir)/lib/libspl/include
+	-I$(top_srcdir)/lib/libspl/include \
+	$(CFLAGS)
```
Comment (behlendorf) [inline lib/libspl/Makefile.am]: It looks like you can remove `-I$(top_srcdir)/lib/libspl/include` from `AM_CCASFLAGS` while you're here to simplify things.  `CPPASCOMPILE` and `LTCPPASCOMPILE` both already include `DEFAULT_INCLUDES`.

File: module/icp/algs/sha1/sha1.c (hunk 1 above)
Comment (KireinaHoro) [reply module/icp/algs/sha1/sha1.c]: I've rebased the branch and that styling issue fix is now in its correct place.

File: lib/libspl/Makefile.am (hunk 2 above)
Comment (KireinaHoro) [reply lib/libspl/Makefile.am]: Added a new commit to remove that line.
