### PR TITLE
Fix segfault in zpool iostat when adding VDEVs

### LINKED ISSUE #6748: Zpool iostat -v segfault when a vdev is added
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Centos
Distribution Version    | 7.2.1511
Linux Kernel                 | 3.10.0-693.1.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.0-58_gcf7684b
SPL Version                  | 0.7.0-12_g9df9692

### Describe the problem you're observing

zpool iostat -v segfault when a vdev is added to a pool : 

```
              capacity     operations     bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
LSI005-OST  3.16M  43.5T     17    401  1.14M  10.5M
  raidz2    3.16M  21.7T      0    304      0  4.66M
    mpatha      -      -      0    103      0  1.55M
    mpathb      -      -      0    100      0  1.55M
    mpathc      -      -      0    100      0  1.55M
Segmentation fault (core dumped)
```

```
[root@lsi005 ~]# zpool iostat -v 1
              capacity     operations     bandwidth 
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
LSI005-OST  7.43G  87.0T      0  1.02K  8.44K  1013M
  raidz2    1.86G  21.7T      0    626  2.11K   608M
    mpatha      -      -      0    208    720   203M
    mpathb      -      -      0    208    720   203M
    mpathc      -      -      0    209    720   203M
  raidz2    1.86G  21.7T      0    610  4.36K   587M
    mpathd      -      -      0    203  1.45K   196M
    mpathe      -      -      0    203  1.45K   196M
    mpathf      -      -      0    203  1.45K   196M
```

### Describe how to reproduce the problem

Create a zpool
run zpool iostat -v 1
Add a new vdev to the pool while zpool iostat -v 1 is running
zpool iostat segfault

### Include any warning/errors/backtraces from the system logs
```
Oct 10 16:15:35 lsi005 kernel: [10696.250879] zpool[65607]: segfault at 100000008 ip 00007fe38eb0012b sp 00007ffc2b8f1840 error 4 in libnvpair.so.1.0.1[7fe38eaf5000+13000]
Oct 10 16:15:35 lsi005 kernel: zpool[65607]: segfault at 100000008 ip 00007fe38eb0012b sp 00007ffc2b8f1840 error 4 in libnvpair.so.1.0.1[7fe38eaf5000+13000]
```

```
(gdb) core /var/spool/abrt/ccpp-2017-10-10-16:59:02-48245/coredump
[New LWP 48245]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `zpool iostat -v 1'.
Program terminated with signal 11, Segmentation fault.
#0  nvlist_lookup_common (nvl=0x100000000, name=0x41cc6d "vdev_stats", type=DATA_TYPE_UINT64_ARRAY, nelem=0x7ffff3c85408, data=0x7ffff3c85420) at ../../module/nvpair/nvpair.c:1348
1348                (priv = (nvpriv_t *)(uintptr_t)nvl->nvl_priv) == NULL)
(gdb) bt
#0  nvlist_lookup_common (nvl=0x100000000, name=0x41cc6d "vdev_stats", type=DATA_TYPE_UINT64_ARRAY, nelem=0x7ffff3c85408, data=0x7ffff3c85420) at ../../module/nvpair/nvpair.c:1348
#1  0x00007f36e2957672 in nvlist_lookup_common (data=<optimized out>, nelem=<optimized out>, type=DATA_TYPE_UINT64_ARRAY, name=<optimized out>, nvl=<optimized out>) at ../../module/nvpair/nvpair.c:1347
#2  nvlist_lookup_uint64_array (nvl=<optimized out>, name=<optimized out>, a=<optimized out>, n=<optimized out>) at ../../module/nvpair/nvpair.c:1518
#3  0x0000000000412476 in print_vdev_stats (zhp=zhp@entry=0x2496620, name=name@entry=0x2536790 "raidz2", oldnv=0x100000000, newnv=0x2504bc8, cb=cb@entry=0x7ffff3c858e0, depth=depth@entry=2) at zpool_main.c:3657
#4  0x0000000000412c6d in print_vdev_stats (zhp=zhp@entry=0x2496620, name=<optimized out>, oldnv=oldnv@entry=0x248f280, newnv=newnv@entry=0x2502d20, cb=cb@entry=0x7ffff3c858e0, depth=depth@entry=0) at zpool_main.c:3775
#5  0x00000000004136a9 in print_iostat (zhp=0x2496620, data=0x7ffff3c858e0) at zpool_main.c:3881
#6  0x00000000004062f8 in pool_list_iter (zlp=zlp@entry=0x248ac30, unavail=unavail@entry=0, func=func@entry=0x413610 <print_iostat>, data=data@entry=0x7ffff3c858e0) at zpool_iter.c:178
#7  0x0000000000411ef2 in zpool_do_iostat (argc=0, argv=0x7ffff3c89aa0) at zpool_main.c:4694
#8  0x0000000000405a94 in main (argc=4, argv=0x7ffff3c89a88) at zpool_main.c:8042
```

Not that this bug is critical ... just that I was doing some automated performance testing, and have been hitting it quite a few time ^^.

### PR DESCRIPTION
**Pull request by tonyhutter**
### Description
Fix a segfault when running 'zpool iostat -v 1' while adding a VDEV.

### Motivation and Context
Closes #6748 

### How Has This Been Tested?
Reproducer:
```
#!/bin/bash
truncate -s 100M /tmp/file{1,2}
sudo ./cmd/zpool/zpool create mypool /tmp/file1
(sleep 4 && sudo ./cmd/zpool/zpool add mypool /tmp/file2) &
sudo ./cmd/zpool/zpool iostat -v 1
```
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

File: cmd/zpool/zpool_main.c [hunk 1]
```diff
@@ -3736,6 +3736,12 @@ print_vdev_stats(zpool_handle_t *zhp, const char *name, nvlist_t *oldnv,
 	    &oldchild, &c) != 0)
 		return (ret);
 
+	/*
+	 * Use MIN() here to deal with VDEVs being added while we're viewing
+	 * the stats.
+	 */
+	children = MIN(c, children);
```
Comment (behlendorf) [inline cmd/zpool/zpool_main.c]: Rather that continuing to borrow `c` for this check why not add a new `oldchildren` variable for clarity.  Then the `MIN` check would be clear without the need for any comment.

**Comment by tonyhutter** [comment]
@behlendorf I included your changes and rebased.

**Comment by behlendorf** [comment]
@tonyhutter some additional investigation is needed for this PR.  These test failures don't appear in master and may have been introduced by this change.

**Comment by tonyhutter** [comment]
@behlendorf yep buildbot caught a real bug.  We'll see if my latest push fixes it.

File: cmd/zpool/zpool_main.c [hunk 2]
```diff
@@ -3761,9 +3761,12 @@ print_vdev_stats(zpool_handle_t *zhp, const char *name, nvlist_t *oldnv,
 		return (ret);
 
 	if (oldnv && nvlist_lookup_nvlist_array(oldnv, ZPOOL_CONFIG_CHILDREN,
-	    &oldchild, &c) != 0)
+	    &oldchild, &oldchildren) != 0)
 		return (ret);
 
+	if (oldnv != NULL)
+		children = MIN(oldchildren, children);
+
```
Comment (behlendorf) [inline cmd/zpool/zpool_main.c]: The fix looks good, but what do you think about restructuring it like this:

```c
        if (oldnv) {
                if (nvlist_lookup_nvlist_array(oldnv, ZPOOL_CONFIG_CHILDREN,
                    &oldchild, &oldchildren) != 0)
                        return (ret);

                children = MIN(oldchildren, children);
        }
```

Comment (tonyhutter) [reply cmd/zpool/zpool_main.c]: Yea, that's better.  I just included it in my latest push.
