### PR TITLE
Reimplement vdev_random_leaf and rename it

### LINKED ISSUE #6631: vdev_random_leaf() can loop forever
### Describe the problem you're observing

While adding encrypted dataset support to ztest I cam across an issue with the mmp code. ztest began to eat 100% CPU without making any forward progress. When I examined the process with gdb, I found that `vdev_random_leaf()` was looping infinitely. It seems that ztest had gotten the pool into a state where it had one top-level mirror vdev with only one child which was not writable. This causes the following code to loop infinitely:

```
	while (!vd->vdev_ops->vdev_op_leaf) {
		child = vd->vdev_child[spa_get_random(vd->vdev_children)];

		if (!vdev_writeable(child))
			continue;

        ...
```

### Describe how to reproduce the problem
This came up twice while doing lots of zloop runs over the course of a week. I suspect it should be fairly easy to reproduce by creating a pool with the layout I described above.

### PR DESCRIPTION
**Pull request by ofaaland**
### Description

Rename the function mmp_random_leaf() since it is defined in mmp.c.

Reimplement to recursively walk the device tree to select the leaf.  It
searches the entire tree, so that a return value of (NULL) indicates
there were no usable leaves in the pool; all were either not writeable
or had pending mmp writes.

It still chooses the starting child randomly at each level of the tree,
so if the pool's devices are healthy, the mmp writes go to random leaves
with an even distribution.  This was verified by testing using
zfs_multihost_history enabled.

### Motivation and Context

The earlier implementation could end up spinning forever if a pool had a
vdev marked writeable, none of whose children were writeable.  It also
did not guarantee that if a writeable leaf vdev existed, it would be
found.

Fixes #6631 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

File: module/zfs/mmp.c [hunk 1]
```diff
@@ -198,50 +198,50 @@ mmp_thread_stop(spa_t *spa)
...
- * We try 10 times to pick a random leaf without an outstanding write.
- * If 90% of the leaves have pending writes, this gives us a >65%
- * chance of finding one we can write to.  There will be at least
- * (zfs_multihost_fail_intervals) tries before the inability to write an MMP
- * block causes serious problems.
+ * When walking the subtree, a random child is chosen as the starting point so
+ * that when the tree is healthy, the leaf chosen will be random with even
+ * distribution.  If there are unhealthy vdevs in the tree, the distribution
+ * will be really poor only if a large proportion of the vdevs are unhealthy,
+ * in which case there are other more pressing problems..
```
Comment (behlendorf) [inline module/zfs/mmp.c]: nit: extra period at end of line

File: module/zfs/mmp.c [hunk 2]
```diff
@@ -198,50 +198,50 @@ mmp_thread_stop(spa_t *spa)
...
-		if (!vdev_writeable(child))
-			continue;
-
-		if (child->vdev_ops->vdev_op_leaf && child->vdev_mmp_pending) {
-			if (pending_writes-- > 0)
-				continue;
-			else
-				return (NULL);
-		}
+	if (vd->vdev_children == 0) {
```
Comment (behlendorf) [inline module/zfs/mmp.c]: When `vd->vdev_children == 0` then `vd->vdev_ops->vdev_op_leaf == B_TRUE`.  Many of the existing functions which recursively walk the tree already depends on this.  So you could simplify this too.

```c
        if (vd->vdev_ops->vdev_op_leaf) {
                if (vd->vdev_mmp_pending == 0)
                        return (vd);
                else
                        return (NULL);
        }
```

Or even

```c
        if (vd->vdev_ops->vdev_op_leaf)
                return (vd->vdev_mmp_pending == 0 ? vd : NULL);
```

File: module/zfs/mmp.c [hunk 3]
```diff
@@ -198,50 +198,50 @@ mmp_thread_stop(spa_t *spa)
...
-	ASSERT(spa_config_held(spa, SCL_STATE, RW_READER) == SCL_STATE);
+	if (!vdev_writeable(vd))
+		return (NULL);
 
 	/*
-	 * Since we hold SCL_STATE, neither pool nor vdev state can
-	 * change.  Therefore, if the root is not dead, there is a
-	 * child that is not dead, and so on down to a leaf.
+	 * Base case: vd has no children
 	 */
```
Comment (behlendorf) [inline module/zfs/mmp.c]: In this case, I suggest dropping the `Base case` and `Recursive case` comments which I don't think add much.  The function is already pretty small and concise (which is good!).

File: module/zfs/mmp.c (hunk 1 above)
Comment (ofaaland) [reply module/zfs/mmp.c]: done

File: module/zfs/mmp.c (hunk 3 above)
Comment (ofaaland) [reply module/zfs/mmp.c]: done

File: module/zfs/mmp.c (hunk 2 above)
Comment (ofaaland) [reply module/zfs/mmp.c]: done

**Comment by ofaaland** [comment]
Pushed an update that addressed the review feedback.
