### PR TITLE
Fix hung z_zvol tasks during 'zfs receive'

### LINKED ISSUE #6330: z_vol task hung on receiving side of zfs send
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Proxmox
Distribution Version    | 5.0
Linux Kernel                 | 4.10.15-15
Architecture                 | amd64
ZFS Version                  | 0.7.0-rc4_96_g0ea05c64f
SPL Version                  | 0.7.0-rc4_5_g7a35f2b

### Describe the problem you're observing
I'm observing the following stack trace on the receiving side of zfs send.

### Describe how to reproduce the problem
Setup a regular send to remote system (1/hour)

### Include any warning/errors/backtraces from the system logs
```
[27671.358618] INFO: task z_zvol:348 blocked for more than 120 seconds.
[27671.360473]       Tainted: P           O    4.10.15-1-pve #1
[27671.362479] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[27671.363379] z_zvol          D    0   348      2 0x00000000
[27671.364409] Call Trace:
[27671.365169]  __schedule+0x233/0x6f0
[27671.366083]  schedule+0x36/0x80
[27671.366877]  taskq_wait_outstanding+0x8c/0xd0 [spl]
[27671.367720]  ? wake_atomic_t_function+0x60/0x60
[27671.368698]  zvol_task_cb+0x2fd/0x490 [zfs]
[27671.369449]  ? __schedule+0x23b/0x6f0
[27671.370574]  taskq_thread+0x25e/0x460 [spl]
[27671.371725]  ? wake_up_q+0x80/0x80
[27671.372447]  kthread+0x109/0x140
[27671.373306]  ? taskq_cancel_id+0x130/0x130 [spl]
[27671.374005]  ? kthread_create_on_node+0x60/0x60
[27671.374736]  ret_from_fork+0x2c/0x40
[27913.020358] INFO: task z_zvol:348 blocked for more than 120 seconds.
[27913.021135]       Tainted: P           O    4.10.15-1-pve #1
[27913.021804] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[27913.022507] z_zvol          D    0   348      2 0x00000000
[27913.023489] Call Trace:
[27913.024566]  __schedule+0x233/0x6f0
[27913.025821]  schedule+0x36/0x80
[27913.026760]  taskq_wait_outstanding+0x8c/0xd0 [spl]
[27913.027658]  ? wake_atomic_t_function+0x60/0x60
[27913.029015]  zvol_task_cb+0x2fd/0x490 [zfs]
[27913.030207]  ? __schedule+0x23b/0x6f0
[27913.031317]  taskq_thread+0x25e/0x460 [spl]
[27913.032461]  ? wake_up_q+0x80/0x80
[27913.033602]  kthread+0x109/0x140
[27913.034545]  ? taskq_cancel_id+0x130/0x130 [spl]
[27913.035439]  ? kthread_create_on_node+0x60/0x60
[27913.036467]  ret_from_fork+0x2c/0x40

```

### LINKED ISSUE #6890: task z_zvol blocked for more than 120 seconds.
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Arch Linux
Distribution Version    |  latest
Linux Kernel                 |  linux-ck 4.13.14.1-ck
Architecture                 | 64
ZFS Version                  |  0.7.3-1 (AUR, dkms)
SPL Version                  |  0.7.3-1 (AUR, dkms)

### Describe the problem you're observing

ZFS hangs on zfs send | receive combo on local machine from LUKS-encrypted nvme partition (tank) to LUKS-encrypted SATA HDD connected via USB3.0 dock (dozer). The HDD is *possibly* faulty, however badblocks performed before the send|receive combo did not yield any problems.

### Describe how to reproduce the problem

zpool tank has about 300 snapshots of 10 (out of 18) datasets made by zfs-auto-snapshot.

```
zfs send -RLc tank@send | zfs receive -Fusvd dozer
```

### Include any warning/errors/backtraces from the system logs

dmesg:
```
[  204.780233] usb 2-4: new SuperSpeed USB device number 2 using xhci_hcd
[  204.802181] usb-storage 2-4:1.0: USB Mass Storage device detected
[  204.802222] usb-storage 2-4:1.0: Quirks match for vid 174c pid 55aa: 400000
[  204.802236] scsi host3: usb-storage 2-4:1.0
[  205.830501] scsi 3:0:0:0: Direct-Access     ASMedia  ASM1153          0    PQ: 0 ANSI: 6
[  205.881441] sd 3:0:0:0: [sdb] 625134827 512-byte logical blocks: (320 GB/298 GiB)
[  205.881675] sd 3:0:0:0: [sdb] Write Protect is off
[  205.881677] sd 3:0:0:0: [sdb] Mode Sense: 43 00 00 00
[  205.881876] sd 3:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  205.930655]  sdb: sdb1
[  205.931489] sd 3:0:0:0: [sdb] Attached SCSI disk
[  858.070057] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[  858.070061]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[  858.070062] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  858.070063] z_zvol          D    0 17045      2 0x00000000
[  858.070065] Call Trace:
[  858.070070]  __schedule+0x6eb/0xcd0
[  858.070072]  schedule+0x3d/0xd0
[  858.070076]  taskq_wait_outstanding+0x87/0xd0 [spl]
[  858.070078]  ? wait_woken+0x80/0x80
[  858.070094]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[  858.070097]  taskq_thread+0x254/0x480 [spl]
[  858.070100]  ? wake_up_q+0x80/0x80
[  858.070102]  kthread+0x124/0x140
[  858.070104]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[  858.070106]  ? kthread_create_on_node+0x70/0x70
[  858.070108]  ret_from_fork+0x25/0x30
[  980.960061] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[  980.960066]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[  980.960067] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  980.960068] z_zvol          D    0 17045      2 0x00000000
[  980.960070] Call Trace:
[  980.960076]  __schedule+0x6eb/0xcd0
[  980.960079]  schedule+0x3d/0xd0
[  980.960083]  taskq_wait_outstanding+0x87/0xd0 [spl]
[  980.960086]  ? wait_woken+0x80/0x80
[  980.960102]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[  980.960105]  taskq_thread+0x254/0x480 [spl]
[  980.960108]  ? wake_up_q+0x80/0x80
[  980.960111]  kthread+0x124/0x140
[  980.960114]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[  980.960115]  ? kthread_create_on_node+0x70/0x70
[  980.960118]  ret_from_fork+0x25/0x30
[ 1103.830057] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[ 1103.830061]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1103.830062] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1103.830063] z_zvol          D    0 17045      2 0x00000000
[ 1103.830066] Call Trace:
[ 1103.830071]  __schedule+0x6eb/0xcd0
[ 1103.830073]  schedule+0x3d/0xd0
[ 1103.830077]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1103.830080]  ? wait_woken+0x80/0x80
[ 1103.830095]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1103.830099]  taskq_thread+0x254/0x480 [spl]
[ 1103.830102]  ? wake_up_q+0x80/0x80
[ 1103.830104]  kthread+0x124/0x140
[ 1103.830106]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1103.830108]  ? kthread_create_on_node+0x70/0x70
[ 1103.830110]  ret_from_fork+0x25/0x30
[ 1226.710103] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[ 1226.710106]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1226.710107] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1226.710108] z_zvol          D    0 17045      2 0x00000000
[ 1226.710110] Call Trace:
[ 1226.710115]  __schedule+0x6eb/0xcd0
[ 1226.710117]  schedule+0x3d/0xd0
[ 1226.710121]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1226.710123]  ? wait_woken+0x80/0x80
[ 1226.710138]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1226.710141]  taskq_thread+0x254/0x480 [spl]
[ 1226.710143]  ? wake_up_q+0x80/0x80
[ 1226.710145]  kthread+0x124/0x140
[ 1226.710147]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1226.710149]  ? kthread_create_on_node+0x70/0x70
[ 1226.710151]  ret_from_fork+0x25/0x30
[ 1349.590140] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[ 1349.590144]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1349.590145] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1349.590146] z_zvol          D    0 17045      2 0x00000000
[ 1349.590148] Call Trace:
[ 1349.590153]  __schedule+0x6eb/0xcd0
[ 1349.590155]  schedule+0x3d/0xd0
[ 1349.590159]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1349.590162]  ? wait_woken+0x80/0x80
[ 1349.590178]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1349.590180]  taskq_thread+0x254/0x480 [spl]
[ 1349.590183]  ? wake_up_q+0x80/0x80
[ 1349.590185]  kthread+0x124/0x140
[ 1349.590187]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1349.590189]  ? kthread_create_on_node+0x70/0x70
[ 1349.590191]  ret_from_fork+0x25/0x30
[ 1436.501551] zfs[27076]: segfault at 10 ip 00007f0bd40474b1 sp 00007fff83d42008 error 4 in libc-2.26.so[7f0bd3ef0000+1ae000]
[ 1472.470050] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[ 1472.470053]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1472.470054] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1472.470056] z_zvol          D    0 17045      2 0x00000000
[ 1472.470058] Call Trace:
[ 1472.470063]  __schedule+0x6eb/0xcd0
[ 1472.470065]  schedule+0x3d/0xd0
[ 1472.470069]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1472.470071]  ? wait_woken+0x80/0x80
[ 1472.470087]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1472.470090]  taskq_thread+0x254/0x480 [spl]
[ 1472.470092]  ? wake_up_q+0x80/0x80
[ 1472.470095]  kthread+0x124/0x140
[ 1472.470097]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1472.470098]  ? kthread_create_on_node+0x70/0x70
[ 1472.470100]  ret_from_fork+0x25/0x30
[ 1595.350031] INFO: task z_zvol:389 blocked for more than 120 seconds.
[ 1595.350034]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1595.350035] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1595.350036] z_zvol          D    0   389      2 0x00000000
[ 1595.350039] Call Trace:
[ 1595.350044]  __schedule+0x6eb/0xcd0
[ 1595.350046]  schedule+0x3d/0xd0
[ 1595.350050]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1595.350052]  ? wait_woken+0x80/0x80
[ 1595.350068]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1595.350071]  taskq_thread+0x254/0x480 [spl]
[ 1595.350073]  ? wake_up_q+0x80/0x80
[ 1595.350076]  kthread+0x124/0x140
[ 1595.350078]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1595.350079]  ? kthread_create_on_node+0x70/0x70
[ 1595.350081]  ? kthread_create_on_node+0x70/0x70
[ 1595.350082]  ret_from_fork+0x25/0x30
[ 1595.350106] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[ 1595.350107]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1595.350108] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1595.350109] z_zvol          D    0 17045      2 0x00000000
[ 1595.350110] Call Trace:
[ 1595.350112]  __schedule+0x6eb/0xcd0
[ 1595.350113]  schedule+0x3d/0xd0
[ 1595.350116]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1595.350117]  ? wait_woken+0x80/0x80
[ 1595.350130]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1595.350133]  taskq_thread+0x254/0x480 [spl]
[ 1595.350135]  ? wake_up_q+0x80/0x80
[ 1595.350137]  kthread+0x124/0x140
[ 1595.350139]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1595.350140]  ? kthread_create_on_node+0x70/0x70
[ 1595.350142]  ret_from_fork+0x25/0x30
[ 1718.230091] INFO: task z_zvol:389 blocked for more than 120 seconds.
[ 1718.230094]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1718.230095] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1718.230097] z_zvol          D    0   389      2 0x00000000
[ 1718.230099] Call Trace:
[ 1718.230103]  __schedule+0x6eb/0xcd0
[ 1718.230105]  schedule+0x3d/0xd0
[ 1718.230109]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1718.230112]  ? wait_woken+0x80/0x80
[ 1718.230127]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1718.230130]  taskq_thread+0x254/0x480 [spl]
[ 1718.230133]  ? wake_up_q+0x80/0x80
[ 1718.230135]  kthread+0x124/0x140
[ 1718.230137]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1718.230139]  ? kthread_create_on_node+0x70/0x70
[ 1718.230140]  ? kthread_create_on_node+0x70/0x70
[ 1718.230142]  ret_from_fork+0x25/0x30
[ 1718.230164] INFO: task z_zvol:17045 blocked for more than 120 seconds.
[ 1718.230166]       Tainted: P     U     O    4.13.14-1-ck-skylake #1
[ 1718.230167] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1718.230167] z_zvol          D    0 17045      2 0x00000000
[ 1718.230169] Call Trace:
[ 1718.230170]  __schedule+0x6eb/0xcd0
[ 1718.230172]  schedule+0x3d/0xd0
[ 1718.230175]  taskq_wait_outstanding+0x87/0xd0 [spl]
[ 1718.230176]  ? wait_woken+0x80/0x80
[ 1718.230190]  zvol_task_cb+0x1fa/0x5a0 [zfs]
[ 1718.230192]  taskq_thread+0x254/0x480 [spl]
[ 1718.230195]  ? wake_up_q+0x80/0x80
[ 1718.230196]  kthread+0x124/0x140
[ 1718.230198]  ? taskq_thread_should_stop+0x70/0x70 [spl]
[ 1718.230200]  ? kthread_create_on_node+0x70/0x70
[ 1718.230201]  ret_from_fork+0x25/0x30
[ 2342.854530] zfs[9384]: segfault at 10 ip 00007f43a3ebb4b1 sp 00007ffd2f425268 error 4 in libc-2.26.so[7f43a3d64000+1ae000]
[ 2343.138402] zfs[9544]: segfault at 10 ip 00007f505f1434b1 sp 00007ffdcb1d1e48 error 4 in libc-2.26.so[7f505efec000+1ae000]
[ 3239.855885] zfs[14132]: segfault at 10 ip 00007f75c5b7b4b1 sp 00007ffec4e010d8 error 4 in libc-2.26.so[7f75c5a24000+1ae000]
```

zdb (anonymised):
```
root@g ~ # zdb 
dozer:
    version: 5000
    name: 'dozer'
    state: 0
    txg: 4
    pool_guid: <number>
    errata: 0
    hostid: <number>
    hostname: 'g'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: <number>
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: <number>
            path: '/dev/mapper/g'
            devid: 'dm-uuid-CRYPT-LUKS1-<uuid>-g'
            whole_disk: 0
            metaslab_array: 256
            metaslab_shift: 31
            ashift: 9
            asize: 320062095360
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 129
            com.delphix:vdev_zap_top: 130
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
tank:
    version: 5000
    name: 'tank'
    state: 0
    txg: 893048
    pool_guid: <number>
    errata: 0
    hostid: <number>
    hostname: 'glock'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: <number>
        children[0]:
            type: 'disk'
            id: 0
            guid: <number>
            path: '/dev/mapper/h'
            devid: 'dm-uuid-CRYPT-LUKS1-<uuid>-h'
            whole_disk: 0
            metaslab_array: 256
            metaslab_shift: 30
            ashift: 12
            asize: 254978818048
            is_log: 0
            DTL: 120
            create_txg: 4
            com.delphix:vdev_zap_leaf: 58
            com.delphix:vdev_zap_top: 59
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

Happy to provide any additional info, just tell me what you want to know.

### PR DESCRIPTION
**Pull request by loli10K**
### Description

During a receive operation `zvol_create_minors_impl()` can wait needlessly for the prefetch thread because both share the same tasks queue.  This results in hung tasks:

```
<3>INFO: task z_zvol:5541 blocked for more than 120 seconds.
<3>      Tainted: P           O  3.16.0-4-amd64 #1
<3>"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

The first z_zvol:5541 (zvol_task_cb) is waiting for the long running traverse_prefetch_thread:260. We should not need to wait for anything since both "testpool" and "testpool/media" are not ZVOLs and have "snapdev=hidden".

```
(gdb) !cat /proc/spl/taskq
taskq                       act  nthr  spwn  maxt   pri  mina         maxa  cura      flags
spl_system_taskq/0            1     2     0    64   100     1   2147483647     1   80000005
	active: [260]traverse_prefetch_thread [zfs](0xffff88003347ae40)
	wait: 5541
spl_delay_taskq/0             0     1     0     4   100     1   2147483647     1   80000005
	delay: spa_deadman [zfs](0xffff880039924000)
z_zvol/1                      1     1     0     1   120     1   2147483647     2   80000000
	active: [5541]zvol_task_cb [zfs](0xffff88001fde6400)
	pend: zvol_task_cb [zfs](0xffff88001fde6800)
(gdb)  
(gdb) p *((zvol_task_t *) 0xffff88001fde6400)
$4 = {
  op = ZVOL_ASYNC_CREATE_MINORS, 
  pool = "testpool", '\000' <repeats 247 times>, 
  name1 = "testpool", '\000' <repeats 247 times>, 
  name2 = '\000' <repeats 255 times>, 
  source = (unknown: 0), 
  value = 18446744073709551615
}
(gdb)  
(gdb) p *((zvol_task_t *) 0xffff88001fde6800)
$5 = {
  op = ZVOL_ASYNC_CREATE_MINORS, 
  pool = "testpool", '\000' <repeats 247 times>, 
  name1 = "testpool/media", '\000' <repeats 241 times>, 
  name2 = '\000' <repeats 255 times>, 
  source = (unknown: 0), 
  value = 18446744073709551615
}
(gdb) !zfs get type,snapdev testpool/media
NAME            PROPERTY  VALUE       SOURCE
testpool/media  type      filesystem  -
testpool/media  snapdev   hidden      default
(gdb) !zfs get type,snapdev testpool
NAME      PROPERTY  VALUE       SOURCE
testpool  type      filesystem  -
testpool  snapdev   hidden      default
(gdb) 
```

Fix this by waiting for tasks on the system queue only if needed.

### Motivation and Context

Fix #6330 
Fix #6890 (this seems to be a duplicate)

### How Has This Been Tested?

EDIT: tested on current master on Debian8 builder receiving ~100GB of snapshot data.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by kpande** [comment]
@behlendorf I support that, more (future) tunables for prefetch would be greatly appreciated.

**Comment by trisk** [comment]
Yeah, we can still potentially get stuck behind the prefetcher if we're unlucky. Instead of a single `system_taskq`, they're lightweight enough that I would liberally create separate taskqs for `traverse_prefetch_thread`, `zvol_prefetch_minors_impl`, and even `zvol_free`.

**Comment by loli10K** [comment]
I agree, a dedicated taskq for the prefetcher looks more robust and clean; does it make sense to do a per-pool taskq like it was done for `spa_zvol_taskq` and `spa_upgrade_taskq`?

I am going to do some local testing and update the PR as soon as possible.

**Comment by behlendorf** [comment]
@loli10K I think making it per-pool would be a nice way to address this.

File: module/zfs/spa.c [hunk 1]
```diff
@@ -1186,6 +1186,14 @@ spa_activate(spa_t *spa, int mode)
 	spa->spa_zvol_taskq = taskq_create("z_zvol", 1, defclsyspri,
 	    1, INT_MAX, 0);
 
+	/*
+	 * Taskq dedicated to prefetcher threads: this is used to prevent the
+	 * pool traverse code to monopolize the global (and limited)
```
Comment (behlendorf) [inline module/zfs/spa.c]: s/to monopolize/from monopolizing/

File: module/zfs/spa.c [hunk 2]
```diff
@@ -1186,6 +1186,14 @@ spa_activate(spa_t *spa, int mode)
...
+	 * system_taskq by inappropriately scheduling long running tasks on it.
+	 */
+	spa->spa_prefetch_taskq = taskq_create("z_prefetch", boot_ncpus,
+	    defclsyspri, 1, INT_MAX, 0);
```
Comment (behlendorf) [inline module/zfs/spa.c]: Let's add the `TASKQ_DYNAMIC` flag.

**Comment by loli10K** [comment]
@behlendorf unfortunately that reproducer does not reproduce this specific issue, the thread that gets blocked is "send_traverse" on the send size, not "z_zvol" (zvol_task_cb) on the receive size.

To reproduce this issue we need(ed), at least, enough data to keep a traverse_prefetch_thread on the system_taskq and we must receive completely the first filesystem, otherwise no zvol_task_cb is run on the same system_taskq. I have a pool that meets this requirements: i was moving said pool to another system when i hit this issue, so i postponed my activities to debug and try to fix this.

**Comment by saurabhnanda** [comment]
Does this affect only the recv side or also the send side? If I have to upgrade zfs, is it enough to upgrade only the recv side?

**Comment by behlendorf** [comment]
This should only effect the recv side.
