### PR TITLE
Scan IOs should use ZIO_PRIORITY_SCRUB

### LINKED ISSUE #6921: IO latency skyrockets during sequential scrub
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 6.9
Linux Kernel                 | 4.9.62 (custom build)
Architecture                 | x86_64
ZFS Version                  | Git d4677269f286005768ae1a0fcd3389aa6015c4c7
SPL Version                  | Git zfsonlinux/spl@ed19bccfb651843fa208232b3a2d3d22a4152bc8

### Describe the problem you're observing
Since sequential scan was added (d4a72f23863382bdf6d0ae33196f5b5decbc48fd) performance of IO has been abysmal during a scrub. Playback of a simple 720p video during a scrub from the pool is not possible. Application latencies are on the order of multiple seconds as shown in the iostats below.

### Describe how to reproduce the problem
Any scrub of a large pool should be sufficient to reproduce the issue.

### Include any warning/errors/backtraces from the system logs
```
# zpool iostat -vl 1
                                                  capacity     operations     bandwidth    total_wait     disk_wait    syncq_wait    asyncq_wait  scrub
pool                                            alloc   free   read  write   read  write   read  write   read  write   read  write   read  write   wait
----------------------------------------------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
dehacked                                        6.46T  22.5T    148      0  3.68M      0     8s      -  196ms      -      -      -     7s      -      -
  raidz2                                        6.46T  22.5T    147      0  3.65M      0     8s      -  196ms      -      -      -     7s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:0      -      -     16      0   475K      0     8s      -  195ms      -      -      -     7s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:1      -      -     18      0   435K      0     8s      -  195ms      -      -      -     7s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:2      -      -     17      0   427K      0     8s      -  195ms      -      -      -     7s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:3      -      -     18      0   455K      0     8s      -  201ms      -      -      -     7s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:4        -      -     18      0   443K      0     8s      -  195ms      -      -      -     7s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:5        -      -     18      0   435K      0     8s      -  195ms      -      -      -     7s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:6        -      -     18      0   535K      0     8s      -  195ms      -      -      -     7s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:7        -      -     17      0   535K      0     8s      -  201ms      -      -      -     7s      -      -
----------------------------------------------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
dehacked                                        6.46T  22.5T    143      0  3.16M      0    12s      -  196ms      -      -      -    12s      -      -
  raidz2                                        6.46T  22.5T    143      0  3.16M      0    12s      -  196ms      -      -      -    12s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:0      -      -     17      0   371K      0    12s      -  195ms      -      -      -    12s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:1      -      -     17      0   355K      0    12s      -  195ms      -      -      -    12s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:2      -      -     17      0   487K      0    12s      -  200ms      -      -      -    12s      -      -
    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:3      -      -     18      0   515K      0    12s      -  190ms      -      -      -    12s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:4        -      -     17      0   407K      0    12s      -  200ms      -      -      -    12s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:5        -      -     17      0   431K      0    12s      -  195ms      -      -      -    12s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:6        -      -     17      0   331K      0    12s      -  195ms      -      -      -    12s      -      -
    usb-ST4000VN_008-2DR166_152D00539000-0:7        -      -     16      0   335K      0    12s      -  194ms      -      -      -    12s      -      -
----------------------------------------------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----

# iostat -dmx 1 sd[e-l]
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sde               0.00     0.00   17.00    0.00     0.37     0.00    44.24     3.00  169.71  169.71    0.00  58.82 100.00
sdf               0.00     0.00   17.00    0.00     0.40     0.00    48.47     3.00  178.00  178.00    0.00  58.82 100.00
sdg               0.00     0.00   16.00    0.00     0.35     0.00    45.00     3.00  172.56  172.56    0.00  62.50 100.00
sdh               0.00     0.00   18.00    0.00     0.45     0.00    51.56     3.00  165.72  165.72    0.00  55.56 100.00
sdi               0.00     0.00   16.00    0.00     0.34     0.00    44.00     3.00  179.69  179.69    0.00  62.50 100.00
sdj               0.00     0.00   18.00    0.00     0.36     0.00    41.33     3.00  163.72  163.72    0.00  55.56 100.00
sdk               0.00     0.00   18.00    0.00     0.42     0.00    47.56     3.00  167.83  167.83    0.00  55.56 100.00
sdl               0.00     0.00   18.00    0.00     0.42     0.00    48.00     3.00  169.22  169.22    0.00  55.56 100.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sde               0.00     0.00   18.00    0.00     0.50     0.00    57.33     3.00  169.00  169.00    0.00  55.56 100.00
sdf               0.00     0.00   19.00    0.00     0.52     0.00    56.00     3.00  161.32  161.32    0.00  52.63 100.00
sdg               0.00     0.00   19.00    0.00     0.47     0.00    50.95     3.00  167.58  167.58    0.00  52.63 100.00
sdh               0.00     0.00   19.00    0.00     0.46     0.00    49.68     3.00  160.16  160.16    0.00  52.63 100.00
sdi               0.00     0.00   19.00    0.00     0.48     0.00    51.79     3.00  161.00  161.00    0.00  52.63 100.00
sdj               0.00     0.00   19.00    0.00     0.46     0.00    49.68     3.00  161.16  161.16    0.00  52.63 100.00
sdk               0.00     0.00   19.00    0.00     0.48     0.00    51.79     3.00  158.11  158.11    0.00  52.63 100.00
sdl               0.00     0.00   18.00    0.00     0.48     0.00    55.11     3.00  163.00  163.00    0.00  55.56 100.00

  pool: dehacked
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: scrub paused since Sun Dec  3 10:44:30 2017
	scrub started on Sun Dec  3 10:44:30 2017
	4.53T scanned, 576K issued, 6.46T total
	0B repaired, 0.00% done
config:

	NAME                                            STATE     READ WRITE CKSUM
	dehacked                                        ONLINE       0     0     0
	  raidz2-0                                      ONLINE       0     0     0
	    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:0  ONLINE       0     0     0
	    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:1  ONLINE       0     0     0
	    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:2  ONLINE       0     0     0
	    usb-WDC_WD40_EFRX-68N32N0_152D00539000-0:3  ONLINE       0     0     0
	    usb-ST4000VN_008-2DR166_152D00539000-0:4    ONLINE       0     0     0
	    usb-ST4000VN_008-2DR166_152D00539000-0:5    ONLINE       0     0     0
	    usb-ST4000VN_008-2DR166_152D00539000-0:6    ONLINE       0     0     0
	    usb-ST4000VN_008-2DR166_152D00539000-0:7    ONLINE       0     0     0

```

### Other
```
options zfs zfs_arc_max=9000000000 l2arc_norw=0
options spl spl_taskq_thread_dynamic=0
```

Pool is made of 8 disks in a single raidz2 on a USB 3.0 8-drive external enclosure. Latency is a bit high overall as a result but this is clearly ZFS not issuing IO very well.

### PR DESCRIPTION
**Pull request by tcaputi**
When sequential scrubs were merged, all calls to arc_read()
(includeing prefetch IOs) were given ZIO_PRIORITY_ASYNC_READ.
Unfortunately, this behaves badly with an existing issue where
prefetch IOs cannot be reprioritized after the issue. The
result is that synchronous reads end up in the same vdev_queue
as the scrub IOs and can have (in some workloads) seconds of
latency. This patch ensures that all scrub IOs are given
ZIO_PRIORITY_SCRUB.

Fixes #6921

Signed-off-by: Tom Caputi <tcaputi@datto.com>

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by dweeezil** [comment]
Although this change looks perfectly reasonable to me, I'll note that all of those ```arc_read()``` calls had been using ```ZIO_PRIORITY_ASYNC_READ``` in the past so it must have mainly been the newly-added one in ```dsl_scan_prefetch_thread()``` that was the main cause of the issue reported in #6921.

Pinging @grwilson as to why ```ZIO_PRIORITY_ASYNC_READ``` was used to begin with in the scrub/scan prefetching, which appears to have been introduced in openzfs/openzfs@b16da2e29e074fb6eaeadc4fd7d17ae7340ba240.

**Comment by tcaputi** [comment]
> Although this change looks perfectly reasonable to me, I'll note that all of those arc_read() calls had been using ZIO_PRIORITY_ASYNC_READ in the past so it must have mainly been the newly-added one in dsl_scan_prefetch_thread() that was the main cause of the issue reported in #6921.

You are correct. The new prefetcher is meant to keep the vdev queues as full as possible without overwhelming them. It was supposed to rely on the vdev queue prioritization to prevent starving real workloads, which seems to work for the most part. This only seems to break down when the vdev queues can't distinguish between user IOs and scrub IOs that this becomes a problem.

**Comment by grwilson** [comment]
I'm not convinced this will completely solve the problem. It will prevent a long queue of prefetched scan I/Os from blocking other async reads but any demand read that is waiting for a block that has been prefetched could still suffer the same performance delay. This sounds very similar to a problem we had in the old scrub code that lead to the need to add this logic:

**Comment by behlendorf** [comment]
Right, I suspect that this won't be 100% of the needed fix but it is expected to help for the reasons described.  Plug it will resolve a tiny bug where some scrub related IO is not reported under the scrub column in the extended `zpool iostat` output.

```
$ zpool iostat -r
                                                                        |||||
                                                                        vvvvv
tank          sync_read    sync_write    async_read    async_write      scrub   
req_size      ind    agg    ind    agg    ind    agg    ind    agg    ind    agg
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
512            24      0      0      0      0      0     89      0      0      0
...
```

@grwilson to address the concern you mention I think we're going to want to implement the functionality proposed in `arc_read()` to convert an outstanding prefetch in to a synchronous read.  As reported in #6921 we know this case is now happening since we do see the `sync_wait_for_async` arcstat being incremented.  I'd expect this change to help mitigate the very worst of the starvation.

```
                        if ((hdr->b_flags & ARC_FLAG_PRIO_ASYNC_READ) &&
                            priority == ZIO_PRIORITY_SYNC_READ) {
                                /*
                                 * This sync read must wait for an
                                 * in-progress async read (e.g. a predictive
                                 * prefetch).  Async reads are queued
                                 * separately at the vdev_queue layer, so
                                 * this is a form of priority inversion.
                                 * Ideally, we would "inherit" the demand
                                 * i/o's priority by moving the i/o from
                                 * the async queue to the synchronous queue,
                                 * but there is currently no mechanism to do
                                 * so.  Track this so that we can evaluate
                                 * the magnitude of this potential performance
                                 * problem.
```

Adding some kind of throttle is definitely worth exploring too when there's contending important IO, like the previous scrub code, let's just be careful to avoid introducing any unnecessary delays.  The new scrub code does a very good job keeping the drives at near 100% utilization which is nice as long as we're submitting the right IOs.

File: include/sys/arc_impl.h [hunk 1]
```diff
@@ -169,6 +169,8 @@ typedef struct l1arc_buf_hdr {
 	/* self protecting */
 	refcount_t		b_refcnt;
 
+	/* protected by HDR_IO_IN_PROGRESS() */
+	zio_t			*b_zio;
```
[the remark this answers is not in the document]
Comment (tcaputi) [reply include/sys/arc_impl.h]: > In this specific case a better trade off is to probably add some lookup logic to find the relevant zio on the pending queue.

I'm not really sure if this is possible. @grwilson and I were talking about this a bit yesterday and the problem here is that raidz and gang blocks would make it really hard to just lookup zios in the queues.

> We want to keep the l1arc_buf_hdr as small as possible to maximize the useful ARC size. Adding a field for this particular rare case feels a bit extravagant.

I was thinking about this a little bit. I could put the pointer to the zio in the `arc_callback_t`, which is a much more transient struct. Would that make more sense? I'm also looking at the structs in `arc_impl.h` and we actually have a few opportunities there to compact `arc_buf_hdr_t` if that is important to us....

> It forces us to hold the hash_lock longer which in the past has been a point on contention.

So I will note that we are not holding the lock across any kind of IO (other than the one kmem_zalloc() which could theoretically require a swap operation). I don't think this will really have that bad of an impact on performance. The alternative would be to just retake the lock to assign the `zio` to the `hdr` and force the `HDR_IO_IN_PROGRESS()` code to loop back to `top` if it encountered a NULL pointer there (which would assume that the pointer would get filled in soon).

[the remark this answers is not in the document]
Comment (behlendorf) [reply include/sys/arc_impl.h]: > I'm not really sure if this is possible.

Indeed, that is an annoying complication.  Ahh well.

> I was thinking about this a little bit. I could put the pointer to the zio in the arc_callback_t, which is a much more transient struct. Would that make more sense? 

If possible I think it's worth keeping the `l1arc_buf_hdr` as small as possible.  It's not particularly uncommon for a system to have a few million of these allocated which does add up.

> have a few opportunities there to compact arc_buf_hdr_t if that is important to us....

If we can, we should.

> So I will note that we are not holding the lock across any kind of IO.

Yup, I agree it shouldn't be a big problem as long as the hash table is correctly sized but I did want to mention it as a potential concern.  I'm OK with the locking change, although let's avoid dropping and reacquiring it in `arc_read()`.  It a little uglier but better to drop it in the conditionals before `goto out;` then there's no need to reacquire.

[the remark this answers is not in the document]
Comment (tcaputi) [reply include/sys/arc_impl.h]: > If possible I think it's worth keeping the l1arc_buf_hdr as small as possible. It's not particularly uncommon for a system to have a few million of these allocated which does add up.

OK. I'll make the change.

> Yup, I agree it shouldn't be a big problem as long as the hash table is correctly sized but I did want to mention it as a potential concern. I'm OK with the locking change, although let's avoid dropping and reacquiring it in arc_read(). It a little uglier but better to drop it in the conditionals before goto out; then there's no need to reacquire.

I can't really do that without impacting performance because I need to drop the lock for the `zio_wait()` . This will only reacquire the lock in the case of a synchronous `arc_read()` where the L2ARC read failed.

**Comment by tcaputi** [comment]
@behlendorf Updated the PR to address your comments.

**Comment by tcaputi** [comment]
I did a little testing before I submitted this. I wrote out a 6GB file onto my 8GB virtual hard drive. Then in one shell I repeatedly ran `zpool scrub` in a loop while in another I repeatedly used `pv` to read the file out in its entirety to `/dev/null`.

When the scrub wasn't running `pv` was able to dump the file at about 465MB/s. Once the scrub started, It ran pretty consistently at 300MB/s until the scrub finished. During this time, the new `async_upgrade_sync` arcstat steadily incremented.

This is just on my tiny VM, but I think it is evidence that the problem should be resolved.

File: module/zfs/zio.c [hunk 2]
```diff
@@ -1963,14 +1963,16 @@ zio_reexecute(zio_t *pio)
 	 * cannot be affected by any side effects of reexecuting 'cio'.
 	 */
 	zio_link_t *zl = NULL;
+	mutex_enter(&pio->io_lock);
```
Comment (grwilson) [inline module/zfs/zio.c]: Is this really required here?

File: module/zfs/zio.c [hunk 3]
```diff
@@ -3474,6 +3476,25 @@ zio_vdev_io_done(zio_t *zio)
...
+{
+	zio_t *cio, *cio_next;
+	zio_link_t *zl = NULL;
+
+	if (pio->io_vd != NULL && pio->io_vd->vdev_ops->vdev_op_leaf &&
+	    (pio->io_type == ZIO_TYPE_READ || pio->io_type == ZIO_TYPE_WRITE)) {
+		vdev_queue_change_io_priority(pio, priority);
+	}
+
+	mutex_enter(&pio->io_lock);
```
Comment (grwilson) [inline module/zfs/zio.c]: I'm assuming you're grabbing the locks to prevent any new children while you walk them all. Is that the idea here? Is it really required?

File: module/zfs/zio.c [hunk 4]
```diff
@@ -3474,6 +3476,25 @@ zio_vdev_io_done(zio_t *zio)
 	return (ZIO_PIPELINE_CONTINUE);
 }
 
+void
+zio_change_priority(zio_t *pio, zio_priority_t priority)
+{
+	zio_t *cio, *cio_next;
+	zio_link_t *zl = NULL;
+
+	if (pio->io_vd != NULL && pio->io_vd->vdev_ops->vdev_op_leaf &&
```
Comment (grwilson) [inline module/zfs/zio.c]: what if the I/O has not been queued yet, how are you changing its priority?

File: module/zfs/dsl_scan.c [hunk 5]
```diff
@@ -1529,7 +1529,7 @@ dsl_scan_prefetch_thread(void *arg)
 		/* issue the prefetch asynchronously */
 		(void) arc_read(scn->scn_zio_root, scn->scn_dp->dp_spa,
 		    &spic->spic_bp, dsl_scan_prefetch_cb, spic->spic_spc,
-		    ZIO_PRIORITY_ASYNC_READ, zio_flags, &flags, &spic->spic_zb);
+		    ZIO_PRIORITY_SCRUB, zio_flags, &flags, &spic->spic_zb);
```
Comment (grwilson) [inline module/zfs/dsl_scan.c]: Given the intent of this fix, do we still need to change the priority to SCRUB? Will these inherit the priority of a demand read?

File: module/zfs/zio.c (hunk 3 above)
Comment (tcaputi) [reply module/zfs/zio.c]: Yes it is. I hit a NULL pointer dereference when running the code without the lock.

File: module/zfs/dsl_scan.c (hunk 5 above)
Comment (tcaputi) [reply module/zfs/dsl_scan.c]: I think these IOs logically should be rate-limited based on the scrub vdev queue. Incidentally, this change resolves another small issue where currently `zpool iostat -q` scrub IOs are listed as async reads which is confusing because "I have a scrub running, why isn't it doing anything?"

So its probably not necessary to resolve #6921 but I think it is appropriate.

File: module/zfs/zio.c (hunk 2 above)
Comment (tcaputi) [reply module/zfs/zio.c]: Yes, see the comment below.

File: module/zfs/zio.c (hunk 4 above)
Comment (tcaputi) [reply module/zfs/zio.c]: Hmmmm. That's a good point. I probably could just change the priority on the zio in this case which should cause any children to inherit the new priority. I'm a bit concerned about locking `zio->io_priority` though. I could probably just take out the `zio->io_lock` for that and for the assignment in `vdev_queue_io()`.  What do you think?

File: module/zfs/arc.c [hunk 6]
```diff
@@ -5911,32 +5911,20 @@ arc_read(zio_t *pio, spa_t *spa, const blkptr_t *bp,
...
-				 * we issued it sooner than we would have
-				 * without the prefetch.
+				 * This is a sync read that needs to wait for
+				 * an in-flight async read. Request that the
+				 * zio have its priority upgraded.
 				 */
+				ASSERT3P(head_zio, !=, NULL);
+				zio_change_priority(head_zio, priority);
 				DTRACE_PROBE1(arc__sync__wait__for__async,
 				    arc_buf_hdr_t *, hdr);
```
Comment (tcaputi) [inline module/zfs/arc.c]: @behlendorf I just noticed this dtrace probe. What should I do with it? Should I just rename it (and in `trace_arc.h`)?

Comment (behlendorf) [reply module/zfs/arc.c]: Yes, let's change the names to match.

File: module/zfs/dsl_scan.c (hunk 5 above)
Comment (grwilson) [reply module/zfs/dsl_scan.c]: These aren't the real scrub I/Os but just the ones required to traverse the metadata. So the question is should they show up as scrub I/Os or just normal async reads. Did I miss where these get promoted if a demand read is issued on for the same block?

File: module/zfs/vdev_queue.c [hunk 7]
```diff
@@ -803,6 +803,48 @@ vdev_queue_io_done(zio_t *zio)
...
+void
+vdev_queue_change_io_priority(zio_t *zio, zio_priority_t priority)
+{
+	vdev_queue_t *vq = &zio->io_vd->vdev_queue;
+	avl_tree_t *tree;
+
+	ASSERT3U(zio->io_priority, <, ZIO_PRIORITY_NUM_QUEUEABLE);
+	ASSERT3U(priority, <, ZIO_PRIORITY_NUM_QUEUEABLE);
+
+	if (zio->io_type == ZIO_TYPE_READ) {
```
Comment (grwilson) [inline module/zfs/vdev_queue.c]: Can you explain why we need this? And also when would we want to change the priority of a WRITE?

Comment (tcaputi) [reply module/zfs/vdev_queue.c]: The block of code is there because it is also in `vdev_queue_io()` and I wanted the same semantics. I don't know when we would currently want to change the priority of a write, but I didn't see any reason to exclude it either.

File: module/zfs/zio.c (hunk 4 above)
Comment (grwilson) [reply module/zfs/zio.c]: This should be fine since we don't really change the priority after `zio_create` (except that vdev_queue_io case which I'm going to nuke).

File: module/zfs/zio.c (hunk 3 above)
Comment (grwilson) [reply module/zfs/zio.c]: Can you add an ASSERT(MUTEX_HELD(pio->io_lock)) in `zio_walk_children`?

File: module/zfs/zio.c (hunk 4 above)
Comment (grwilson) [reply module/zfs/zio.c]: BTW can't we just add something like this:
```
else if (pio->io_priority != priority)
        pio->io_priority = priority;
```

File: module/zfs/vdev_queue.c (hunk 7 above)
Comment (grwilson) [reply module/zfs/vdev_queue.c]: I'm not sure we want to add code that is never called.

File: module/zfs/dsl_scan.c (hunk 5 above)
Comment (tcaputi) [reply module/zfs/dsl_scan.c]: > So the question is should they show up as scrub I/Os or just normal async reads.

In the past, these were always given a priority of "async read". It doesn't really make sense to upgrade any of these reads since we don't want them to interfere with normal user IO. The async read category also doesnt seem great now because then they can get intermixed with user prefetches, which isn't the end of the world with the new priority upgrade code. However, it will mean that if the dmu tries to issue a prefetch for a block that could get lost in the sea of scrub prefetches. Therefore, the only priority that makes sense to me is "scrub". 

> Did I miss where these get promoted if a demand read is issued on for the same block?

If you are talking about a user's demand read that will be done by the user's `arc_read()`. If you are talking about the scrub's demand read it doesn't happen with the code the way it is right now for the reasons above.

File: module/zfs/zio.c (hunk 4 above)
Comment (tcaputi) [reply module/zfs/zio.c]: @grwilson Would you mind giving an opinion here?

File: module/zfs/dsl_scan.c (hunk 5 above)
Comment (grwilson) [reply module/zfs/dsl_scan.c]: What about the case where we have a demand read for a block that is being prefetched by the scrub metadata traversal? If these were async reads, then it would promote them to sync reads since someone was waiting on it. If the metadata traversal is a scrub priority then the user that issued the demand read must still wait. It feels like the promotion should take place here too.

File: module/zfs/zio.c (hunk 4 above)
Comment (grwilson) [reply module/zfs/zio.c]: I don't think you need to grab the `io_lock` and can just change the priority and doing it in an `else` clause seems simple enough.  By doing this you end up changing the priority as you walk down the children tree.

File: module/zfs/dsl_scan.c (hunk 5 above)
Comment (tcaputi) [reply module/zfs/dsl_scan.c]: The promotion will take place in this case. The scrub prectch will come in ``arc_read(PRIORITY_SCRUB)` as demand read will come in with `arc_read(PRIORITY_SYNC_READ)`, which will request to upgrade the priority to `PRIORITY_SYNC_READ`

File: module/zfs/vdev_queue.c (hunk 7 above)
Comment (tcaputi) [reply module/zfs/vdev_queue.c]: Would you prefer me to ASSERT that the call is always a read?

File: module/zfs/zio.c (hunk 4 above)
Comment (tcaputi) [reply module/zfs/zio.c]: Could that possibly race with `vdev_queue_io()` in such a way that `vdev_queue_io_add()` adds the IO to the wrong tree?

File: module/zfs/zio.c (hunk 3 above)
Comment (tcaputi) [reply module/zfs/zio.c]: Will do

File: module/zfs/vdev_queue.c (hunk 7 above)
Comment (grwilson) [reply module/zfs/vdev_queue.c]: Yes, I think you can rip this whole block out and add an ASSERT.

File: module/zfs/zio.c (hunk 4 above)
Comment (grwilson) [reply module/zfs/zio.c]: I don't think this would be possible for the case since the children will have inherited the parent's priority correctly.

File: module/zfs/dsl_scan.c (hunk 5 above)
Comment (grwilson) [reply module/zfs/dsl_scan.c]: Maybe I'm missing something. The promotion happens when we have the following condition:
```if ((hdr->b_flags & ARC_FLAG_PRIO_ASYNC_READ) &&
  			    priority == ZIO_PRIORITY_SYNC_READ) {
```
In the case I was describing, would the PRIORITY_SCRUB I/O set the ARC_FLAG_PRIO_ASYNC_READ flag. I don't think I saw that. If not, then it should so that we promote the I/O. Sorry if I missed that.

Comment (tcaputi) [reply module/zfs/dsl_scan.c]: Oh. I see what you mean. I will fix that.

**Comment by behlendorf** [comment]
It looks like we are going to have to do something with  ZIO_TYPE_WRITE.  The `redundancy_001_pos` test case hit the newly added ASSERT while walking one of the children.

http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20i686%20%28TEST%29/builds/5100/steps/shell_8/logs/console

```
Test: /usr/share/zfs/zfs-tests/tests/functional/redundancy/redundancy_001_pos [KILLED]
```

```
VERIFY3(pio->io_type == ZIO_TYPE_READ) failed (2 == 1)
PANIC at zio.c:3494:zio_change_priority()
Showing stack for process 23369
CPU: 0 PID: 23369 Comm: cksum Tainted: P           OX 3.13.0-133-generic #182-Ubuntu
Call Trace:
 [<c165fe02>] dump_stack+0x58/0x72
 [<d5538bf1>] spl_dumpstack+0x41/0x50 [spl]
 [<d5538c96>] spl_panic+0x96/0xe0 [spl]
 [<d60acc62>] zio_change_priority+0x62/0x1b0 [zfs]
 [<d60acce8>] zio_change_priority+0xe8/0x1b0 [zfs]
 [<d60acce8>] zio_change_priority+0xe8/0x1b0 [zfs]
 [<d5f818e1>] arc_read+0x831/0x1db0 [zfs]
 [<d5f908eb>] dbuf_read+0x99b/0x13e0 [zfs]
 [<d5fa3f5f>] dmu_buf_hold_array_by_dnode+0x3bf/0x730 [zfs]
 [<d5fa59e1>] dmu_read_uio_dnode+0x51/0x150 [zfs]
 [<d5fa5b2f>] dmu_read_uio_dbuf+0x4f/0x70 [zfs]
 [<d6084112>] zfs_read+0x152/0x4e0 [zfs]
 [<d60b8dad>] zpl_read_common_iovec.constprop.7+0x6d/0x100 [zfs]
 [<d60b8ed0>] zpl_aio_read+0x90/0xc0 [zfs]
 [<c117c987>] do_sync_read+0x57/0x90
 [<c117d0b8>] vfs_read+0x78/0x140
 [<c117d839>] SyS_read+0x49/0x90
```

**Comment by tcaputi** [comment]
@behlendorf I will add the handling I originally had back in. George and I took it out because we thought it was dead code.

**Comment by tcaputi** [comment]
It looks like putting the handling back in solved the problem. @behlendorf is there anything else keeping this from being merged?

File: module/zfs/vdev_queue.c [hunk 8]
```diff
@@ -803,6 +803,48 @@ vdev_queue_io_done(zio_t *zio)
...
+		if (priority != ZIO_PRIORITY_SYNC_READ &&
+		    priority != ZIO_PRIORITY_ASYNC_READ &&
+		    priority != ZIO_PRIORITY_SCRUB)
+			priority = ZIO_PRIORITY_ASYNC_READ;
+	} else {
+		ASSERT(zio->io_type == ZIO_TYPE_WRITE);
+		if (priority != ZIO_PRIORITY_SYNC_WRITE &&
+		    priority != ZIO_PRIORITY_ASYNC_WRITE)
+			priority = ZIO_PRIORITY_ASYNC_WRITE;
```
Comment (grwilson) [inline module/zfs/vdev_queue.c]: I'm changing this logic from `vdev_queue_io` so this won't be necessary. I can clean this up so that we only promote ASYNC writes that are part of a repair I/O.

**Comment by MyPod** [comment]
This PR introduced a couple of empty files in the root of the project

**Comment by tcaputi** [comment]
I don't know how that happened.... That didn't show up when I rebased... @behlendorf How do you want to handle this? Should I make a new PR?

**Comment by behlendorf** [comment]
Whoops, @tcaputi yes please.

**Comment by tcaputi** [comment]
Pushed the fix to #6990. Sorry everyone :(

**Comment by DeHackEd** [comment]
So, might this cause imports to become significantly slower if a scrub is in progress?

```
root     24184  0.0  0.0 2280028 5736 pts/50   D+   22:10   0:00 zpool import -d /dev/disk/by-id dehacked -N
# cat /proc/24184/stack
[<ffffffffc1103d8e>] spa_open_common+0x5e/0x430 [zfs]
[<ffffffffc11041cf>] spa_get_stats+0x4f/0x4c0 [zfs]
[<ffffffffc113d54c>] zfs_ioc_pool_stats+0x2c/0x70 [zfs]
[<ffffffffc114016c>] zfsdev_ioctl+0x5bc/0x600 [zfs]
[<ffffffffa517601d>] do_vfs_ioctl+0x8d/0x5b0
[<ffffffffa517657c>] SyS_ioctl+0x3c/0x70
[<ffffffffa5521b20>] entry_SYSCALL_64_fastpath+0x13/0x94
[<ffffffffffffffff>] 0xffffffffffffffff
```

Otherwise, IO performance has improved dramatically with this applied during a scrub. Multi-second latencies remain in `zpool iostat -l` but they are now part of the scrub column.

**Comment by tcaputi** [comment]
I definitely wouldn't expect it to.... What kind of difference in import time are you seeing?

**Comment by tcaputi** [comment]
Also, since sequential scrubs were merged, we postpone scrubs for a few txgs to allow the pool to be imported faster. Was the pool cleanly exported before? If not, it will take longer to import later.

**Comment by behlendorf** [comment]
Right, I wouldn't expect slower imports for the reasons @tcaputi mentioned.  You can safely increase `SCAN_IMPORT_WAIT_TXGS` in the source which will further delay in-progress scrubs from starting after an import.  The current setting of 5 TXGs might not be large enough.

**Comment by dweeezil** [comment]
@tcaputi Could you please comment on the swapping of the parent/child mutex lock ordering in this patch.  It seems to be outside the scope of the comments in the commit log.  The reason I'm asking is because I'm occasionally asked to port other changes to the stable branch and recently ported the enhanced deadman but it required this re-ordering to prevent deadlocks between the deadman and `zio_remove_child()` (in the z_rd_int threads).  I'll tag @behlendorf, too because he might be interested to hear this.

**Comment by dweeezil** [comment]
@tcaputi Thanks for the insight.  So it sounds like the lock re-ordering done as part of this patch should really be considered to be associated with a76f3d0.

**Comment by behlendorf** [comment]
@dweeezil yes, a76f3d0 was effectively a followup fix for this patch.
