### PR TITLE
zvol: allow rename of in use ZVOL dataset

### LINKED ISSUE #6263: PANIC at zvol.c:1165:zvol_resume()
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | Stretch
Linux Kernel                 | 4.9.30-2+deb9u1
Architecture                 | amd64
ZFS Version                  | 0.7.0-rc4_64_g0241e491a
SPL Version                  | 0.7.0-rc4_4_gac48361

### Describe the problem you're observing
While receiving a zvol from another machine, I obtained this:

```
[238797.610918] VERIFY3(zv->zv_objset->os_dsl_dataset->ds_owner == zv) failed (          (null) == ffff931c97dc3400)
[238797.612947] PANIC at zvol.c:1165:zvol_resume()
[238797.614940] Showing stack for process 10784
[238797.616951] CPU: 0 PID: 10784 Comm: zfs Tainted: G           O    4.9.0-3-amd64 #1 Debian 4.9.30-2+deb9u1
[238797.619117] Hardware name: Gigabyte Technology Co., Ltd. GA-78LMT-USB3 6.0/GA-78LMT-USB3 6.0, BIOS F2 11/25/2014
[238797.621219]  0000000000000000 ffffffff8dd286e4 ffffffffc0dcbfec ffffb083029079e0
[238797.623331]  ffffffffc052535b ffff931c78582140 ffffffff00000030 ffffb083029079f0
[238797.625468]  ffffb08302907990 2833594649524556 6f5f767a3e2d767a 6f3e2d7465736a62
[238797.627629] Call Trace:
[238797.629779]  [<ffffffff8dd286e4>] ? dump_stack+0x5c/0x78
[238797.631967]  [<ffffffffc052535b>] ? spl_panic+0xbb/0xf0 [spl]
[238797.634118]  [<ffffffff8e00380e>] ? mutex_lock+0xe/0x30
[238797.636379]  [<ffffffffc0cb1bd0>] ? rrw_exit+0x40/0x130 [zfs]
[238797.638516]  [<ffffffff8e00380e>] ? mutex_lock+0xe/0x30
[238797.640741]  [<ffffffffc0c79902>] ? dmu_objset_from_ds+0x62/0x140 [zfs]
[238797.642967]  [<ffffffffc0c79a53>] ? dmu_objset_hold+0x73/0xc0 [zfs]
[238797.645203]  [<ffffffffc0d3a2d8>] ? zvol_resume+0x108/0x1b0 [zfs]
[238797.647449]  [<ffffffffc0d073d8>] ? zfs_ioc_recv_impl+0x828/0x10a0 [zfs]
[238797.649726]  [<ffffffffc0d07e61>] ? zfs_ioc_recv+0x211/0x340 [zfs]
[238797.651991]  [<ffffffffc0cc82da>] ? spa_name_compare+0xa/0x20 [zfs]
[238797.654171]  [<ffffffffc01c1141>] ? avl_find+0x51/0x90 [zavl]
[238797.656408]  [<ffffffffc0cc717e>] ? spa_lookup+0x5e/0x80 [zfs]
[238797.658579]  [<ffffffff8dbdf99e>] ? __kmalloc+0x17e/0x560
[238797.660718]  [<ffffffff8dca2171>] ? security_capable+0x41/0x60
[238797.662876]  [<ffffffff8da80b33>] ? ns_capable_common+0x63/0x80
[238797.665121]  [<ffffffffc0cb08cd>] ? priv_policy.isra.1.part.2+0xd/0x20 [zfs]
[238797.667369]  [<ffffffffc0d052fe>] ? zfsdev_ioctl+0x73e/0x890 [zfs]
[238797.669555]  [<ffffffff8dbb384b>] ? handle_mm_fault+0xf7b/0x1390
[238797.671748]  [<ffffffff8dc161cf>] ? do_vfs_ioctl+0x9f/0x600
[238797.673943]  [<ffffffff8dc167a4>] ? SyS_ioctl+0x74/0x80
[238797.676131]  [<ffffffff8e00627b>] ? system_call_fast_compare_end+0xc/0x9b
```

### Describe how to reproduce the problem
This seems to happen infrequently on zfs receive. I don't have a 100% way to reproduce it, but it has happened a few times and forced me to reboot the machine involved as the pool affected would become unresponsive (zfs and zpool commands becoming unresponsive, no I/O possible from VMs running on the same pool)

The command used was
`zfs send -Rv mov/stretch-git@send | ssh root@192.168.2.7 zfs recv -uv data/virt/git`
however I have had this happen even locally (between two different pools on the same machine)

If anything else is needed, I have not yet rebooted this system, but will have to soon.

### PR DESCRIPTION
**Pull request by loli10K**
### Motivation and Context

Fix #6263

### Description

NOTE: this is a tentative fix.

While ZFS allow renaming of in use ZVOLs at the DSL level without issues the ZVOL layer does not correctly update the renamed dataset if the device node is open (zv->zv_open_count > 0): trying to access the stale dataset name, for instance during a zfs receive, will cause the following failure:

```
VERIFY3(zv->zv_objset->os_dsl_dataset->ds_owner == zv) failed ((null) == ffff8800dbb6fc00)
PANIC at zvol.c:1255:zvol_resume()
Showing stack for process 1390
CPU: 0 PID: 1390 Comm: zfs Tainted: P           O  3.16.0-4-amd64 #1 Debian 3.16.51-3
Hardware name: Bochs Bochs, BIOS Bochs 01/01/2011
 0000000000000000 ffffffff8151ea00 ffffffffa0758a80 ffff88028aefba30
 ffffffffa0417219 ffff880037179220 ffffffff00000030 ffff88028aefba40
 ffff88028aefb9e0 2833594649524556 6f5f767a3e2d767a 6f3e2d7465736a62
Call Trace:
 [<0>] ? dump_stack+0x5d/0x78
 [<0>] ? spl_panic+0xc9/0x110 [spl]
 [<0>] ? mutex_lock+0xe/0x2a
 [<0>] ? zfs_refcount_remove_many+0x1ad/0x250 [zfs]
 [<0>] ? rrw_exit+0xc8/0x2e0 [zfs]
 [<0>] ? mutex_lock+0xe/0x2a
 [<0>] ? dmu_objset_from_ds+0x9a/0x250 [zfs]
 [<0>] ? dmu_objset_hold_flags+0x71/0xc0 [zfs]
 [<0>] ? zvol_resume+0x178/0x280 [zfs]
 [<0>] ? zfs_ioc_recv_impl+0x88b/0xf80 [zfs]
 [<0>] ? zfs_refcount_remove_many+0x1ad/0x250 [zfs]
 [<0>] ? zfs_ioc_recv+0x1c2/0x2a0 [zfs]
 [<0>] ? dmu_buf_get_user+0x13/0x20 [zfs]
 [<0>] ? __alloc_pages_nodemask+0x166/0xb50
 [<0>] ? zfsdev_ioctl+0x896/0x9c0 [zfs]
 [<0>] ? handle_mm_fault+0x464/0x1140
 [<0>] ? do_vfs_ioctl+0x2cf/0x4b0
 [<0>] ? __do_page_fault+0x177/0x410
 [<0>] ? SyS_ioctl+0x81/0xa0
 [<0>] ? async_page_fault+0x28/0x30
 [<0>] ? system_call_fast_compare_end+0x10/0x15
```

### How Has This Been Tested?

Tested with reproducer added to the ZFS Test Suite.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by loli10K** [comment]
I tried renaming a ZVOL during an incremental `zfs recv` which was being delayed  (mdelay(5s) via systemtap) in `dmu_recv_end()`, so after a successful `zvol_suspend()` but before the `zvol_resume()`:

https://github.com/zfsonlinux/zfs/blob/9b626c126e78cdc36200b66c7cd1dc6a06cf400d/module/zfs/zfs_ioctl.c#L4645-L4647

This system is running code from this PR:

```
ctime(gettimeofday_s())   uid() ppid()  pid()     execname()
---------------------------------------------------------------------------------
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs -> zfs_ioc_recv_impl tofs="testpool/zvol-recv" tosnap="snap2" origin=          (null) ...
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs  -> dmu_recv_stream drc={.drc_ds=0xffff880022117000, .drc_drr_begin=0xffff880012023d08, .drc_drrb=0xffff880012023d10, .drc_tofs="testpool/zvol-recv", .drc_tosnap="snap2", ...
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs  <- dmu_recv_stream return=0
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs  -> zvol_suspend name="testpool/zvol-recv"
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs   -> zvol_find_by_name name="testpool/zvol-recv" mode=1
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs    -> zvol_name_hash name="testpool/zvol-recv"
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs    <- zvol_name_hash return=5434585174035895019
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs    -> zvol_find_by_name_hash name="testpool/zvol-recv" hash=5434585174035895019 mode=1
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs    <- zvol_find_by_name_hash return={.zv_name="testpool/zvol-recv", .zv_volsize=10485760, .zv_volblocksize=8192, ...
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs   <- zvol_find_by_name return={.zv_name="testpool/zvol-recv", .zv_volsize=10485760, .zv_volblocksize=8192, ...
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs  <- zvol_suspend return={.zv_name="testpool/zvol-recv", .zv_volsize=10485760, .zv_volblocksize=8192, ...
Thu Feb  7 18:00:57 2019      0  25941   7146            zfs  -> dmu_recv_end drc={.drc_ds=0xffff880022117000, .drc_drr_begin=0xffff880012023d08, .drc_drrb=0xffff880012023d10, .drc_tofs="testpool/zvol-recv", .drc_tosnap="snap2", ... owner=0x0
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol -> zvol_task_cb param=0xffff88002218bc00
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol  -> zvol_rename_minors_impl oldname="testpool/zvol-recv" newname="testpool/zvol-recv-new"
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol   -> zvol_name_hash name="testpool/zvol-recv-new"
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol   <- zvol_name_hash return=15829768060993764661
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol  <- zvol_rename_minors_impl 
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol <- zvol_task_cb 
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol -> zvol_task_cb param=0xffff880011ba1000
Thu Feb  7 18:01:16 2019      0  25941   7146            zfs  <- dmu_recv_end return=2
Thu Feb  7 18:01:16 2019      0  25941   7146            zfs  -> zvol_resume zv={.zv_name="testpool/zvol-recv-new", .zv_volsize=10485760, ...
Thu Feb  7 18:01:16 2019      0  25941   7146            zfs  <- zvol_resume return=0
Thu Feb  7 18:01:16 2019      0  25941   7146            zfs <- zfs_ioc_recv_impl return=2
Thu Feb  7 18:01:16 2019      0      2   6599         z_zvol <- zvol_task_cb 
```

`zfs recv` exits with errno=ENOENT, the ZVOL is correctly renamed to "zvol-recv-new" and the system seems to be fine:

```
root@linux:/usr/src/zfs# zfs send -i $POOLNAME/zvol@snap1 $POOLNAME/zvol@snap2 | zfs recv $POOLNAME/zvol-recv
cannot open 'testpool/zvol-recv': dataset does not exist
cannot receive incremental stream: dataset does not exist
cannot open 'testpool/zvol-recv': dataset does not exist
root@linux:/usr/src/zfs# zfs list
NAME                     USED  AVAIL     REFER  MOUNTPOINT
testpool                 675K  55.3M       24K  /testpool
testpool/zvol             12K  55.3M       12K  -
testpool/zvol-recv-new    12K  55.3M       12K  -
root@linux:/usr/src/zfs# 
```

File: module/zfs/zvol.c [hunk 1]
```diff
@@ -2252,12 +2252,6 @@ zvol_rename_minors_impl(const char *oldname, const char *newname)
 
 		mutex_enter(&zv->zv_state_lock);
 
-		/* If in use, leave alone */
-		if (zv->zv_open_count > 0) {
-			mutex_exit(&zv->zv_state_lock);
-			continue;
-		}
```
Comment (behlendorf) [inline module/zfs/zvol.c]: According to the comment in https://github.com/zfsonlinux/zfs/issues/4344#issue-134463990 this logic was added to make sure the `zv_name` wasn't updated while being accessed by `zvol_ioctl()`.  This was a concern because it was accessed outside the `zv_state_lock`.  Since this is no longer the case, this should be fine.  This does mean the udev symlink name may change out from underneath us,  which is arguably what we want to happen.

```
Function zvol_rename_minors() does not check the reference count before
modifying the zv_name, which is not good since zvol_ioctl(), for instance,
accesses zv_name without holding zvol_state_lock (but with zv_open_count
being positive).
```

**Comment by behlendorf** [comment]
@bprotopopov would you mind commenting on this PR.

**Comment by behlendorf** [comment]
@tcaputi I agree there's a larger issue to tackle here regarding lookups by zvol name.  Doing this with the objset instead of the name as you suggested is definitely worth exploring as a more complete solution.  I'd like to move forward with this PR as is, which resolves a real existing issue, and then we can follow up with a more comprehensive improvement.

**Comment by bprotopopov** [comment]
Sorry was away from computer on vacation

Typos courtesy of my iPhone

On Feb 19, 2019, at 4:34 PM, Brian Behlendorf <notifications@github.com<mailto:notifications@github.com>> wrote:


@bprotopopov<https://github.com/bprotopopov> would you mind commenting on this PR.
