### PR TITLE
Handle new dnode size in incremental backup stream

### LINKED ISSUE #6366: Invalid backup stream
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Arch Linux
Distribution Version    | N/A
Linux Kernel                 | 4.11.9-1-ARCH
Architecture                 | x86-64
ZFS Version                  | 0.7.0-rc4_95_g94b25662c
SPL Version                  | 0.7.0-rc4_5_g7a35f2b

### Describe the problem you're observing
I have a box with two pools and I'm using `zxfer` to back up daily filesystem snapshots from one of the pools to the other. This fails for one of those filesystems with `cannot receive incremental stream: invalid backup stream`.  Note that I'm running `zfs send -Le`, not sure whether it makes a difference.

I tried to destroy the destination and send everything again. It works for a couple of days, then sends start failing again:

```
bike/zroot                                                 21.8G  33.6G  13.6G  /
bike/zroot@znap_2017-07-04-2100_daily                       460M      -  13.2G  -
bike/zroot@znap_2017-07-05-2100_daily                       122M      -  13.2G  -
bike/zroot@znap_2017-07-06-2100_daily                       119M      -  13.2G  -
bike/zroot@znap_2017-07-07-2100_daily                       365M      -  13.4G  -
bike/zroot@znap_2017-07-08-2100_daily                       131M      -  13.2G  -
bike/zroot@znap_2017-07-09-2100_daily                       114M      -  13.2G  -
bike/zroot@znap_2017-07-10-2100_daily                       133M      -  13.2G  -
bike/zroot@znap_2017-07-11-2100_daily                       161M      -  13.3G  -
bike/zroot@znap_2017-07-12-2100_daily                       158M      -  13.2G  -
bike/zroot@znap_2017-07-13-2100_daily                       147M      -  13.2G  -
bike/zroot@znap_2017-07-14-2100_daily                       514M      -  13.6G  -
bike/zroot@znap_2017-07-15-2100_daily                       155M      -  13.2G  -
bike/zroot@znap_2017-07-16-2100_daily                       150M      -  13.3G  -
bike/zroot@znap_2017-07-17-2100_daily                       155M      -  13.2G  -
tank/zroot                                                 6.04G  1.13T  5.39G  /tank/zroot
tank/zroot@znap_2017-07-08-2100_daily                      57.8M      -  5.41G  -
tank/zroot@znap_2017-07-09-2100_daily                      47.2M      -  5.41G  -
tank/zroot@znap_2017-07-10-2100_daily                      56.8M      -  5.42G  -
tank/zroot@znap_2017-07-11-2100_daily                      68.3M      -  5.44G  -
tank/zroot@znap_2017-07-12-2100_daily                         0B      -  5.39G  -
```

Notice how the transfers stopped working after the July 12th snapshot. Ignore the `REFER` mismatches, `bike/zroot` is configured with `copies=2`.

This _might_ be related to https://github.com/zfsonlinux/zfs/commit/a9f0d7dd89fd9e09ef41ca98d6ba06bbd3d6ea88. I had enabled the `large_dnode` feature before that commit. It was only after that commit that I started seeing these errors for a couple of filesystems. Destroying the destination filesystems and the (older) source snapshots fixed it at that time with the exception of this filesystem here.

### Describe how to reproduce the problem
Not sure. Other filesystems work.

### Include any warning/errors/backtraces from the system logs
Nothing.

### PR DESCRIPTION
**Pull request by nedbass**
### Description

When receiving an incremental backup stream, call
dmu_object_reclaim_dnsize() if an object's dnode size differs between
the incremental source and target. Otherwise it may appear that a
dnode which has shrunk is still occupying slots which are in fact
free. This will cause a failure to receive new objects that should
occupy the now-free slots.

Add a test case to verify that an incremental stream containing
objects with changed dnode sizes can be received without error. This
test case fails without this change.

### Motivation and Context

Fixes #6366

### How Has This Been Tested?

Added test case. Verified test case fails without included code changes.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

File: module/zfs/dmu_send.c [hunk 1]
```diff
@@ -2482,11 +2482,15 @@ receive_object(struct receive_writer_arg *rwa, struct drr_object *drro,
 	} else if (drro->drr_type != doi.doi_type ||
 	    drro->drr_blksz != doi.doi_data_block_size ||
 	    drro->drr_bonustype != doi.doi_bonus_type ||
-	    drro->drr_bonuslen != doi.doi_bonus_size) {
+	    drro->drr_bonuslen != doi.doi_bonus_size ||
+	    (!(drro->drr_dn_slots == 0 &&
+	    doi.doi_dnodesize == DNODE_MIN_SIZE) &&
```
Comment (behlendorf) [inline module/zfs/dmu_send.c]: Is the `!(drro->drr_dn_slots == 0 && doi.doi_dnodesize == DNODE_MIN_SIZE)` portion of this conditional needed at all?  It seems like it's sufficient to solely rely on a difference in the slot count.  If they don't match then worst case we reclaim and reallocate it based on the size provided by the send stream.  If we do need to keep this check for some reason we should find a way to document why since the reason isn't clear (to me at least) with the code alone.

Comment (nedbass) [reply module/zfs/dmu_send.c]: I included that portion because send streams from ZFS versions that don't know about large dnodes will have `drro->drr_dn_slots == 0`, which is treated as if it were set to 1. I wanted to avoid reclaiming the object in this case, mainly because I'm not sure what side effects that will have. But if it's safe to reclaim and reallocate the object then we could certainly drop that part.

Comment (behlendorf) [reply module/zfs/dmu_send.c]: Good thought, my reading of the code is that this is OK and the side effects will be limited too the following all of which are safe.  So this LGTM.

* Kicking any unreferenced dbufs for the dnode out of the cache which is safe.
* Optimizing the bonus space used by SAs.
* A little additional IO since the dnode will be dirtied.

**Comment by behlendorf** [comment]
We're going to need to revisit this test case and possibly revert this change for the moment.  The test case is failing after merging this PR and 4c5b89f59e4e5c8f5b4680040118ebde09598bbe, which both passed when tested independently.

```
Test: /usr/share/zfs/zfs-tests/tests/functional/rsend/send_changed_dnodesize (run as root) [00:01] [FAIL]
00:57:53.86 ASSERTION: Verify incremental receive handles objects with changed dnode size
00:57:53.88 SUCCESS: zfs create -o dnodesize=auto testpool/fs
00:57:54.15 Created 200 files of random sizes up to 262144 bytes
00:57:54.30 SUCCESS: zfs unmount testpool/fs
00:57:54.31 SUCCESS: zfs snapshot testpool/fs@a
00:57:54.32 SUCCESS: zfs mount testpool/fs
00:57:54.34 SUCCESS: rm /testpool/fs/file-262144-0 /testpool/fs/file-262144-1 /testpool/fs/file-262144-10 /testpool/fs/file-262144-100 /testpool/fs/file-262144-101 /testpool/fs/file-262144-102 /testpool/fs/file-262144-103 /testpool/fs/file-262144-104 /testpool/fs/file-262144-105 /testpool/fs/file-262144-106 /testpool/fs/file-262144-107 /testpool/fs/file-262144-108 /testpool/fs/file-262144-109 /testpool/fs/file-262144-11 /testpool/fs/file-262144-110 /testpool/fs/file-262144-111 /testpool/fs/file-262144-112 /testpool/fs/file-262144-113 /testpool/fs/file-262144-114 /testpool/fs/file-262144-115 /testpool/fs/file-262144-116 /testpool/fs/file-262144-117 /testpool/fs/file-262144-118 /testpool/fs/file-262144-119 /testpool/fs/file-262144-12 /testpool/fs/file-262144-120 /testpool/fs/file-262144-121 /testpool/fs/file-262144-122 /testpool/fs/file-262144-123 /testpool/fs/file-262144-124 /testpool/fs/file-262144-125 /testpool/fs/file-262144-126 /testpool/fs/file-262144-127 /testpool/fs/file-262144-128 /testpool/fs/file-262144-129 /testpool/fs/file-262144-13 /testpool/fs/file-262144-130 /testpool/fs/file-262144-131 /testpool/fs/file-262144-132 /testpool/fs/file-262144-133 /testpool/fs/file-262144-134 /testpool/fs/file-262144-135 /testpool/fs/file-262144-136 /testpool/fs/file-262144-137 /testpool/fs/file-262144-138 /testpool/fs/file-262144-139 /testpool/fs/file-262144-14 /testpool/fs/file-262144-140 /testpool/fs/file-262144-141 /testpool/fs/file-262144-142 /testpool/fs/file-262144-143 /testpool/fs/file-262144-144 /testpool/fs/file-262144-145 /testpool/fs/file-262144-146 /testpool/fs/file-262144-147 /testpool/fs/file-262144-148 /testpool/fs/file-262144-149 /testpool/fs/file-262144-15 /testpool/fs/file-262144-150 /testpool/fs/file-262144-151 /testpool/fs/file-262144-152 /testpool/fs/file-262144-153 /testpool/fs/file-262144-154 /testpool/fs/file-262144-155 /testpool/fs/file-262144-156 /testpool/fs/file-262144-157 /testpool/fs/file-262144-158 /testpool/fs/file-262144-159 /testpool/fs/file-262144-16 /testpool/fs/file-262144-160 /testpool/fs/file-262144-161 /testpool/fs/file-262144-162 /testpool/fs/file-262144-163 /testpool/fs/file-262144-164 /testpool/fs/file-262144-165 /testpool/fs/file-262144-166 /testpool/fs/file-262144-167 /testpool/fs/file-262144-168 /testpool/fs/file-262144-169 /testpool/fs/file-262144-17 /testpool/fs/file-262144-170 /testpool/fs/file-262144-171 /testpool/fs/file-262144-172 /testpool/fs/file-262144-173 /testpool/fs/file-262144-174 /testpool/fs/file-262144-175 /testpool/fs/file-262144-176 /testpool/fs/file-262144-177 /testpool/fs/file-262144-178 /testpool/fs/file-262144-179 /testpool/fs/file-262144-18 /testpool/fs/file-262144-180 /testpool/fs/file-262144-181 /testpool/fs/file-262144-182 /testpool/fs/file-262144-183 /testpool/fs/file-262144-184 /testpool/fs/file-262144-185 /testpool/fs/file-262144-186 /testpool/fs/file-262144-187 /testpool/fs/file-262144-188 /testpool/fs/file-262144-189 /testpool/fs/file-262144-19 /testpool/fs/file-262144-190 /testpool/fs/file-262144-191 /testpool/fs/file-262144-192 /testpool/fs/file-262144-193 /testpool/fs/file-262144-194 /testpool/fs/file-262144-195 /testpool/fs/file-262144-196 /testpool/fs/file-262144-197 /testpool/fs/file-262144-198 /testpool/fs/file-262144-199 /testpool/fs/file-262144-2 /testpool/fs/file-262144-20 /testpool/fs/file-262144-21 /testpool/fs/file-262144-22 /testpool/fs/file-262144-23 /testpool/fs/file-262144-24 /testpool/fs/file-262144-25 /testpool/fs/file-262144-26 /testpool/fs/file-262144-27 /testpool/fs/file-262144-28 /testpool/fs/file-262144-29 /testpool/fs/file-262144-3 /testpool/fs/file-262144-30 /testpool/fs/file-262144-31 /testpool/fs/file-262144-32 /testpool/fs/file-262144-33 /testpool/fs/file-262144-34 /testpool/fs/file-262144-35 /testpool/fs/file-262144-36 /testpool/fs/file-262144-37 /testpool/fs/file-262144-38 /testpool/fs/file-262144-39 /testpool/fs/file-262144-4 /testpool/fs/file-262144-40 /testpool/fs/file-262144-41 /testpool/fs/file-262144-42 /testpool/fs/file-262144-43 /testpool/fs/file-262144-44 /testpool/fs/file-262144-45 /testpool/fs/file-262144-46 /testpool/fs/file-262144-47 /testpool/fs/file-262144-48 /testpool/fs/file-262144-49 /testpool/fs/file-262144-5 /testpool/fs/file-262144-50 /testpool/fs/file-262144-51 /testpool/fs/file-262144-52 /testpool/fs/file-262144-53 /testpool/fs/file-262144-54 /testpool/fs/file-262144-55 /testpool/fs/file-262144-56 /testpool/fs/file-262144-57 /testpool/fs/file-262144-58 /testpool/fs/file-262144-59 /testpool/fs/file-262144-6 /testpool/fs/file-262144-60 /testpool/fs/file-262144-61 /testpool/fs/file-262144-62 /testpool/fs/file-262144-63 /testpool/fs/file-262144-64 /testpool/fs/file-262144-65 /testpool/fs/file-262144-66 /testpool/fs/file-262144-67 /testpool/fs/file-262144-68 /testpool/fs/file-262144-69 /testpool/fs/file-262144-7 /testpool/fs/file-262144-70 /testpool/fs/file-262144-71 /testpool/fs/file-262144-72 /testpool/fs/file-262144-73 /testpool/fs/file-262144-74 /testpool/fs/file-262144-75 /testpool/fs/file-262144-76 /testpool/fs/file-262144-77 /testpool/fs/file-262144-78 /testpool/fs/file-262144-79 /testpool/fs/file-262144-8 /testpool/fs/file-262144-80 /testpool/fs/file-262144-81 /testpool/fs/file-262144-82 /testpool/fs/file-262144-83 /testpool/fs/file-262144-84 /testpool/fs/file-262144-85 /testpool/fs/file-262144-86 /testpool/fs/file-262144-87 /testpool/fs/file-262144-88 /testpool/fs/file-262144-89 /testpool/fs/file-262144-9 /testpool/fs/file-262144-90 /testpool/fs/file-262144-91 /testpool/fs/file-262144-92 /testpool/fs/file-262144-93 /testpool/fs/file-262144-94 /testpool/fs/file-262144-95 /testpool/fs/file-262144-96 /testpool/fs/file-262144-97 /testpool/fs/file-262144-98 /testpool/fs/file-262144-99
00:57:54.37 SUCCESS: zfs unmount testpool/fs
00:57:54.38 SUCCESS: zfs set dnodesize=legacy testpool/fs
00:57:54.39 SUCCESS: zfs mount testpool/fs
00:57:54.67 Created 200 files of random sizes up to 262144 bytes
00:57:54.84 SUCCESS: zfs unmount testpool/fs
00:57:54.85 SUCCESS: zfs snapshot testpool/fs@b
00:57:54.94 SUCCESS: eval zfs send testpool/fs@a > /var/tmp/backdir-rsend/fs-dn-auto
00:57:55.02 SUCCESS: eval zfs send -i testpool/fs@a testpool/fs@b > /var/tmp/backdir-rsend/fs-dn-legacy
00:57:55.21 SUCCESS: eval zfs recv testpool/newfs < /var/tmp/backdir-rsend/fs-dn-auto
00:57:55.23 cannot restore to testpool/newfs@b: destination already exists
00:57:55.23 ERROR: eval zfs recv testpool/newfs < /var/tmp/backdir-rsend/fs-dn-legacy exited 1
```
