### PR TITLE
Don't enter zvol's rangelock for read bio with size 0 (#8379)

### LINKED ISSUE #8379: Kernel Oops on ->make_request_fn() of ZFS volume
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	| 16.04 LTS
Linux Kernel	| 4.15.0-36-generic
Architecture	| x86_64
ZFS Version	| 0.7.12, 0.8.0-rc3(following kernel stack trace is from 0.8.0-rc3)
SPL Version	| 

### Describe the problem you're observing

Seeing kernel oops on block I/O against zvol.

```
[  516.185390] BUG: unable to handle kernel paging request at ffffffffc087221a
[  516.185439] IP: avl_insert+0x4f/0xe0 [zavl]
[  516.185454] PGD c00e067 P4D c00e067 PUD c010067 PMD 134267067 PTE 12e333061
[  516.185480] Oops: 0003 [#1] SMP PTI
[  516.185497] Modules linked in: rbd libceph xt_multiport xt_addrtype nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack binfmt_misc isert_scst(OE) qla2x00tgt(OE) ipt_REJECT nf_reject_ipv4 ipmi_devintf ipmi_msghandler qla2xxx(OE) scsi_transport_fc xt_tcpudp iptable_filter iscsi_scst(OE) ip_tables x_tables scst_vdisk(OE) rpcsec_gss_krb5 nfsv4 nfs fscache zfs(POE) zunicode(POE) zavl(POE) icp(POE) zlua(POE) zcommon(POE) znvpair(POE) spl(OE) vmw_balloon crct10dif_pclmul crc32_pclmul ghash_clmulni_intel input_leds joydev pcbc serio_raw aesni_intel aes_x86_64 crypto_simd glue_helper cryptd intel_rapl_perf shpchp vmw_vsock_vmci_transport vsock vmw_vmci mac_hid ib_qib(OE) ib_uverbs(OE) scst(OE) dlm scsi_transport_srp ib_ipoib(OE) mlx4_ib(OE) mlx4_en(OE) ptp pps_core mlx4_core(OE) devlink ib_umad(OE)
[  516.189576]  ib_iser(OE) nfsd auth_rpcgss rdma_cm(OE) iw_cm(OE) nfs_acl ib_cm(OE) lockd grace ib_core(OE) mlx_compat(OE) sunrpc iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi dm_multipath autofs4 btrfs zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear vmwgfx ttm drm_kms_helper syscopyarea sysfillrect sysimgblt mptspi fb_sys_fops mptscsih mptbase psmouse vmxnet3 drm scsi_transport_spi pata_acpi
[  516.192509] CPU: 1 PID: 4804 Comm: d3c81731e21_0 Tainted: P           OE    4.15.0-36-generic #39~16.04.1-Ubuntu
[  516.193660] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 04/05/2016
[  516.195007] RIP: 0010:avl_insert+0x4f/0xe0 [zavl]
[  516.195687] RSP: 0018:ffffb5b3418bfac0 EFLAGS: 00010282
[  516.196266] RAX: ffffffffc087221b RBX: ffff94a02a68d100 RCX: ffffffffc087221b
[  516.196929] RDX: 0000000000000000 RSI: ffff94a02a68d108 RDI: ffff94a032f19530
[  516.197515] RBP: ffffb5b3418bfac0 R08: ffffffffc087221a R09: ffff94a03b003200
[  516.198122] R10: ffff94a02a68d100 R11: 00000000000002e6 R12: ffff94a032f19530
[  516.198838] R13: 0000000000000000 R14: 0000000000000000 R15: ffff94a02a68da00
[  516.199456] FS:  0000000000000000(0000) GS:ffff94a03fc80000(0000) knlGS:0000000000000000
[  516.200186] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  516.200775] CR2: ffffffffc087221a CR3: 000000000c00a005 CR4: 00000000001606e0
[  516.201466] Call Trace:
[  516.202266]  rangelock_enter+0x43a/0x530 [zfs]
[  516.203252]  ? spl_kmem_alloc+0xba/0x150 [spl]
[  516.204058]  zvol_request+0x163/0x2e0 [zfs]
[  516.204704]  generic_make_request+0x122/0x2f0
[  516.205271]  submit_bio+0x73/0x150
[  516.206175]  ? bio_alloc_bioset+0xd2/0x1e0
[  516.207497]  ? submit_bio+0x73/0x150
[  516.208102]  vdisk_blockio_flush+0x81/0x120 [scst_vdisk]
[  516.208855]  vdisk_fsync+0x167/0x180 [scst_vdisk]
[  516.209458]  vdisk_synchronize_cache+0x6d/0xd0 [scst_vdisk]
[  516.210434]  vdev_do_job+0x38/0xc0 [scst_vdisk]
[  516.211605]  blockio_exec+0x83/0x160 [scst_vdisk]
[  516.212699]  scst_do_real_exec+0x5b/0x1c0 [scst]
[  516.213424]  ? _raw_spin_unlock_bh+0x1e/0x20
[  516.213999]  scst_exec_check_blocking+0xbb/0x220 [scst]
[  516.214574]  scst_process_active_cmd+0x8e/0x1b90 [scst]
[  516.215186]  scst_cmd_thread+0x2e5/0x570 [scst]
[  516.215721]  ? wait_woken+0x80/0x80
[  516.216249]  kthread+0x105/0x140
[  516.216723]  ? scst_cmd_done_local+0x90/0x90 [scst]
[  516.217203]  ? kthread_destroy_worker+0x50/0x50
[  516.217589]  ? do_syscall_64+0x73/0x130
[  516.217993]  ? SyS_exit_group+0x14/0x20
[  516.218476]  ret_from_fork+0x35/0x40
[  516.218894] Code: e0 04 48 83 c9 01 48 89 e5 48 09 c8 4d 85 c0 48 c7 06 00 00 00 00 48 c7 46 08 00 00 00 00 48 89 46 10 0f 84 81 00 00 00 48 63 d2 <49> 89 34 d0 49 8b 70 10 8b 04 95 38 81 84 c0 89 f1 83 e1 03 83
[  516.220237] RIP: avl_insert+0x4f/0xe0 [zavl] RSP: ffffb5b3418bfac0
[  516.220680] CR2: ffffffffc087221a
[  516.221128] ---[ end trace 8c29e41f13d9df00 ]---
```

Analysis from from above stack trace.

```
0000000000000580 <avl_insert>:
 580:   e8 00 00 00 00          callq  585 <avl_insert+0x5>
 585:   49 89 d0                mov    %rdx,%r8
 588:   83 e2 01                and    $0x1,%edx
 58b:   48 03 77 10             add    0x10(%rdi),%rsi
 58f:   49 83 e0 fe             and    $0xfffffffffffffffe,%r8
 593:   8d 04 95 00 00 00 00    lea    0x0(,%rdx,4),%eax
 59a:   55                      push   %rbp
 59b:   4c 89 c1                mov    %r8,%rcx
 59e:   48 83 47 18 01          addq   $0x1,0x18(%rdi)
 5a3:   83 e0 04                and    $0x4,%eax
 5a6:   48 83 c9 01             or     $0x1,%rcx
 5aa:   48 89 e5                mov    %rsp,%rbp
 5ad:   48 09 c8                or     %rcx,%rax
 5b0:   4d 85 c0                test   %r8,%r8
 5b3:   48 c7 06 00 00 00 00    movq   $0x0,(%rsi)
 5ba:   48 c7 46 08 00 00 00    movq   $0x0,0x8(%rsi)
 5c1:   00
 5c2:   48 89 46 10             mov    %rax,0x10(%rsi)
 5c6:   0f 84 81 00 00 00       je     64d <avl_insert+0xcd>
 5cc:   48 63 d2                movslq %edx,%rdx
 5cf:   49 89 34 d0             mov    %rsi,(%r8,%rdx,8) <--- Oops on dereferencing
           (R8 + (0 or pointer_size)) for MOV destination, where R8 was 0xffffffffc087221a
 5d3:   49 8b 70 10             mov    0x10(%r8),%rsi
 5d7:   8b 04 95 00 00 00 00    mov    0x0(,%rdx,4),%eax
 5de:   89 f1                   mov    %esi,%ecx
 5e0:   83 e1 03                and    $0x3,%ecx
 5e3:   83 e9 01                sub    $0x1,%ecx
 5e6:   01 c8                   add    %ecx,%eax
 ...
 ...
```

It's dereferencing an invalid pointer at `avl_insert+0x4f/0xe0`,

`5cf:   49 89 34 d0             mov    %rsi,(%r8,%rdx,8)`

which corresponds to below C code,

`parent->avl_child[which_child] = node;`

and R8 contains address for parent AVL node,

`58f:   49 83 e0 fe             and    $0xfffffffffffffffe,%r8`

which corresponds to below C code,

`avl_node_t *parent = AVL_INDEX2NODE(where);`

which originates from `uintptr_t where` argument,

`585:   49 89 d0                mov    %rdx,%r8`

hence it looks like `uintptr_t where` value passed to `avl_insert()` from `avl_add()` whose value was obtained from `avl_find(..., &where)` contained invalid address.

Note that this range lock that caused Oops is for read I/O route, as `rangelock_enter()` call at `zvol_request+0x163/0x2e0` is passing `RL_READER` (=0) for rangelock_type_t type.

```
000000000010d460 <zvol_request>:
  .....
  .....
  10d5ae:       48 8b 75 d0             mov    -0x30(%rbp),%rsi
  10d5b2:       49 8d bd 30 01 00 00    lea    0x130(%r13),%rdi
  10d5b9:       31 c9                   xor    %ecx,%ecx
  10d5bb:       4c 89 f2                mov    %r14,%rdx
  10d5be:       e8 00 00 00 00          callq  10d5c3 <zvol_request+0x163>
```

### Describe how to reproduce the problem

Run below C code in a loop.
* Note that below code assumes `/path/to/block/device` is iSCSI exported block device (zvol) via SCST, so `fsync()` against `/path/to/block/device` results in bio submission by SCST backend against zvol, as you can see in the stack trace above.
* The problem reproduces instantly on my environment.
* Was not able to reproduce the problem against zvol on a local machine.
* Having short sleep like `sleep 0.05` or more between each attempt in the loop made it unable to reproduce the problem.

```
# while [ 1 ]; do
> ./fsync /path/to/block/device
> done
```

```
# cat fsync.c
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
        int fd = open(argv[1], O_RDWR);
        if (fd == -1) {
                perror("open");
                exit(1);
        }

        if (fsync(fd)) {
                perror("fsync");
                exit(1);
        }

        close(fd);

        return 0;
}
```

### PR DESCRIPTION
**Pull request by kusumi**
### Motivation and Context

This fixes #8379.

### Description

The SCST driver (SCSI target driver implementation) and possibly
others may issue read bio's with a length of zero bytes. Although
this is unusual, such bio's issued under certain condition can cause
kernel oops, due to how rangelock is implemented.

rangelock_add_reader() is not made to handle overlap of two (or more)
ranges from read bio's with the same offset when one of them has size
of 0, even though they conceptually overlap. Allowing them to enter
rangelock results in kernel oops by dereferencing invalid pointer,
or assertion failure on AVL tree manipulation with debug enabled
kernel module.

For example, this happens when read bio whose (offset, size) is
(0, 0) enters rangelock followed by another read bio with (0, 4096)
when (0, 0) rangelock is still locked, when there are no pending
write bio's. It can also happen with reverse order, which is (0, N)
followed by (0, 0) when (0, N) is still locked. More details
mentioned in #8379.

Prevent this by returning bio with size 0 as success without entering
rangelock. This has been done for write bio after checking flusher
bio case (though not for the same reason), but not for read bio.

### How Has This Been Tested?

With the test code mentioned in #8379.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by kusumi** [comment]
Fixed typo/etc in commit message and force pushed. The diff hasn't changed from the initial one.

File: module/zfs/zvol.c [hunk 1]
```diff
@@ -1008,6 +1008,16 @@ zvol_request(struct request_queue *q, struct bio *bio)
 				zvol_write(zvr);
 		}
 	} else {
+		/*
+		 * rangelock_add_reader() can't handle overlap of two ranges
+		 * with the same offset when either has length 0, so return
+		 * without entering rangelock if it's a read bio with size 0.
+		 */
```
Comment (behlendorf) [inline module/zfs/zvol.c]: This fix looks good to me, but how about rephrasing the comment a little to explain how a size of zero can happen.  I think that would better get at the heart of the issue since the zero length is the unusual condition.  The range lock code itself handled this condition as expected.  How about something like:

```c
/*
 * The SCST driver, and possibly others, may issue READ IOs with a
 * length of zero bytes.  These empty IOs contain no data and require
 * no additional handling.
 */
```

Comment (kusumi) [reply module/zfs/zvol.c]: ok, will change to it.

Comment (kusumi) [reply module/zfs/zvol.c]: Updated via force push.

File: module/zfs/zvol.c [hunk 2]
```diff
@@ -1008,6 +1008,16 @@ zvol_request(struct request_queue *q, struct bio *bio)
 				zvol_write(zvr);
 		}
 	} else {
+		/*
```
Comment (alek-p) [inline module/zfs/zvol.c]: LGTM. I would `ASSERT3S(rw, ==, READ)` here but that's not really direcly related to this patch so feel free to leave as is
