### PR TITLE
Pool allocation classes misplacing small file blocks

### LINKED ISSUE #8351: Documentation: special_small_blocks does not operate as described in man page
Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	|  Stretch (9.6)
Linux Kernel	|  Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27)
Architecture	| x64
ZFS Version	| 0.8.0-rc3
SPL Version	| 0.8.0-rc3

### Describe the problem you're observing

The man page states that the value `special_small_blocks` "represents the threshold block size for including small file blocks into the special allocation class."  Based on this description, I would expect any block smaller than, or equal to, special_small_blocks to be assigned to the special allocation. 

However, testing indicates that this property behaves slightly differently.  Only blocks smaller than `special_small_blocks `will be allocated to the special allocation.  Blocks that are equal to `special_small_blocks` will be placed in the regular vdev allocation. 

As an example, if I set `recordsize=64`k, `special_small_blocks=64k`, and set `compression=off,` all blocks from a VM image are allocated to the regular vdev.  However, setting `recordsize=32k`will ensure the blocks are saved to the special allocation.  Similarly, setting `special_small_blocks=128k` will ensure the same for `recordsize=64k`.

### Describe how to reproduce the problem

1.  Create a testpool with a special allocation class vdev
2.  Create a new dataset with `recordsize=64k`, `special_small_blocks=64k`, and` compression=of`f on the
3.  Copy a large file to the dataset while monitoring with `zpool iostat - v 1`

### Resolution

A more accurate man page summary might say something like the following, "This value represents the threshold block size for including small file blocks into the special allocation class.  Blocks smaller than this value will be assigned to the special allocation class while blocks equal to or greater than this value will be assigned to the regular allocation."

### PR DESCRIPTION
**Pull request by loli10K**
### Motivation and Context

Fix #8351 

NOTE: i am not sure this fix is correct, maybe the way it is currently implemented is already "working as intended" and we just need to update the man page, but the "alloc_class_012_pos" test case seems to suggest that setting `recordsize == special_small_blocks` should force allocations on the special vdev (which is *almost* not happening):

```
Test: /usr/share/zfs/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos (run as root) [00:19] [PASS]
06:26:25.65 ASSERTION: Removing a special device from a pool succeeds.
06:26:25.65 SUCCESS: disk_setup
06:26:25.80 SUCCESS: zpool create testpool /mnt/device-0 /mnt/device-1 /mnt/device-2 special /mnt/device-3 special /mnt/device-4
06:26:27.83 SUCCESS: display_status testpool
06:26:27.86 SUCCESS: zfs create -o special_small_blocks=32K -o recordsize=32K testpool/testfs
06:26:28.01 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.1 bs=1M count=25
06:26:28.31 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.2 bs=1M count=50
06:26:29.45 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.3 bs=1M count=75
06:26:30.68 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.4 bs=1M count=100
06:26:30.89 SUCCESS: zpool sync testpool
06:26:30.89 SUCCESS: sync_pool testpool
06:26:30.89 NAME              SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
06:26:30.89 testpool         3.75G   251M  3.50G        -         -     0%     6%  1.00x    ONLINE  -
06:26:30.89   /mnt/device-0   960M  85.2M   875M        -         -     0%  8.88%      -  ONLINE  
06:26:30.89   /mnt/device-1   960M  79.1M   881M        -         -     0%  8.23%      -  ONLINE  
06:26:30.89   /mnt/device-2   960M  85.7M   874M        -         -     0%  8.92%      -  ONLINE  
06:26:30.89 special              -      -      -        -         -      -      -      -  -
06:26:30.89   /mnt/device-3   480M   426K   480M        -         -     0%  0.08%      -  ONLINE  
06:26:30.89   /mnt/device-4   480M   428K   480M        -         -     0%  0.08%      -  ONLINE  
06:26:30.90 SUCCESS: zpool list -v testpool
```

### Description

Due to an off-by-one condition in `spa_preferred_class()` we are picking the "normal" allocation class instead of the "special" one for file blocks with size equal to the special_small_blocks property value.

This change fix the small code issue, update the ZFS Test Suite and the zfs(8) man page.

### How Has This Been Tested?

When `recordsize == special_small_blocks` file blocks are placed in the special vdev:

```
root@linux:~# POOLNAME='testpool'
root@linux:~# TMPDIR='/var/tmp'
root@linux:~# mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
root@linux:~# zpool destroy $POOLNAME
cannot open 'testpool': no such pool
root@linux:~# rm -f $TMPDIR/zpool_$POOLNAME.*.dat
root@linux:~# truncate -s 128m $TMPDIR/zpool_$POOLNAME.normal.dat
root@linux:~# truncate -s 128m $TMPDIR/zpool_$POOLNAME.special.dat
root@linux:~# zpool create $POOLNAME $TMPDIR/zpool_$POOLNAME.normal.dat special $TMPDIR/zpool_$POOLNAME.special.dat
root@linux:~# zfs create -o mountpoint=/mnt/specialfs -o recordsize=32K -o special_small_blocks=32K $POOLNAME/specialfs
root@linux:~# dd if=/dev/zero of=/mnt/specialfs/zero bs=1M count=10
10+0 records in
10+0 records out
10485760 bytes (10 MB) copied, 0.046305 s, 226 MB/s
root@linux:~# zpool list -v
NAME                                    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
testpool                                224M  9.96M   214M        -         -     0%     4%  1.00x    ONLINE  -
  /var/tmp/zpool_testpool.normal.dat    112M      0   112M        -         -     0%  0.00%      -  ONLINE  
special                                    -      -      -        -         -      -      -      -  -
  /var/tmp/zpool_testpool.special.dat   112M  9.96M   102M        -         -     3%  8.89%      -  ONLINE  
root@linux:~# 
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Thanks, Yes, we should verify with @don-brady, but my feeling is that you've got the correct fix here.  As I recall this was intended to be inclusive of the blocksize specified.

This is a slight digression but allocation class related.   There's a case to be made spill blocks should also be considered to be metadata. When in use they're virtually always storing xattrs which are metadata, likely selinux xattrs, which we need to be fast. This should be a small change and I think it would better align the allocation class behavior with users expectations.  That said, we should get a different PR open for this issue.  This was brought up in #8130.

File: module/zfs/spa_misc.c [hunk 1]
```diff
@@ -1851,7 +1851,7 @@ spa_preferred_class(spa_t *spa, uint64_t size, dmu_object_type_t objtype,
 	 * zfs_special_class_metadata_reserve_pct exclusively for metadata.
 	 */
 	if (DMU_OT_IS_FILE(objtype) &&
-	    has_special_class && size < special_smallblk) {
+	    has_special_class && size <= special_smallblk) {
```
Comment (richardelling) [inline module/zfs/spa_misc.c]: I recommended this change in the original PR, it makes better sense to me.

File: tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh [hunk 2]
```diff
@@ -24,6 +24,22 @@
...
+# According to the pool layout used in this test vdev_id 3 and 4 are special
+#
+function file_in_special_vdev # <dataset> <inode>
+{
+	typeset dataset="$1"
+	typeset inum="$2"
+
+	zdb -ddddd $dataset $inum | awk '/L0 [0-9]+/ {
+		match($3,"([^:]+):.*",dva);
+		if(dva[1] < 3)
```
Comment (richardelling) [inline tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh]: [stretch goal]
I'd like to see this function become more generic and moved to libtest.shlib.
More specifically, pass in the expected vdev name (eg "mirror-0") as an argument. From "mirror-0" we find the instance (3, in the example here) and compare all of the dvas for the block for inclusion.  This will allow us to more easily write tests that check for copies or otherwise look at where a specific set of blocks are allocated.

Comment (loli10K) [reply tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh]: Without a parsable `zpool status` output (which AFAIK is the only `zpool` output showing redundant devices with unique names) it is not easy to map "mirror-0" to a guid/vdevid number. Parsing `zdb` output is not an option either.

I can see this function becoming more generic once we get http://open-zfs.org/wiki/Vdev_Properties though.

Comment (richardelling) [reply tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh]: It is parseable with the `zdb -C` output. Try something like this:
```
zdb -C testpool |  awk '
  $1=="type:" {type=$2}
  $1=="id:" {id=$2} 
  $1=="guid:" {guid=$2}
  $1=="path:" {path=$2}
  $1~/^children/ {printf("type=%s id=%s guid=%s path=%s\n", type, id, guid, path)} 
  END {printf("type=%s id=%s guid=%s path=%s\n", type, id, guid, path)}
'
``` 
Then if you know the device you are seaching for, it becomes easy to get its id or its parent's id. For the parent you also get the type, so relatively simple to get 'type=mirror'  with  'path=/dev/sda' with 'id=1' where id is also the dva id.

For real-world parsing, we try to directly read the nvlist or convert the nvlist to JSON and parse it with a more object-friendly language like go or python (in other words, not awk or shell). `nvlist_print_json()` is your friend for the conversion, but there is more to understanding the resulting JSON than expected.

In retrospect, it would be nice to have a top-level vdev annotation that is more flexible than booleans like `is_log` but that horse already left the barn.

Comment (loli10K) [reply tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh]: Consider the following layout:

```
root@linux:~# zdb -C testpool |  awk '
  $1=="type:" {type=$2}
  $1=="id:" {id=$2} 
  $1=="guid:" {guid=$2}
  $1=="path:" {path=$2}
  $1~/^children/ {printf("type=%s id=%s guid=%s path=%s\n", type, id, guid, path)} 
  END {printf("type=%s id=%s guid=%s path=%s\n", type, id, guid, path)}
'
type='root' id=0 guid=9264953930665662240 path=
type='mirror' id=0 guid=7373751702954239063 path=
type='file' id=0 guid=7368990276599147716 path='/var/tmp/vdev1'
type='file' id=1 guid=4769494959538226270 path='/var/tmp/vdev2'
type='mirror' id=1 guid=4074419556359544368 path='/var/tmp/vdev2'
type='file' id=0 guid=4562404146963926287 path='/var/tmp/vdev3'
type='file' id=1 guid=7285901949148168926 path='/var/tmp/vdev4'
type='file' id=2 guid=13620745756185228281 path='/var/tmp/vdev5'
```

Is "/var/tmp/vdev5" part of the second mirror (3-way mirror) or a top level vdev?
